import type {ScenarioPack} from '../scenario-types.ts';

/**
 * 가상(IF) 대본 B — 중편 「업성의 왕」(cao_zhi)·「촉의 사마의」(shu), 그 뒤의 갈림길 둘,
 * 하편 「시인의 천하」·「선양의 날」·「한실 부흥」·「촉의 승상」·「이른 정변」·「천하통일」과 결말.
 * 가상 시나리오는 이 게임의 창작이다.
 */
const pack:ScenarioPack={chapters:[
// ════════════════════════════════════════════════════════════════
// 중편 가상 · 업성의 왕 (cao_zhi) — 적: 허저·조진·조휴(또는 장료)·조비
// ════════════════════════════════════════════════════════════════
{id:'IF2-zhi-1',year:'220년 · 업성',title:'업성 봉기',
  synopsis:'조조가 숨을 거둔 밤, 사마의는 업성의 조식을 위왕으로 세우기로 한다. 조비의 호위 대장 허저가 성 밖에 진을 치고 성문을 열라 외친다. 허저를 물리쳐야 봉기가 산다.',
  scenes:[
    {place:'업성 · 동작대 아래',art:5,cast:[
      {name:'조식',look:'civil',at:[62,52],face:'left'},
      {name:'양수',look:'strategist',at:[76,58],face:'left'},
      {name:'사마의',look:'strategist'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'220년 정월, 낙양에서 조조가 숨을 거두었다. 그 소식이 닿은 밤, 업성 동작대 아래 등불 하나가 꺼지지 않았다.'},
      {enter:'사마의',at:[32,60],from:'left'},
      {say:'조식',line:'중달이 이 밤에 업성까지 오다니. 형님 대신 나를 택했다는 말을 믿어도 되겠소?',to:'사마의'},
      {say:'사마의',line:'믿으시든 아니든, 저는 이미 강을 건넜습니다. 돌아갈 배는 태워 두었지요.'},
      {emote:'양수',text:'!'},
      {move:'양수',to:[50,60]},
      {say:'양수',line:'하하, 계륵이 아니라 대들보가 굴러들어 왔구려. 공자, 이 사람은 조비의 사람이 아닙니다.'},
      {enter:'전령',at:[88,64],from:'right'},
      {say:'전령',line:'급보요! 허저가 호위 기병을 끌고 남문 밖에 진을 쳤습니다! 성문을 열라 외칩니다!'},
      {emote:'조식',text:'땀'},
      {say:'사마의',line:'호치가 왔군요. 성문은 제가 맡겠습니다. 공자께서는 붓을 놓지 마십시오. 사람들이 공자를 보고 있습니다.'},
    ]},
    {place:'업성 · 남문 성루',art:8,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'장합',look:'cavalry',at:[58,62],face:'left'},
      {name:'곽회',look:'archer',at:[26,64]},
      {name:'업성 병사',look:'spear',at:[72,70],face:'left'}],
    steps:[
      {say:'장합',line:'허저는 웃통을 벗고 마초와 싸운 장사요. 성문을 열고 맞붙으면 그 무게를 감당하기 어렵소.'},
      {emote:'곽회',text:'…'},
      {say:'곽회',line:'성 안 문사와 가동까지 모으면 머릿수는 채웁니다. 다만 붓 쥐던 손이 창을 쥐겠습니까.'},
      {move:'사마의',to:[46,56]},
      {choice:'사마의',options:[
        {id:'militia',text:'업성의 문사와 가동을 모두 무장시킨다.',reply:'성을 지키는 데 붓과 창을 가릴 겨를은 없다.',answer:{speaker:'곽회',line:'명대로 하지요. 다만 피 흘린 집이 많을 것입니다.'},note:'업성 의용병 2부대가 초록 깃발로 돕는다 · 백성의 원망이 남는다',
          effects:[{kind:'reinforce',name:'업성 의용병',unitClass:'infantry',side:'npc'},{kind:'reinforce',name:'업성 가동',unitClass:'spearman',side:'npc'},{kind:'flag',flag:'zhi_burden'}]},
        {id:'yang_xiu',text:'양수를 군사로 삼아 성 안의 지휘를 맡긴다.',reply:'재주 많은 자는 쓰기 어렵다. 그러나 쓰지 않으면 더 위험하다.',answer:{speaker:'장합',line:'그 입만 다물면 쓸 만한 사람이오.'},note:'양수 영입(책사) · 책략 MP +15',
          effects:[{kind:'recruit',name:'양수',unitClass:'strategist'},{kind:'insight'},{kind:'flag',flag:'zhi_yangxiu'}]},
        {id:'night',text:'해가 뜨기 전에 허저의 진을 친다.',reply:'호랑이는 잠들었을 때 잡는 것이다.',note:'기습 · 적 전원 체력 80%로 시작',
          effects:[{kind:'ambush'},{kind:'flag',flag:'zhi_night_raid'}]},
      ]},
      {emote:'장합',text:'!'},
      {exit:'업성 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'업성 · 남문 밖',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'양수',look:'strategist',at:[24,64]},
      {name:'조식',look:'civil'}],
    steps:[
      {narrate:'허저는 끝내 성문을 넘지 못하고 낙양 쪽으로 말머리를 돌렸다.'},
      {enter:'조식',at:[58,58],from:'right'},
      {say:'조식',line:'업성이 버텼소! 오늘 밤은 시 한 수로는 모자라겠구려.',to:'사마의'},
      {say:'조식',line:'…창을 쥐고 쓰러진 문사들의 이름은 내가 하나하나 비석에 새기겠소.',when:'zhi_burden'},
      {emote:'양수',text:'♪'},
      {say:'양수',line:'어둠 속에서 호치의 수염을 그을렸지요. 허저가 낙양에 가서 무어라 고할지 궁금하군요.',when:'zhi_night_raid'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'시는 허창을 얻은 뒤에 지으시지요. 천자가 계신 곳을 쥐는 자가 명분을 쥡니다.'},
    ]},
  ]},

{id:'IF2-zhi-2',year:'220년 · 허창',title:'허창 탈취',
  synopsis:'천자가 있는 허창을 쥐는 자가 명분을 쥔다. 조씨 종실의 대들보 조진이 허창을 지킨다. 한때 함께 싸운 벗과 칼을 맞댈 차례다.',
  scenes:[
    {place:'업성 · 군막',art:14,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'양수',look:'strategist',at:[58,60],face:'left'},
      {name:'사마랑',look:'physician'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'업성의 봉기는 사흘 만에 하북에 퍼졌다. 그러나 천자는 여전히 허창에 있었다.'},
      {enter:'사마랑',at:[24,64],from:'left'},
      {say:'사마랑',line:'허창은 조진이 지킨다. 성문을 닫고 천자를 모셨으니, 우리가 치면 역적이 되는 셈이다.',to:'사마의'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'자단(조진)이라. 관중에서 함께 마초를 막던 사람입니다. 그의 칼은 곧고, 그래서 꺾기 어렵지요.'},
      {say:'양수',line:'곧은 칼은 옆에서 치면 부러집니다. 허창 성 안의 문관 반은 이미 제 편지를 받았습니다.',when:'zhi_yangxiu'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'장안의 언릉후 조창께서 사람을 보냈습니다! 아우 조식을 돕겠다 하십니다!'},
      {emote:'양수',text:'!'},
    ]},
    {place:'허창 · 성문 앞',art:2,cast:[
      {name:'사마의',look:'strategist',at:[36,64]},
      {name:'곽회',look:'archer',at:[20,68]},
      {name:'조진',look:'heavy',at:[62,44],face:'left'},
      {name:'허창 수비병',look:'spear',at:[76,46],face:'left'}],
    steps:[
      {say:'조진',line:'중달! 자네가 역적의 깃발 아래 서다니. 선왕께서 자네를 어찌 대하셨는지 잊었는가!'},
      {move:'사마의',to:[46,60]},
      {say:'사마의',line:'잊지 않았네. 그래서 선왕의 아들 가운데 천하를 덜 해칠 분을 골랐을 뿐일세.'},
      {emote:'조진',text:'분노'},
      {move:'허창 수비병',to:[70,48]},
      {choice:'사마의',options:[
        {id:'mandate',text:'천자께 표를 올려 명분부터 얻는다.',reply:'칼보다 먼저 붓이다. 천자의 조서 한 장이 성벽 하나보다 무겁다.',note:'아군 전원 첫 턴 방어 태세 · 천자의 명분이 남는다',
          effects:[{kind:'guard'},{kind:'flag',flag:'zhi_mandate'}]},
        {id:'cang',text:'조창의 기병을 불러 함께 친다.',reply:'황수아(조창)는 형제 다툼에 칼을 아낄 사람이 아니다.',answer:{speaker:'곽회',line:'수염 노란 장수가 오면 허창 수비병은 겁부터 먹을 겁니다.'},note:'조창 영입(기병) · 처음 2턴 사기 상승',
          effects:[{kind:'recruit',name:'조창',unitClass:'cavalry'},{kind:'rally'},{kind:'flag',flag:'zhi_cang'}]},
        {id:'letter',text:'조휴에게 거짓 서신을 보내 동쪽 군을 묶어 둔다.',reply:'천리구는 빨리 달린다. 그러니 엉뚱한 곳으로 달리게 하면 된다.',note:'다음 전장이 「장료의 북상」으로 바뀐다 · 책략 MP +15',
          effects:[{kind:'path',tale:'IF2-zhi-3x'},{kind:'insight'},{kind:'flag',flag:'zhi_false_letter'}]},
      ]},
      {exit:'조진',to:'right'},
    ]},
  ],
  after:[
    {place:'허창 · 궁 앞뜰',art:5,cast:[
      {name:'사마의',look:'strategist',at:[38,60]},
      {name:'조진',look:'heavy',at:[60,62],face:'left'},
      {name:'조식',look:'civil'}],
    steps:[
      {narrate:'허창의 성문이 열렸다. 사로잡힌 조진은 칼을 내려놓고도 고개를 숙이지 않았다.'},
      {say:'조진',line:'베게, 중달. 조씨의 장수가 조씨에게 진 것이니 부끄럽지는 않네.'},
      {say:'사마의',line:'자네 칼은 조씨를 위한 칼이지. 공자도 조씨일세. 칼집에 넣어 두게, 쓸 날이 올 걸세.'},
      {emote:'조진',text:'…'},
      {enter:'조식',at:[80,58],from:'right'},
      {say:'조식',line:'천자께서 조서를 내리셨소. 위왕의 인수가 이제 내 손에 있소!',when:'zhi_mandate'},
      {exit:'조진',to:'left'},
    ]},
  ]},

{id:'IF2-zhi-3',year:'221년 · 업성 동쪽',title:'종친의 반격',
  synopsis:'천리구라 불린 조휴가 동쪽 군을 이끌고 업성으로 내달린다. 업성에는 조식의 처자와 문사들이 남아 있다. 그를 막지 못하면 조식의 왕위는 사흘을 넘기지 못한다.',
  scenes:[
    {place:'허창 · 궁정',art:5,cast:[
      {name:'조식',look:'civil',at:[62,54],face:'left'},
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마랑',look:'physician',at:[24,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {enter:'전령',at:[86,64],from:'right'},
      {say:'전령',line:'조휴가 청주와 서주의 군을 이끌고 업성으로 내달립니다! 하루에 이백 리를 달린다 합니다!'},
      {emote:'조식',text:'땀'},
      {move:'조식',to:[54,56]},
      {say:'조식',line:'업성에는 내 처자와 시를 함께 짓던 벗들이 있소. 중달, 그들을 버릴 수는 없소.'},
      {say:'사마의',line:'버리지 않습니다. 천리구는 빨리 달리니, 지친 말로 업성에 닿을 것입니다. 그 앞을 막으면 됩니다.'},
      {say:'사마랑',line:'허창은 내가 지키마. 천자 곁에 사마씨 한 사람은 있어야 하지 않겠느냐.',to:'사마의'},
      {exit:'전령',to:'right'},
    ]},
    {place:'업성 동쪽 · 장수 여울',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'장합',look:'cavalry',at:[56,64],face:'left'},
      {name:'곽회',look:'archer',at:[24,66]},
      {name:'조창',look:'cavalry'}],
    steps:[
      {narrate:'장수(漳水)의 여울 위로 새벽 안개가 깔렸다. 조휴의 선봉이 반나절 거리에 있다.'},
      {enter:'조창',at:[72,58],from:'right',when:'zhi_cang'},
      {say:'조창',line:'휴(조휴) 녀석은 어려서부터 말만 빨랐지. 내가 정면에서 받아 주겠소!',when:'zhi_cang'},
      {move:'장합',to:[60,60]},
      {emote:'곽회',text:'?'},
      {choice:'사마의',options:[
        {id:'ford',text:'여울 양쪽 갈대밭에 복병을 묻는다.',reply:'말이 물을 건널 때가 가장 약하다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
        {id:'scout',text:'척후를 풀어 조휴의 별동대를 먼저 끊는다.',reply:'천리구의 다리 하나를 먼저 묶는다.',answer:{speaker:'곽회',line:'별동대는 북쪽 둑길로 돌고 있을 겁니다. 제가 끊지요.'},note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
        {id:'poet',text:'조식 공에게 진 앞에 나서 종친에게 호소하게 한다.',reply:'조씨가 조씨를 부르는 소리는 내 말보다 멀리 간다.',answer:{speaker:'장합',line:'왕이 몸소 나서면 병사들 눈빛이 달라질 것이오.'},note:'처음 2턴 사기 상승 · 조식이 전장에 선 일이 남는다',
          effects:[{kind:'rally'},{kind:'flag',flag:'zhi_poet_front'}]},
      ]},
      {emote:'장합',text:'!'},
    ]},
  ],
  after:[
    {place:'업성 동쪽 · 장수 여울',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'조식',look:'civil',at:[56,58],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'조휴는 여울에서 말을 잃고 동쪽으로 달아났다. 업성은 지켜졌다.'},
      {say:'조식',line:'진 앞에 서 보니 알겠소. 시 한 줄보다 병사 하나의 숨이 무겁구려.',when:'zhi_poet_front'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'낙양에서 급보! 조비가 몸소 친위대를 이끌고 낙양을 나섰습니다!'},
      {emote:'조식',text:'…'},
      {say:'사마의',line:'형님께서 마침내 직접 오시는군요. 이제 형제의 일은 형제가 끝내야 합니다.'},
      {exit:'전령',to:'right'},
    ]},
  ]},

{id:'IF2-zhi-3x',year:'221년 · 업성 남쪽',title:'장료의 북상',
  synopsis:'거짓 서신에 조휴는 엉뚱한 곳에 묶였다. 그러나 조비는 합비의 장료를 불러올렸다. 강동의 아이 울음을 그치게 하던 이름이 업성으로 내달린다.',
  scenes:[
    {place:'업성 · 남쪽 성벽',art:8,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'양수',look:'strategist',at:[24,62]},
      {name:'장합',look:'cavalry',at:[58,62],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'조휴는 서신대로 서주에서 발이 묶였다. 그 빈자리를 메운 것은 더 무서운 이름이었다.'},
      {enter:'전령',at:[86,64],from:'right'},
      {say:'전령',line:'합비의 장료가 북상합니다! 기병 팔백으로 길을 열고 본대가 뒤따른다 합니다!'},
      {emote:'장합',text:'!'},
      {say:'장합',line:'요래요래, 강동의 아이들이 울음을 그친다는 그 장료요. 팔백으로 손권 십만을 흔든 사람이오.'},
      {say:'양수',line:'계책 하나로 범 하나를 묶었더니 늑대 하나가 왔군요. 승상, 웃어야 합니까 울어야 합니까.'},
      {move:'사마의',to:[48,56]},
      {say:'사마의',line:'둘 다 아니오. 장료는 빠르나 멀리서 왔소. 지친 범은 고양이와 다르지 않지.'},
      {exit:'전령',to:'right'},
      {choice:'사마의',options:[
        {id:'ferry',text:'황하 나루의 배를 모두 거둬 장료의 뒤를 끊는다.',reply:'돌아갈 길이 없음을 알면 팔백도 흔들린다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
        {id:'militia',text:'업성 의용병을 다시 불러 성벽을 채운다.',reply:'업성이 다시 한번 피를 흘려야겠구나.',note:'업성 의용병이 초록 깃발로 돕는다 · 백성의 원망이 남는다',effects:[{kind:'reinforce',name:'업성 의용병',unitClass:'spearman',side:'npc'},{kind:'flag',flag:'zhi_burden'}]},
        {id:'duel',text:'장합에게 장료와 정면으로 맞서게 한다.',reply:'명장은 명장으로 받는다.',answer:{speaker:'장합',line:'평생 한 번은 겨뤄 보고 싶던 상대요!'},note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
    ]},
  ],
  after:[
    {place:'업성 남쪽 · 들판',art:16,cast:[
      {name:'사마의',look:'strategist',at:[40,62]},
      {name:'장료',look:'cavalry',at:[66,58],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'장료는 끝내 성벽에 닿지 못했다. 그는 칼을 거두고 말 위에서 사마의를 바라보았다.'},
      {say:'장료',line:'중달, 그대의 왕이 오래가기를 바라오. 나는 합비로 돌아가 강동이나 막겠소.'},
      {exit:'장료',to:'right'},
      {enter:'전령',at:[84,64],from:'right'},
      {say:'전령',line:'조비가 몸소 친위대를 이끌고 낙양을 나섰습니다!'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'cao_zhi:boss',year:'221년 · 낙양 교외',title:'형제의 싸움',
  synopsis:'조비가 친위대를 이끌고 몸소 나섰다. 콩을 삶는데 콩대를 태우는 싸움, 형과 아우가 낙양 들판에서 마주 선다. 조비를 꺾어야 조식이 위왕이 된다.',
  scenes:[
    {place:'낙양 교외 · 군막',art:14,cast:[
      {name:'조식',look:'civil',at:[60,56],face:'left'},
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'양수',look:'strategist'},
      {name:'사마랑',look:'physician'}],
    steps:[
      {narrate:'낙양 동쪽 들판, 두 개의 위(魏) 깃발이 마주 섰다.'},
      {emote:'조식',text:'…'},
      {say:'조식',line:'어려서 형님은 나를 업고 동작대에 오르곤 했소. 그 등에 칼을 겨누게 될 줄이야.'},
      {enter:'양수',at:[76,62],from:'right'},
      {say:'양수',line:'왕이 되시려면 형님은 잊으십시오. 저쪽은 공자를 잊은 지 오래입니다.'},
      {enter:'사마랑',at:[22,64],from:'left'},
      {say:'사마의',line:'잊으실 필요는 없습니다. 이기고 나서 기억하시면 됩니다.',to:'조식'},
    ]},
    {place:'낙양 교외 · 두 진 사이',art:16,cast:[
      {name:'사마의',look:'strategist',at:[30,62]},
      {name:'조식',look:'civil',at:[42,60]},
      {name:'조비',look:'strategist',at:[72,56],face:'left'},
      {name:'친위병',look:'heavy',at:[84,62],face:'left'}],
    steps:[
      {move:'조비',to:[62,58]},
      {say:'조비',line:'자건(조식)아, 일곱 걸음 안에 시를 지어 보아라. 짓지 못하면 네 목을 베겠다.'},
      {move:'조식',to:[50,58]},
      {say:'조식',line:'콩을 삶는데 콩대를 태우니, 콩이 솥 안에서 우는구나. 본디 한 뿌리에서 났거늘, 어찌 이리 급히 볶는가.'},
      {emote:'조비',text:'분노'},
      {say:'조비',line:'사마의! 아비가 그토록 경계하던 이리가 결국 내 아우의 등에 붙었구나!'},
      {choice:'사마의',options:[
        {id:'spare',text:'조비는 사로잡되 목숨은 살린다고 온 군에 알린다.',reply:'형을 죽인 왕은 오래가지 못한다.',answer:{speaker:'조식',line:'고맙소, 중달. 그 말 한마디로 내 마음이 가볍소.'},note:'아군 전원 첫 턴 방어 태세 · 조비의 목숨이 남는다',
          effects:[{kind:'guard'},{kind:'flag',flag:'zhi_spare_pi'}]},
        {id:'strike',text:'조비의 본진을 곧장 친다.',reply:'싸움은 짧을수록 덜 슬프다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
        {id:'henei',text:'하내 의병을 부르고 형님(사마랑)에게 뒤를 맡긴다.',reply:'사마씨 고향의 사람들이 오늘 왕을 만든다.',answer:{speaker:'조식',line:'하내의 은혜를 잊지 않겠소.'},note:'하내 의병이 초록 깃발로 돕는다 · 처음 2턴 사기 상승',
          effects:[{kind:'reinforce',name:'하내 의병',unitClass:'infantry',side:'npc'},{kind:'rally'}]},
      ]},
      {exit:'친위병',to:'right'},
    ]},
  ],
  after:[
    {place:'낙양 · 궁문 앞',art:2,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'조식',look:'civil',at:[54,58],face:'left'},
      {name:'조비',look:'strategist'}],
    steps:[
      {narrate:'조비의 친위대가 무너졌다. 조식은 낙양에 들어가 위왕의 자리에 올랐다.'},
      {enter:'조비',at:[78,62],from:'right',when:'zhi_spare_pi'},
      {say:'조비',line:'아우야, 너는 왕이 되었구나. 나는 안향으로 가서 시나 짓겠다. 네가 늘 하던 대로.',when:'zhi_spare_pi'},
      {exit:'조비',to:'right',when:'zhi_spare_pi'},
      {narrate:'조비는 난전 속에 화살을 맞고 쓰러졌다. 조식은 형의 시신 앞에서 오래 울었다.',unless:'zhi_spare_pi'},
      {emote:'조식',text:'…'},
      {say:'사마의',line:'왕이시여, 이제 천하가 왕의 시를 기다립니다. 정사는 신이 맡겠습니다.'},
      {narrate:'그로부터 여섯 해, 시를 사랑하는 왕은 조정을 사마의에게 맡겼다.'},
    ]},
  ]},

{id:'fate:3:cao_zhi',year:'226년 · 낙양',title:'왕의 재상',
  synopsis:'조식이 위왕이 된 지 여러 해. 시를 사랑하는 왕은 정사를 사마의에게 맡겼다. 천하는 아직 셋으로 나뉘어 있고, 조정은 사마의의 손 안에 있다.',
  scenes:[
    {place:'낙양 · 위왕의 궁정',art:5,cast:[
      {name:'조식',look:'civil',at:[70,50],face:'left'},
      {name:'사마의',look:'strategist',at:[44,60]},
      {name:'양수',look:'strategist'},
      {name:'사마사',look:'infantry'},
      {name:'사마소',look:'civil'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'226년, 낙양. 조식이 위왕이 된 지 여러 해. 천하는 아직 셋으로 나뉘어 있고, 조정은 재상 사마의의 손 안에 있다.'},
      {say:'조식',line:'중달, 짐은 오늘도 시를 지었소. 정사는 그대가 짓고 있으니, 위나라에 시인이 둘인 셈이구려.'},
      {say:'조식',line:'안향의 형님이 또 시를 보내왔소. 형제가 글로만 만나니, 이것도 나쁘지 않소.',when:'zhi_spare_pi'},
      {enter:'전령',at:[88,64],from:'right'},
      {say:'전령',line:'강동의 손권이 합비 앞에 배를 띄우고, 육손이 장강의 물길을 모두 쥐었다 합니다!'},
      {exit:'전령',to:'right'},
      {enter:'양수',at:[60,62],from:'right'},
      {say:'양수',line:'재상, 지금 강동을 치면 천하가 하나가 됩니다. 시인의 왕 아래 천하통일이라, 이보다 좋은 시가 있겠습니까.'},
      {enter:'사마사',at:[24,64],from:'left'},
      {enter:'사마소',at:[14,68],from:'left'},
      {say:'사마사',line:'아버님, 조정의 종친들이 수군댑니다. 천하는 이미 사마씨를 보고 있다고. 그렇다면 굳이 남의 자리에서 일하실 까닭이 있습니까.'},
      {emote:'사마소',text:'땀'},
      {say:'사마소',line:'형님 말씀이 지나치나… 틀린 말은 아닙니다. 왕께서도 옥좌를 무거워하십니다.'},
      {emote:'사마의',text:'…'},
      {choice:'사마의',options:[
        {id:'zhi_unify',text:'왕의 재상으로 남아 강동을 친다.',reply:'왕은 시를 짓고, 나는 천하를 하나로 묶는다. 그것으로 족하다.',answer:{speaker:'조식',line:'그대가 천하를 묶으면, 짐은 그 천하를 노래하겠소.'},note:'가상 · 시인의 천하 · 강동 수향 · 우두머리 육손'},
        {id:'zhi_throne',text:'왕에게서 선양을 받는다.',reply:'왕께서 무거워하시는 것을 신이 대신 지겠습니다.',answer:{speaker:'사마사',line:'아버님, 종친의 칼은 저희 형제가 막겠습니다.'},note:'가상 · 선양의 날 · 낙양 궁정 · 우두머리 조식'},
      ]},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 하편 가상 · 시인의 천하 (zhi_unify) — 적: 주연·손권(또는 정봉)·육손
// ════════════════════════════════════════════════════════════════
{id:'IF3-zu-1',year:'227년 · 합비',title:'합비의 문',
  synopsis:'조식의 재상 사마의가 강동을 치러 합비를 넘는다. 장강 가의 요새는 오의 주연이 지킨다. 첫 관문을 넘어야 강이 보인다.',
  scenes:[
    {place:'낙양 · 궁문',art:2,cast:[
      {name:'조식',look:'civil',at:[62,54],face:'left'},
      {name:'사마의',look:'strategist',at:[42,60]},
      {name:'양수',look:'strategist',at:[28,64]}],
    steps:[
      {narrate:'재상 사마의는 왕의 이름으로 남정(南征)의 군을 일으켰다.'},
      {move:'조식',to:[54,56]},
      {say:'조식',line:'중달, 건업에 닿거든 강물 소리를 적어 보내시오. 짐은 그것으로 부(賦)를 짓겠소.'},
      {say:'사마의',line:'강물 소리보다 손권의 항복 표문을 먼저 보내 드리지요.'},
      {emote:'양수',text:'♪'},
      {exit:'조식',to:'right'},
    ]},
    {place:'합비 신성 · 군막',art:14,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'만총',look:'infantry',at:[60,58],face:'left'},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'등애',look:'spear'},
      {name:'전령',look:'infantry'}],
    steps:[
      {say:'만총',line:'합비는 열 번을 막았소. 이번에는 우리가 강을 건널 차례라니, 늙은 몸이 다 떨리는구려.'},
      {enter:'등애',at:[76,64],from:'right'},
      {emote:'등애',text:'땀'},
      {say:'등애',line:'애, 애, 애가… 둔전관 등애가 회수 물길 지도를 그, 그려 왔습니다.'},
      {say:'사마의',line:'천천히 말하게. 말은 더듬어도 지도는 더듬지 않았구먼. 이 물길, 누가 알려 주었나.'},
      {enter:'전령',at:[88,60],from:'right'},
      {say:'전령',line:'주연이 강가 요새의 문을 닫고 화살을 쟁였습니다!'},
      {choice:'사마의',options:[
        {id:'man_chong',text:'만총의 합비 수비군을 선봉에 세운다.',reply:'합비를 아는 사람이 합비의 문을 연다.',answer:{speaker:'만총',line:'열한 번째 싸움은 내가 칼끝에 서겠소.'},note:'만총 영입(보병) · 첫 턴 방어 태세',
          effects:[{kind:'recruit',name:'만총',unitClass:'infantry'},{kind:'guard'},{kind:'flag',flag:'zu_manchong'}]},
        {id:'deng_ai',text:'등애의 지도대로 물길 뒤로 돈다.',reply:'이 젊은이의 눈은 땅속까지 본다.',answer:{speaker:'등애',line:'바, 반드시 길을 열겠습니다!'},note:'등애 영입(창병) · 척후로 적 한 부대가 나오지 않는다',
          effects:[{kind:'recruit',name:'등애',unitClass:'spearman'},{kind:'scout'},{kind:'flag',flag:'zu_dengai'}]},
        {id:'dongxing',text:'요새를 넘거든 곧장 동흥 제방으로 간다.',reply:'건업 앞바다보다 동흥의 둑이 먼저다. 둑을 쥐면 강이 우리 편이 된다.',note:'다음 전장이 「동흥 설전」으로 바뀐다 · 책략 MP +15',
          effects:[{kind:'path',tale:'IF3-zu-2x'},{kind:'insight'}]},
      ]},
      {exit:'전령',to:'right'},
    ]},
  ],
  after:[
    {place:'합비 남쪽 · 강가 요새',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'만총',look:'infantry'},
      {name:'등애',look:'spear'}],
    steps:[
      {narrate:'주연은 요새를 버리고 강을 건너 물러났다. 장강의 물빛이 처음으로 위군의 눈앞에 펼쳐졌다.'},
      {enter:'만총',at:[60,58],from:'right',when:'zu_manchong'},
      {say:'만총',line:'평생 이 강을 등지고 싸웠는데, 오늘은 마주 보고 섰구려.',when:'zu_manchong'},
      {enter:'등애',at:[60,62],from:'right',when:'zu_dengai'},
      {say:'등애',line:'강가 둔전에 보리를 심으면 오 년 치 군량이 나옵니다. 처, 천천히 이기시면 됩니다.',when:'zu_dengai'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'요새 하나에 주연을 보냈으니, 다음은 손권이 몸소 나올 차례다.'},
    ]},
  ]},

{id:'IF3-zu-2',year:'228년 · 건업 앞바다',title:'건업 앞바다',
  synopsis:'건업 앞바다에 손권이 몸소 함대를 이끌고 나왔다. 강동의 주인과 마주할 때다. 물 위의 싸움에 익숙하지 않은 북군이 바다 같은 강을 건너야 한다.',
  scenes:[
    {place:'장강 · 북쪽 강둑',art:7,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'양수',look:'strategist',at:[22,64]},
      {name:'곽회',look:'archer',at:[54,66],face:'left'},
      {name:'문빙',look:'infantry'},
      {name:'위군 병사',look:'spear',at:[70,70],face:'left'}],
    steps:[
      {narrate:'강 건너 건업 앞바다에 붉은 돛이 숲처럼 섰다. 벽안자염의 손권이 몸소 누선 위에 올랐다.'},
      {emote:'위군 병사',text:'땀'},
      {move:'위군 병사',to:[78,72]},
      {say:'곽회',line:'병사들이 배에 오르기도 전에 멀미를 합니다. 북쪽 사람은 물을 두려워하지요.'},
      {say:'양수',line:'선왕께서 적벽에서 잃은 것이 바로 그 두려움이었습니다.'},
      {enter:'문빙',at:[86,62],from:'right'},
      {say:'문빙',line:'강하의 문빙이오. 물길이라면 이 늙은이가 조금 압니다. 재상의 명을 기다리오.'},
      {choice:'사마의',options:[
        {id:'wen_pin',text:'문빙의 강하 수군을 앞세운다.',reply:'물은 물을 아는 자에게 맡긴다.',answer:{speaker:'문빙',line:'적벽의 빚을 오늘 갚겠소.'},note:'문빙의 수군이 초록 깃발로 돕는다',
          effects:[{kind:'reinforce',name:'문빙',unitClass:'navy',side:'npc'}]},
        {id:'fire',text:'동남풍을 기다려 불배를 띄운다.',reply:'주유가 우리에게 가르쳐 준 것을 돌려줄 때다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'},{kind:'flag',flag:'zu_fire'}]},
        {id:'king',text:'왕의 친서를 손권에게 먼저 보낸다.',reply:'시인의 왕이 쓴 글이다. 칼보다 먼저 닿게 하라.',note:'첫 턴 방어 태세 · 왕의 친서가 강동에 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'zu_king_letter'}]},
      ]},
      {exit:'문빙',to:'right'},
    ]},
  ],
  after:[
    {place:'장강 · 남쪽 강둑',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'양수',look:'strategist',at:[24,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'손권의 누선이 물러났다. 북군이 처음으로 장강 남쪽 땅을 밟았다.'},
      {narrate:'강물이 사흘 동안 붉게 탔다. 강동 사람들은 그 불을 오래 기억했다.',when:'zu_fire'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'손권이 건업으로 들어가고, 군권을 육손에게 넘겼다 합니다!'},
      {emote:'양수',text:'!'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'이릉에서 칠백 리 진채를 태운 그 서생이로군. 이제야 진짜 강동이 나온다.'},
    ]},
  ]},

{id:'IF3-zu-2x',year:'228년 · 동흥 제방',title:'동흥 설전',
  synopsis:'건업 앞바다 대신 동흥의 둑을 노렸다. 눈 내리는 제방 위에서 오의 노장 정봉이 갑옷을 벗은 단병(短兵)을 이끌고 기다린다. 둑을 쥐면 강이 위의 편이 된다.',
  scenes:[
    {place:'동흥 · 눈 덮인 제방',art:17,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'곽회',look:'archer',at:[22,66]},
      {name:'위군 병사',look:'spear',at:[56,66],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'동흥의 제방 위로 눈이 내렸다. 강물은 얼지 않았지만, 병사들의 손은 얼었다.'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'정봉이 병사들에게 갑옷을 벗기고 짧은 칼만 쥐게 했습니다! 눈 속에서 춤추듯 달려옵니다!'},
      {emote:'위군 병사',text:'땀'},
      {move:'위군 병사',to:[48,68]},
      {say:'곽회',line:'추위에 갑옷을 벗다니, 미친 늙은이입니다. 그러나 미친 자가 가장 빠릅니다.'},
      {say:'사마의',line:'갑옷을 벗은 자는 오래 싸우지 못한다. 우리는 오래 싸우면 된다.'},
      {choice:'사마의',options:[
        {id:'warm',text:'병사들에게 술과 솜옷을 먼저 돌린다.',reply:'언 손으로는 창을 쥘 수 없다.',note:'처음 2턴 사기 상승',effects:[{kind:'rally'}]},
        {id:'dike',text:'제방 한쪽을 무너뜨려 오군의 길을 물로 막는다.',reply:'둑은 강을 막으라고 있는 것이 아니라, 쓰라고 있는 것이다.',note:'책략 MP +15 · 첫 턴 방어 태세',effects:[{kind:'insight'},{kind:'guard'}]},
        {id:'bold',text:'정봉의 단병과 눈 속에서 정면으로 붙는다.',reply:'저 늙은이의 춤에 장단을 맞춰 주자.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {exit:'전령',to:'right'},
    ]},
  ],
  after:[
    {place:'동흥 · 눈 그친 제방',art:17,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'정봉은 눈 속에 칼을 꽂고 물러났다. 동흥의 둑이 위의 손에 들어오자 건업으로 가는 물길이 열렸다.'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'손권이 놀라 건업 성문을 닫고, 군권을 육손에게 넘겼다 합니다!'},
      {emote:'곽회',text:'!'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'둑 하나에 강동의 주인이 성 안으로 숨었구나. 이제 육손이 나온다.'},
    ]},
  ]},

{id:'zhi_unify:boss',year:'229년 · 건업',title:'건업 함락',
  synopsis:'손권은 성 안으로 물러나고, 이릉에서 유비를 불태운 육손이 건업 앞에 섰다. 시인의 왕이 천하를 노래하려면 이 서생을 꺾어야 한다.',
  scenes:[
    {place:'건업 북쪽 · 군영 아침',art:6,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'양수',look:'strategist',at:[24,64]},
      {name:'조식',look:'civil'},
      {name:'친위병',look:'spear'}],
    steps:[
      {narrate:'229년 봄, 위왕 조식이 몸소 강을 건너 군영에 이르렀다.'},
      {enter:'친위병',at:[80,66],from:'right'},
      {enter:'조식',at:[62,58],from:'right'},
      {say:'조식',line:'중달, 강물 소리를 기다리다 못해 짐이 직접 왔소. 건업의 성벽이 저리 높은가.'},
      {emote:'양수',text:'땀'},
      {say:'양수',line:'왕께서 전장에 오시다니요! 화살 하나면 천하가 시인을 잃습니다.'},
      {say:'사마의',line:'왕께서는 군영에 계십시오. 성벽은 신이 낮추겠습니다.'},
    ]},
    {place:'건업 · 성 밖',art:2,cast:[
      {name:'사마의',look:'strategist',at:[34,62]},
      {name:'곽회',look:'archer',at:[20,66]},
      {name:'육손',look:'strategist',at:[66,46],face:'left'},
      {name:'오군 병사',look:'spear',at:[78,50],face:'left'}],
    steps:[
      {say:'육손',line:'사마중달. 이릉에서 유비는 칠백 리 진채를 이었다가 불탔소. 그대는 몇 리를 잇겠소?'},
      {move:'사마의',to:[44,60]},
      {say:'사마의',line:'한 리도 잇지 않소, 백언(육손). 그대의 불은 이어진 것만 태우지 않소?'},
      {emote:'육손',text:'…'},
      {move:'오군 병사',to:[72,48]},
      {choice:'사마의',options:[
        {id:'yiling',text:'진채를 잇지 않고 물가에서 떨어뜨려 친다.',reply:'이릉의 불은 남의 일로 배운다.',note:'첫 턴 방어 태세 · 이릉의 교훈이 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'zu_yiling'}]},
        {id:'letter',text:'육손에게 항복 뒤의 대우를 약조하는 글을 보낸다.',reply:'이 서생은 죽이기 아까운 사람이다.',answer:{speaker:'육손',line:'…싸움이 끝나면 다시 읽어 보겠소.'},note:'책략 MP +15 · 육손에게 보낸 약조가 남는다',effects:[{kind:'insight'},{kind:'flag',flag:'zu_luxun_letter'}]},
        {id:'bold',text:'성문을 향해 전군을 몰아친다.',reply:'왕께서 보고 계신다. 오늘 끝낸다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {exit:'육손',to:'right'},
    ]},
  ],
  after:[
    {place:'건업 · 무너진 성문',art:1,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'조식',look:'civil'},
      {name:'육손',look:'strategist'}],
    steps:[
      {narrate:'건업의 성문이 무너졌다. 손권은 옥새를 받들고 성 밖으로 나왔다.'},
      {enter:'육손',at:[64,60],from:'right',when:'zu_luxun_letter'},
      {say:'육손',line:'약조를 읽었소. 강동 백성을 해치지 않는다면, 이 몸은 그대의 붓이 되겠소.',when:'zu_luxun_letter'},
      {enter:'조식',at:[22,58],from:'left'},
      {say:'조식',line:'중달, 들리오? 이것이 천하가 하나 되는 소리구려.'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'ending:zhi_unify',year:'230년 · 낙양',title:'시인의 천하',
  synopsis:'조식의 재상 사마의가 건업을 함락시켰다. 시를 짓던 왕 아래 천하가 하나 되었다.',
  scenes:[
    {place:'낙양 · 위왕의 궁정',art:5,cast:[
      {name:'조식',look:'civil',at:[66,50],face:'left'},
      {name:'사마의',look:'strategist'},
      {name:'양수',look:'strategist',at:[80,58],face:'left'},
      {name:'사마사',look:'infantry'},
      {name:'육손',look:'strategist'}],
    steps:[
      {narrate:'조식의 재상 사마의가 건업을 함락시켰다. 시를 짓던 왕 아래 천하가 하나 되었다.'},
      {enter:'사마의',at:[42,60],from:'left'},
      {enter:'사마사',at:[28,64],from:'left'},
      {say:'조식',line:'중달, 짐이 지은 시 가운데 가장 긴 것을 그대가 대신 썼구려. 천하라는 시를.'},
      {say:'사마의',line:'신은 먹을 갈았을 뿐입니다. 붓은 언제나 왕의 것이었습니다.'},
      {enter:'육손',at:[54,64],from:'right',when:'zu_luxun_letter'},
      {say:'육손',line:'강동의 백성은 무사합니다. 약조를 지킨 재상께, 이 서생이 머리를 숙입니다.',when:'zu_luxun_letter'},
      {say:'조식',line:'안향의 형님이 축하하는 시를 보내왔소. 콩과 콩대가 이제 한 솥에서 웃는다 하오.',when:'zhi_spare_pi'},
      {emote:'양수',text:'♪'},
      {say:'양수',line:'천하가 하나 되었는데 재상께서는 웃지 않으십니까.'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'웃음은 왕의 몫이오. 나는 이 천하가 다시 갈라지지 않을 방법을 생각하고 있소.'},
      {narrate:'칠보시의 공자는 성군으로, 그 곁의 재상은 천하를 다스린 손으로 기억되었다.'},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 하편 가상 · 선양의 날 (zhi_throne) — 적: 조휴·조진(또는 하후패)·조식
// ════════════════════════════════════════════════════════════════
{id:'IF3-zt-1',year:'227년 · 낙양',title:'종친의 반발',
  synopsis:'선양의 소문이 돌자 조씨 종친 조휴가 군을 일으켰다. 사마의의 아우 사마부마저 신하의 도리를 들어 반대한다. 낙양으로 오는 길목을 끊어야 한다.',
  scenes:[
    {place:'낙양 · 사마씨 저택',art:0,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'사마부',look:'civil',at:[60,56],face:'left'},
      {name:'사마사',look:'infantry'},
      {name:'사마소',look:'civil'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'왕이 옥좌를 넘기려 한다는 소문이 낙양에 돌았다. 사마씨 저택의 뜰에도 밤늦게 등불이 켜졌다.'},
      {say:'사마부',line:'형님, 선양이라니요. 우리 집안은 대대로 신하로 살았습니다. 숙달(사마부)은 이 일에 따를 수 없습니다.'},
      {say:'사마의',line:'숙달, 왕께서 먼저 말씀하셨네. 옥좌가 무겁다고, 시만 짓고 싶다고.'},
      {emote:'사마부',text:'…'},
      {enter:'사마사',at:[22,62],from:'left'},
      {enter:'사마소',at:[12,66],from:'left'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'급보! 조휴가 동쪽 종친의 군을 모아 낙양으로 옵니다! 사마씨를 치겠다 격문을 돌렸습니다!'},
      {say:'사마사',line:'아버님, 종친의 칼은 저희 형제가 막겠다 말씀드렸습니다. 명만 내리십시오.'},
      {choice:'사마의',options:[
        {id:'jia_chong',text:'가충을 불러 조휴의 군량길을 끊게 한다.',reply:'꾀 많은 자는 위험하나, 오늘은 그 꾀가 필요하다.',answer:{speaker:'사마소',line:'가충이라면 제가 데려오겠습니다. 저를 따르는 사람입니다.'},note:'가충 영입(책사) · 책략 MP +15',
          effects:[{kind:'recruit',name:'가충',unitClass:'strategist'},{kind:'insight'},{kind:'flag',flag:'zt_jiachong'}]},
        {id:'shi_bao',text:'석포의 기병으로 조휴의 정면을 막는다.',reply:'대장장이 출신이라 하나, 그 손은 쇠를 다룰 줄 안다.',answer:{speaker:'사마사',line:'석포는 제 사람입니다. 앞장서게 하지요.'},note:'석포 영입(기병) · 처음 2턴 사기 상승',
          effects:[{kind:'recruit',name:'석포',unitClass:'cavalry'},{kind:'rally'}]},
        {id:'zhen',text:'조진에게 먼저 사람을 보내 금군을 묶어 둔다.',reply:'자단(조진)은 곧은 사람이다. 곧은 사람에게는 곧게 부탁하면 된다.',note:'다음 전장이 「옹주의 격문」으로 바뀐다 · 조진과의 옛 정이 남는다',
          effects:[{kind:'path',tale:'IF3-zt-2x'},{kind:'flag',flag:'zt_zhen_friend'}]},
      ]},
      {exit:'전령',to:'right'},
    ]},
  ],
  after:[
    {place:'낙양 동쪽 · 길목',art:11,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마사',look:'infantry',at:[24,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'조휴의 군은 낙양 동쪽 길목에서 무너졌다. 조휴는 분을 이기지 못해 등창이 터져 쓰러졌다.'},
      {say:'사마사',line:'가충이 군량 수레를 모두 태웠습니다. 조휴의 병사들은 사흘을 굶었다 합니다.',when:'zt_jiachong'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'조진이 금군을 이끌고 궁문을 닫았습니다! 아무도 들이지 말라는 명입니다!',unless:'zt_zhen_friend'},
      {say:'전령',line:'조진은 금군을 움직이지 않겠다 답했습니다. 그런데 서쪽 옹주에서 하후패가 격문을 돌립니다!',when:'zt_zhen_friend'},
      {move:'사마사',to:[30,62]},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'IF3-zt-2',year:'227년 · 낙양 궁문',title:'금군의 칼끝',
  synopsis:'금군을 쥔 조진이 궁문을 닫았다. 허창에서 칼을 내려놓았던 벗이 이번에는 칼을 뽑았다. 한때의 벗이 마지막 벽이다.',
  scenes:[
    {place:'낙양 · 궁문 앞',art:2,cast:[
      {name:'사마의',look:'strategist',at:[34,64]},
      {name:'사마사',look:'infantry',at:[20,66]},
      {name:'곽회',look:'archer'},
      {name:'조진',look:'heavy',at:[62,44],face:'left'},
      {name:'금군 병사',look:'spear',at:[76,46],face:'left'}],
    steps:[
      {narrate:'낙양 궁문이 굳게 닫혔다. 성루 위에 조진이 섰다.'},
      {say:'조진',line:'중달, 허창에서 자네는 내 칼을 칼집에 넣어 두라 했지. 쓸 날이 온다고. 오늘이 그날이네.'},
      {move:'사마의',to:[44,60]},
      {say:'사마의',line:'자단, 왕께서 스스로 내려놓으시려는 자리일세. 자네가 지키려는 것은 왕인가, 자리인가.'},
      {emote:'조진',text:'분노'},
      {enter:'곽회',at:[10,68],from:'left'},
      {move:'금군 병사',to:[70,48]},
      {choice:'사마의',options:[
        {id:'old_friend',text:'조진만은 살려서 사로잡으라 명한다.',reply:'벗을 베고 얻는 옥좌라면 차라리 받지 않겠다.',answer:{speaker:'사마사',line:'아버님 뜻대로 하겠습니다. 다만 조진의 칼은 사정을 봐주지 않을 겁니다.'},note:'첫 턴 방어 태세 · 조진의 목숨이 남는다',
          effects:[{kind:'guard'},{kind:'flag',flag:'zt_zhen_spared'}]},
        {id:'night',text:'밤을 틈타 궁의 북문으로 들어간다.',reply:'정문은 자단에게 맡기고, 우리는 뒷문으로 간다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
        {id:'bold',text:'궁문을 정면으로 부순다.',reply:'벗에게는 숨기지 않는다. 정면으로 간다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {exit:'조진',to:'right'},
    ]},
  ],
  after:[
    {place:'낙양 · 열린 궁문',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,62]},
      {name:'조진',look:'heavy',at:[62,60],face:'left'},
      {name:'금군 병사',look:'spear',at:[78,64],face:'left'}],
    steps:[
      {narrate:'궁문이 열렸다. 금군은 창을 거꾸로 들었다.'},
      {say:'조진',line:'또 살려 두는가, 중달. 자네는 나를 두 번 이겼고, 두 번 살렸네. …세 번째는 없겠지.',when:'zt_zhen_spared'},
      {narrate:'조진은 궁문 앞에서 끝까지 싸우다 쓰러졌다. 사마의는 오래 그 자리에 서 있었다.',unless:'zt_zhen_spared'},
      {exit:'금군 병사',to:'right'},
      {emote:'사마의',text:'…'},
      {exit:'조진',to:'right'},
    ]},
  ]},

{id:'IF3-zt-2x',year:'227년 · 낙양 서쪽',title:'옹주의 격문',
  synopsis:'조진은 옛 벗과의 정으로 금군을 움직이지 않았다. 대신 하후연의 아들 하후패가 옹주에서 격문을 돌리고 기병을 몰아 낙양으로 내려온다.',
  scenes:[
    {place:'낙양 서쪽 · 숲길',art:11,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'곽회',look:'archer',at:[54,64],face:'left'},
      {name:'사마소',look:'civil',at:[22,66]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'조진은 사마의의 서신에 한 줄로 답했다. "금군은 궁을 지킬 뿐, 누구도 치지 않는다."'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'하후패가 옹주 기병을 이끌고 함곡관을 넘었습니다! 격문에 찬탈자 사마의를 베겠다 적었습니다!'},
      {emote:'사마소',text:'땀'},
      {say:'곽회',line:'옹주의 장수들은 제가 오래 다룬 사람들입니다. 하후패를 따르는 자들도 속으로는 흔들리고 있을 겁니다.'},
      {move:'사마의',to:[44,60]},
      {say:'사마의',line:'아비 하후연은 정군산에서 성급히 나섰다가 쓰러졌다. 아들도 그 피를 이었구나.'},
      {exit:'전령',to:'right'},
      {choice:'사마의',options:[
        {id:'guo',text:'곽회에게 옹주의 장수들을 달래 데려오게 한다.',reply:'적의 반을 우리 편으로 만드는 것이 가장 싼 승리다.',answer:{speaker:'곽회',line:'옹주 기병 한 부대는 데려오지요.'},note:'옹주 기병이 직접 지휘하는 아군으로 합류',
          effects:[{kind:'reinforce',name:'옹주 기병',unitClass:'cavalry',side:'ally'}]},
        {id:'scout',text:'함곡관 뒤 보급대를 먼저 끊는다.',reply:'급히 달려온 자는 뒤를 돌아보지 않는다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
        {id:'bold',text:'숲길에서 하후패와 정면으로 맞선다.',reply:'젊은 범의 이빨을 한 번은 받아 주자.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
    ]},
  ],
  after:[
    {place:'낙양 서쪽 · 숲길 끝',art:11,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마소',look:'civil',at:[24,64]},
      {name:'하후패',look:'cavalry',at:[66,58],face:'left'}],
    steps:[
      {narrate:'하후패의 기병이 흩어졌다. 그는 말머리를 돌리며 외쳤다.'},
      {say:'하후패',line:'사마의! 위에 내 자리가 없다면 촉으로 가겠다! 언젠가 그 깃발 아래 돌아오리라!'},
      {exit:'하후패',to:'right'},
      {emote:'사마소',text:'?'},
      {move:'사마의',to:[48,58]},
      {say:'사마의',line:'가게 두어라. 이제 남은 것은 왕께서 옥좌를 내려놓으시는 일뿐이다.'},
    ]},
  ]},

{id:'zhi_throne:boss',year:'228년 · 낙양 궁정',title:'시인 왕의 마지막 칼',
  synopsis:'종친의 칼은 모두 꺾였다. 그러나 조식 곁에 남은 장수들은 마지막까지 왕을 지키겠다며 궁정에 진을 쳤다. 조식도 한 번은 왕으로서 칼을 들고 싶다고 말한다.',
  scenes:[
    {place:'낙양 · 사마씨 서재',art:12,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'사마부',look:'civil',at:[58,58],face:'left'},
      {name:'사마사',look:'infantry'}],
    steps:[
      {narrate:'선양의 날을 사흘 앞두고, 궁정의 장수들이 왕을 둘러싸고 문을 닫았다.'},
      {emote:'사마부',text:'…'},
      {say:'사마부',line:'형님, 왕께서도 한 번은 칼을 들고 싶으신 게지요. 시인도 사내입니다.'},
      {enter:'사마사',at:[22,62],from:'left'},
      {say:'사마사',line:'궁정 회랑에 호위 장수들이 진을 쳤습니다. 왕께서 몸소 그 가운데 계십니다.'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'왕께서 바라시는 것은 이기는 싸움이 아니다. 지고도 부끄럽지 않은 싸움이다. 그것을 드리자.'},
    ]},
    {place:'낙양 · 궁정 회랑',art:13,cast:[
      {name:'사마의',look:'strategist',at:[30,62]},
      {name:'사마소',look:'civil',at:[16,66]},
      {name:'조식',look:'civil',at:[72,52],face:'left'},
      {name:'궁 호위병',look:'heavy',at:[84,58],face:'left'}],
    steps:[
      {move:'조식',to:[64,54]},
      {say:'조식',line:'중달, 짐은 평생 시만 지었소. 마지막으로 한 번은 왕답게 서 보고 싶소. 막아 보시오.'},
      {emote:'사마소',text:'!'},
      {move:'사마의',to:[40,60]},
      {say:'사마의',line:'왕께서 서신 자리가 곧 왕의 자리입니다. 신이 그 앞까지 걸어가겠습니다.'},
      {choice:'사마의',options:[
        {id:'no_blood',text:'궁 안에서는 아무도 죽이지 말라 명한다.',reply:'선양의 날에 피가 묻으면 그것은 찬탈이다.',note:'첫 턴 방어 태세 · 피 없는 선양이 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'zt_no_blood'}]},
        {id:'sons',text:'사마사와 사마소에게 양 날개를 맡긴다.',reply:'이 나라를 이어받을 것은 너희다. 오늘 그 무게를 느껴 보아라.',answer:{speaker:'사마소',line:'형님은 왼쪽을, 저는 오른쪽을 맡겠습니다.'},note:'처음 2턴 사기 상승 · 두 아들이 앞장선 일이 남는다',effects:[{kind:'rally'},{kind:'flag',flag:'zt_sons'}]},
        {id:'swift',text:'날이 밝기 전에 회랑을 휩쓴다.',reply:'왕께서 오래 서 계시지 않도록, 빨리 끝낸다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
      ]},
      {emote:'조식',text:'…'},
      {exit:'궁 호위병',to:'right'},
    ]},
  ],
  after:[
    {place:'낙양 · 궁정 회랑',art:13,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'조식',look:'civil',at:[62,56],face:'left'}],
    steps:[
      {narrate:'호위 장수들이 하나둘 창을 내려놓았다. 조식은 칼을 거두고 웃었다.'},
      {say:'조식',line:'아무도 죽지 않았구려. 고맙소, 중달. 그대는 끝까지 짐의 재상이었소.',when:'zt_no_blood'},
      {say:'조식',line:'졌구려. 그런데 이상하게 마음이 가볍소. 이제야 시만 지을 수 있겠소.',unless:'zt_no_blood'},
      {move:'조식',to:[52,58]},
      {emote:'사마의',text:'…'},
      {emote:'조식',text:'♪'},
      {say:'사마의',line:'사흘 뒤, 수선대에서 뵙겠습니다.'},
    ]},
  ]},

{id:'ending:zhi_throne',year:'228년 · 낙양 수선대',title:'선양의 날',
  synopsis:'조식은 웃으며 옥새를 내려놓았다. 사마씨의 나라가 열렸다.',
  scenes:[
    {place:'낙양 · 수선대',art:5,cast:[
      {name:'조식',look:'civil',at:[64,50],face:'left'},
      {name:'사마의',look:'strategist'},
      {name:'사마사',look:'infantry',at:[18,64]},
      {name:'사마소',look:'civil',at:[28,68]},
      {name:'사마부',look:'civil'}],
    steps:[
      {narrate:'수선대 위로 봄바람이 불었다. 시인 왕이 옥새를 두 손으로 받쳐 들었다.'},
      {enter:'사마의',at:[44,58],from:'left'},
      {move:'조식',to:[56,54]},
      {say:'조식',line:'그대가 더 잘 다스릴 것이오. 짐은 이제 바람이나 노래하겠소.'},
      {say:'사마의',line:'왕께서 남기신 시는 이 나라가 망하는 날까지 읽힐 것입니다.'},
      {emote:'사마사',text:'!'},
      {say:'사마사',line:'궁 안에 피 한 방울 없이 이 날을 맞았습니다. 백성들이 선양이라 부르지 찬탈이라 부르지 않습니다.',when:'zt_no_blood'},
      {say:'사마소',line:'아버님, 조진 장군이 멀리서 이 날을 지켜보았다 합니다. 끝내 고개는 숙이지 않았지만요.',when:'zt_zhen_spared'},
      {enter:'사마부',at:[84,62],from:'right'},
      {emote:'사마부',text:'…'},
      {say:'사마부',line:'저는 끝까지 위의 신하로 남겠습니다, 형님. 그것이 이 날을 덜 부끄럽게 하는 길이겠지요.'},
      {narrate:'역사보다 한 세대 이른 진(晉) — 시인 왕의 양보로 시작된 왕조였다.'},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 중편 가상 · 촉의 사마의 (shu) — 적: 서황·우금·장합(또는 맹달)·조인
// ════════════════════════════════════════════════════════════════
{id:'IF2-shu-1',year:'220년 · 한중 → 양양',title:'양양 공략',
  synopsis:'조조 없는 위를 버리고 한중왕 유비에게 몸을 맡겼다. 법정은 위의 이리를 믿지 않고, 제갈량은 부채를 거두며 북쪽의 문 양양을 가리킨다. 위의 명장 서황이 양양을 지킨다.',
  scenes:[
    {place:'한중 · 한중왕의 궁',art:5,cast:[
      {name:'유비',look:'infantry',at:[66,52],face:'left'},
      {name:'제갈량',look:'strategist',at:[80,58],face:'left'},
      {name:'법정',look:'civil',at:[56,60],face:'left'},
      {name:'사마의',look:'strategist'},
      {name:'사마랑',look:'physician'}],
    steps:[
      {narrate:'조조가 숨을 거둔 그달, 하내의 사마씨 형제가 한중으로 들어왔다. 위를 버린 자들을 한중왕이 맞았다.'},
      {enter:'사마의',at:[34,60],from:'left'},
      {enter:'사마랑',at:[20,66],from:'left'},
      {say:'유비',line:'조조가 그토록 부르려 애쓰던 사마중달이 내 문을 두드리다니. 하늘이 아직 한실을 버리지 않았구려.'},
      {emote:'법정',text:'분노'},
      {move:'법정',to:[48,60]},
      {say:'법정',line:'대왕, 이자는 조조 앞에서도 병을 핑계로 일곱 해를 버틴 사람입니다. 위의 이리를 우리 안에 들이시렵니까.'},
      {say:'사마의',line:'이리는 배고플 때 문을 두드리지 않소, 효직(법정). 나는 갈 곳을 골라서 왔을 뿐이오.'},
      {move:'제갈량',to:[70,58]},
      {say:'제갈량',line:'다투실 것 없습니다. 중달, 북쪽의 문은 양양이오. 그 문을 열어 보이면 효직도 입을 닫겠지요.'},
    ]},
    {place:'양양 · 성벽 아래',art:8,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'사마랑',look:'physician',at:[20,66]},
      {name:'위연',look:'infantry'},
      {name:'촉군 병사',look:'spear',at:[54,68],face:'left'}],
    steps:[
      {narrate:'양양 성벽 위에 서황의 큰 도끼가 번뜩였다. 성은 높고, 서황은 서두르지 않는 장수였다.'},
      {enter:'위연',at:[62,60],from:'right'},
      {say:'위연',line:'책사 양반, 내게 선봉을 주시오. 성벽은 높아도 서황의 목은 하나요.'},
      {emote:'촉군 병사',text:'!'},
      {choice:'사마의',options:[
        {id:'wei_yan',text:'위연에게 선봉을 맡긴다.',reply:'반골이라 하나, 그 뼈가 앞을 향해 있으면 쓸 만하다.',answer:{speaker:'위연',line:'하하! 위에서 온 책사가 사람 볼 줄은 아는구려!'},note:'위연 영입(보병) · 정면 승부로 적 정예 1부대 추가, 경험치 1.5배',
          effects:[{kind:'recruit',name:'위연',unitClass:'infantry'},{kind:'bold'},{kind:'flag',flag:'shu_weiyan'}]},
        {id:'guan',text:'형주의 관우와 날짜를 맞춰 남북에서 친다.',reply:'운장의 칼이 남쪽에서 오면, 서황은 등 뒤를 걱정해야 한다.',note:'관우가 초록 깃발로 돕는다 · 관우와의 인연이 남는다',
          effects:[{kind:'reinforce',name:'관우',unitClass:'cavalry',side:'npc'},{kind:'flag',flag:'shu_guanyu'}]},
        {id:'night',text:'서황에게 거짓 항복 서신을 보낸다.',reply:'위에서 도망친 자가 다시 위로 가겠다 하면, 서황도 한 번은 믿고 싶을 것이다.',note:'기습 · 적 전원 체력 80%로 시작 · 법정의 의심이 남는다',
          effects:[{kind:'ambush'},{kind:'flag',flag:'shu_false_letter'}]},
      ]},
      {move:'촉군 병사',to:[70,66]},
    ]},
  ],
  after:[
    {place:'양양 · 열린 성문',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'법정',look:'civil'},
      {name:'위연',look:'infantry'}],
    steps:[
      {narrate:'서황은 양양을 버리고 북쪽 번성으로 물러났다.'},
      {enter:'위연',at:[58,62],from:'right',when:'shu_weiyan'},
      {say:'위연',line:'봤소? 서황의 도끼가 내 칼에 밀렸소! 책사, 다음에도 내가 선봉이오!',when:'shu_weiyan'},
      {enter:'법정',at:[70,58],from:'right'},
      {say:'법정',line:'거짓 항복이라… 그 솜씨가 언젠가 우리에게 향하지 않기를 바라오.',when:'shu_false_letter'},
      {say:'법정',line:'양양을 열었구려. 이리라 부른 말은 거두겠소. 범이라 부르리다.',unless:'shu_false_letter'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'IF2-shu-2',year:'220년 · 번성',title:'번성 포위',
  synopsis:'가을비에 한수가 불어 번성이 물에 잠겼다. 성을 구하러 온 우금의 칠군이 물가에 갇혔다. 관우와 함께 칠군을 꺾을 때다.',
  scenes:[
    {place:'한수 · 불어난 강둑',art:15,cast:[
      {name:'사마의',look:'strategist',at:[34,62]},
      {name:'관우',look:'cavalry',at:[60,56],face:'left'},
      {name:'관평',look:'cavalry'},
      {name:'촉군 병사',look:'spear',at:[76,68],face:'left'}],
    steps:[
      {narrate:'열흘 동안 비가 그치지 않았다. 한수가 둑을 넘어 번성 아래 들판을 삼켰다.'},
      {say:'관우',line:'그대가 위에서 왔다는 책사인가. 물은 내가 끌어왔소. 그대는 무엇을 끌어왔소?'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'운장(관우)의 등 뒤를 지킬 눈을 끌어왔습니다. 강동의 여몽이 장군의 강릉을 보고 있습니다.'},
      {emote:'관우',text:'분노'},
      {enter:'관평',at:[48,66],from:'right'},
      {say:'관평',line:'아버님, 이 사람 말이 맞습니다. 육구의 여몽이 병을 핑계로 물러났다는데, 수상합니다.'},
      {move:'촉군 병사',to:[84,66]},
      {choice:'사마의',options:[
        {id:'guan_ping',text:'관평과 함께 상류의 둑을 터뜨린다.',reply:'물을 끌어온 것이 장군이라면, 물을 쏟는 것은 아드님이 하시오.',answer:{speaker:'관평',line:'제가 앞장서겠습니다, 군사!'},note:'관평 영입(기병) · 처음 2턴 사기 상승',
          effects:[{kind:'recruit',name:'관평',unitClass:'cavalry'},{kind:'rally'},{kind:'flag',flag:'shu_guanping'}]},
        {id:'mercy',text:'칠군의 항졸은 모두 살려 준다고 외친다.',reply:'물에 빠진 자에게 손을 내밀면 칼을 쥐지 않는다.',answer:{speaker:'관우',line:'흥, 책사답구려. 좋소, 그리 외치게 하시오.'},note:'첫 턴 방어 태세 · 항졸을 살린 일이 남는다',
          effects:[{kind:'guard'},{kind:'flag',flag:'shu_mercy'}]},
        {id:'xincheng',text:'물가는 관우에게 맡기고 상용의 맹달을 먼저 친다.',reply:'맹달은 촉을 버리고 위로 갔다. 등 뒤의 칼부터 치운다.',note:'다음 전장이 「신성의 맹달」로 바뀐다 · 책략 MP +15',
          effects:[{kind:'path',tale:'IF2-shu-3x'},{kind:'insight'}]},
      ]},
    ]},
  ],
  after:[
    {place:'번성 · 물에 잠긴 들판',art:7,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'관우',look:'cavalry',at:[62,56],face:'left'},
      {name:'우금',look:'spear'}],
    steps:[
      {narrate:'칠군이 물에 잠겼다. 우금은 언덕 위에서 투구를 벗었다.'},
      {enter:'우금',at:[80,62],from:'right'},
      {say:'우금',line:'삼십 년을 위에서 싸웠는데… 물에 지고 말았구나.'},
      {say:'관우',line:'항졸 삼만을 살렸소. 책사의 말이 옳았는지 그른지는 형주 백성이 알 것이오.',when:'shu_mercy'},
      {emote:'관우',text:'…'},
      {say:'관우',line:'사마중달. 그대가 말한 강릉의 일, 잊지 않겠소. 강릉에 봉화를 더 세우리다.'},
      {exit:'우금',to:'right'},
    ]},
  ]},

{id:'IF2-shu-3',year:'220년 · 완성',title:'완성 진격',
  synopsis:'번성을 지나면 완성, 완성을 지나면 허창이다. 가정에서 마속을 꺾었어야 할 장합이 이번에는 촉의 길을 막는다. 위의 군략을 아는 자와 위의 명장이 마주 선다.',
  scenes:[
    {place:'완성 남쪽 · 군막',art:14,cast:[
      {name:'제갈량',look:'strategist',at:[62,56],face:'left'},
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'마속',look:'strategist'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'제갈량이 몸소 완성 남쪽까지 올라왔다. 와룡과 총(冢)이 처음으로 한 군막에 앉았다.'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'완성 앞 산길에 장합이 진을 쳤습니다! 물길 옆 높은 언덕을 모두 쥐었습니다!'},
      {exit:'전령',to:'right'},
      {say:'제갈량',line:'장합은 교변(巧變)의 명장이오. 중달, 그대는 그를 위에서 보았지. 어찌 보오?'},
      {say:'사마의',line:'싸움터의 모양을 보고 그 자리에서 바꾸는 사람입니다. 그러니 모양을 먼저 정해 주면 됩니다.'},
      {enter:'마속',at:[22,64],from:'left'},
      {emote:'마속',text:'!'},
      {say:'마속',line:'제가 산 위에 진을 치고 내려다보며 치면 어떻겠습니까? 병법에 높은 곳에 서라 했습니다.'},
      {emote:'사마의',text:'…'},
      {choice:'사마의',options:[
        {id:'ma_su',text:'마속을 곁에 두고 군략을 함께 짠다. 다만 산 위는 안 된다.',reply:'유상(마속), 그대의 재주는 쓰겠다. 그러나 물 없는 산은 무덤이다.',answer:{speaker:'마속',line:'…명심하겠습니다. 물길부터 쥐지요.'},note:'마속 영입(책사) · 책략 MP +15',
          effects:[{kind:'recruit',name:'마속',unitClass:'strategist'},{kind:'insight'},{kind:'flag',flag:'shu_masu'}]},
        {id:'water',text:'물길을 끼고 낮은 곳에 진을 친다.',reply:'장합이 언덕을 쥐었다면, 우리는 물을 쥔다. 언덕은 사흘이면 목마르다.',note:'첫 턴 방어 태세',effects:[{kind:'guard'}]},
        {id:'scout',text:'장합의 물 긷는 길을 먼저 끊는다.',reply:'교변의 명장도 물 없이는 바꿀 것이 없다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
      ]},
    ]},
  ],
  after:[
    {place:'완성 · 산길 어귀',art:4,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'제갈량',look:'strategist',at:[58,58],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'장합은 언덕을 버리고 북쪽으로 물러났다. 완성의 성문이 열렸다.'},
      {say:'제갈량',line:'중달, 위에 있었다면 그대가 나를 이리 막았겠구려. 다행이오, 이쪽에 있어서.'},
      {emote:'사마의',text:'…'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'조인이 형주에 남은 위군을 모두 모아 강릉으로 내려간다 합니다! 오의 여몽과 손을 잡았다는 소문입니다!'},
      {exit:'전령',to:'right'},
      {say:'사마의',line:'역시 강릉이다. 운장의 뒤를 노리는 칼이 둘이 되었구나.'},
    ]},
  ]},

{id:'IF2-shu-3x',year:'220년 · 상용 신성',title:'신성의 맹달',
  synopsis:'관우를 돕지 않고 위로 넘어간 맹달이 상용 신성에서 촉의 등을 노린다. 위에 있었다면 사마의가 여드레 만에 짓밟았을 그 성이다. 이번에는 촉의 장수로 그 길을 달린다.',
  scenes:[
    {place:'상용 · 신성 가는 길',art:11,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'사마랑',look:'physician',at:[22,66]},
      {name:'유봉',look:'spear'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'맹달은 촉을 버리고 위에 투항했다. 신성은 촉의 북쪽 등허리에 박힌 가시가 되었다.'},
      {enter:'유봉',at:[66,60],from:'right'},
      {emote:'유봉',text:'분노'},
      {say:'유봉',line:'맹달은 나와 함께 상용을 지키다 나를 버리고 달아났소! 그 성은 내 손으로 되찾겠소!'},
      {say:'사마랑',line:'신성은 험한 산성입니다. 맹달은 지원군이 오기까지 한 달은 걸린다 믿고 있을 겁니다.'},
      {move:'사마의',to:[46,60]},
      {say:'사마의',line:'한 달이라. 그러면 여드레 만에 가면 된다. 맹달은 셈은 잘하나 남의 발걸음은 셈하지 못한다.'},
      {enter:'전령',at:[86,64],from:'right'},
      {say:'전령',line:'신성의 문이 아직 반쯤 열려 있습니다! 맹달은 성벽을 고치는 중입니다!'},
      {choice:'사마의',options:[
        {id:'eight_days',text:'밤낮없이 달려 여드레 만에 성 밑에 닿는다.',reply:'맹달이 붓을 들어 위에 구원을 청할 때, 우리는 이미 성 밑이다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
        {id:'liu_feng',text:'유봉의 상용 군을 앞세운다.',reply:'버림받은 자의 분노가 성문을 연다.',answer:{speaker:'유봉',line:'고맙소, 중달! 이 원한을 오늘 갚겠소!'},note:'유봉의 상용 군이 초록 깃발로 돕는다',
          effects:[{kind:'reinforce',name:'유봉',unitClass:'spearman',side:'npc'}]},
        {id:'letter',text:'맹달의 부장들에게 투항을 권하는 글을 쏜다.',reply:'세 번 주인을 바꾼 자 곁에는 네 번째를 바라는 자가 있다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
      ]},
      {exit:'전령',to:'right'},
    ]},
  ],
  after:[
    {place:'신성 · 무너진 성문',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'유봉',look:'spear',at:[60,62],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'신성이 떨어졌다. 맹달은 성벽 위에서 사로잡혔다.'},
      {say:'유봉',line:'중달, 위에 있었어도 그대는 이 성을 이렇게 쳤을 것이오. 맹달이 운이 없었소.'},
      {emote:'사마의',text:'…'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'조인이 형주의 위군을 모두 모아 강릉으로 내려갑니다! 오의 여몽과 손을 잡았다 합니다!'},
      {exit:'전령',to:'right'},
      {say:'사마의',line:'등 뒤의 가시는 뽑았다. 이제 운장의 등 뒤로 간다.'},
    ]},
  ]},

{id:'shu:boss',year:'221년 · 강릉',title:'강릉의 봉화',
  synopsis:'조인이 오의 여몽과 손잡고 관우의 뒤, 강릉을 노렸다. 사마의가 일찍이 내다본 그 칼끝이다. 강릉을 지키면 형주가 남고, 관우가 산다.',
  scenes:[
    {place:'강릉 · 성루',art:8,cast:[
      {name:'사마의',look:'strategist',at:[38,58]},
      {name:'관우',look:'cavalry'},
      {name:'사마랑',look:'physician',at:[22,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'221년 겨울, 강릉. 흰 옷을 입은 오의 상인 배들이 강을 거슬러 올라왔다.'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'강가 봉화대 셋이 소리 없이 넘어갔습니다! 상인 배 속에서 오군이 쏟아져 나옵니다!'},
      {emote:'사마랑',text:'땀'},
      {say:'사마의',line:'백의도강(白衣渡江)이라. 여몽이 배를 상인으로 꾸몄구나. 북쪽에서는 조인이 내려온다.'},
      {exit:'전령',to:'right'},
      {enter:'관우',at:[64,58],from:'right'},
      {say:'관우',line:'중달, 그대의 말을 들어 봉화를 더 세웠더니 이렇게 알게 되었소. 이번 싸움은 그대가 지휘하시오.',when:'shu_guanyu'},
      {say:'관우',line:'번성에서 바로 달려왔소. 그대가 말한 강릉의 칼끝, 이 청룡도로 받아 주겠소.',unless:'shu_guanyu'},
      {move:'사마의',to:[46,58]},
    ]},
    {place:'강릉 · 북문 밖',art:16,cast:[
      {name:'사마의',look:'strategist',at:[34,62]},
      {name:'관우',look:'cavalry',at:[48,60]},
      {name:'조인',look:'heavy',at:[76,56],face:'left'},
      {name:'위군 병사',look:'spear',at:[86,62],face:'left'}],
    steps:[
      {move:'조인',to:[68,56]},
      {say:'조인',line:'사마의! 선왕께서 너를 그리 아끼셨거늘, 귀 큰 놈의 개가 되었느냐!'},
      {emote:'관우',text:'분노'},
      {say:'사마의',line:'자효(조인) 장군, 번성에서 장군을 다시 뵙기를 바랐는데 강릉에서 뵙는구려.'},
      {choice:'사마의',options:[
        {id:'beacon',text:'남은 봉화대에 불을 올리고 강가를 먼저 지킨다.',reply:'여몽의 배가 먼저다. 등이 굳어야 앞을 본다.',note:'첫 턴 방어 태세 · 강릉의 봉화가 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'shu_beacon'}]},
        {id:'guan_yu',text:'관우에게 조인의 본진을 맡긴다.',reply:'번성에서 끝내지 못한 싸움, 운장이 끝내시오.',answer:{speaker:'관우',line:'좋소! 자효의 목은 내가 가져가리다!'},note:'관우의 형주군이 초록 깃발로 돕는다 · 처음 2턴 사기 상승',
          effects:[{kind:'reinforce',name:'관우',unitClass:'cavalry',side:'npc'},{kind:'rally'}]},
        {id:'bold',text:'조인의 본진을 정면으로 친다.',reply:'조인은 지키는 장수다. 지킬 틈을 주지 않는다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {exit:'위군 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'강릉 · 봉화대',art:3,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'관우',look:'cavalry',at:[60,58],face:'left'},
      {name:'제갈량',look:'strategist'}],
    steps:[
      {narrate:'조인은 북쪽으로 물러나고, 여몽의 배는 강을 따라 돌아갔다. 형주는 촉에 남았고, 관우는 맥성으로 가지 않았다.'},
      {say:'관우',line:'중달, 그대 덕에 내 목이 아직 붙어 있구려. 이 은혜는 칼로 갚겠소.'},
      {enter:'제갈량',at:[80,60],from:'right'},
      {say:'제갈량',line:'형주를 지켰으니 이제 북쪽을 볼 수 있소. 몇 해만 기다리시오. 출사표를 쓸 날이 올 것이오.'},
      {emote:'사마의',text:'…'},
      {move:'제갈량',to:[72,58]},
      {narrate:'몇 해 뒤 한중왕 유비가 세상을 떠났다. 유선이 뒤를 잇고, 제갈량은 붓을 들었다.'},
    ]},
  ]},

{id:'fate:3:shu',year:'227년 · 한중',title:'출사표',
  synopsis:'제갈량이 출사표를 올렸다. "중달, 이번에는 그대가 선봉이오." 북쪽에는 위의 대군이, 남쪽에는 아직 복종하지 않은 남중이 있다.',
  scenes:[
    {place:'한중 · 승상부',art:14,cast:[
      {name:'제갈량',look:'strategist',at:[66,52],face:'left'},
      {name:'사마의',look:'strategist',at:[42,60]},
      {name:'위연',look:'infantry'},
      {name:'마속',look:'strategist'},
      {name:'남중 사자',look:'bandit'}],
    steps:[
      {narrate:'227년, 한중. 제갈량이 후주 유선에게 출사표를 올렸다. "선제께서 창업을 반도 이루지 못하고 붕어하시니…"'},
      {say:'제갈량',line:'중달, 이번에는 그대가 선봉이오. 위의 지략을 아는 자가 촉에 있으니, 기산을 넘을 때가 왔소.'},
      {enter:'위연',at:[80,62],from:'right'},
      {say:'위연',line:'승상, 자오곡으로 열흘이면 장안이오! 군사(사마의)가 함께라면 낙양까지 단숨이오!'},
      {enter:'남중 사자',at:[90,68],from:'right'},
      {emote:'남중 사자',text:'땀'},
      {say:'남중 사자',line:'급보요! 남중의 맹획이 다시 반기를 들었습니다! 등갑병과 코끼리 떼가 영창으로 몰려옵니다!'},
      {enter:'마속',at:[24,64],from:'left'},
      {say:'마속',line:'군사, 남중을 두고 북쪽으로 가면 등 뒤가 탑니다. 마음을 치는 것이 상책이라 저는 승상께 아뢰었지요.'},
      {move:'사마의',to:[48,58]},
      {emote:'사마의',text:'…'},
      {say:'제갈량',line:'그대가 고르시오, 중달. 나는 그대가 가지 않는 쪽을 맡겠소.'},
      {choice:'사마의',options:[
        {id:'shu_north',text:'기산을 넘어 북벌을 완수한다.',reply:'위를 아는 자가 위를 친다. 이번에는 진창을 사흘에 넘겠습니다.',answer:{speaker:'위연',line:'하하! 드디어 북쪽이오!'},note:'가상 · 한실 부흥 · 낙양 진격 · 우두머리 조예'},
        {id:'shu_south',text:'남중을 평정하고 촉의 안쪽부터 다진다.',reply:'등 뒤를 다지지 않고 앞으로 가는 자는 오래 못 간다.',answer:{speaker:'제갈량',line:'그러면 북쪽은 내가 지키겠소. 남중을 부탁하오.'},note:'가상 · 촉의 승상 · 남중 밀림 · 우두머리 맹획'},
      ]},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 하편 가상 · 한실 부흥 (shu_north) — 적: 학소·장합(또는 하후무)·조예
// ════════════════════════════════════════════════════════════════
{id:'IF3-sn-1',year:'228년 · 진창',title:'진창',
  synopsis:'진창성을 학소가 지킨다. 제갈량을 스무 날 붙잡았던 성을, 사마의는 사흘 안에 넘으려 한다. 위연은 자오곡으로 장안을 곧장 치자고 조른다.',
  scenes:[
    {place:'기산 · 촉군 군막',art:14,cast:[
      {name:'제갈량',look:'strategist',at:[64,54],face:'left'},
      {name:'사마의',look:'strategist',at:[42,60]},
      {name:'위연',look:'infantry'},
      {name:'강유',look:'cavalry'}],
    steps:[
      {narrate:'228년 봄, 촉군이 기산을 넘었다. 선봉에 선 것은 위에서 온 책사였다.'},
      {enter:'위연',at:[80,62],from:'right'},
      {say:'위연',line:'진창 같은 작은 성에 붙들려 무엇하오! 내게 오천만 주시오. 자오곡으로 열흘이면 장안이오!'},
      {say:'제갈량',line:'문장(위연), 그 길은 험하고, 한 번 막히면 오천이 다 죽소.'},
      {emote:'위연',text:'분노'},
      {say:'사마의',line:'장안을 지키는 하후무는 부마일 뿐 장수가 아니오. 문장의 길이 아주 틀린 것은 아니외다.'},
      {enter:'강유',at:[24,64],from:'left'},
      {say:'강유',line:'천수의 강백약이오. 위에서 의심받아 성문 밖에 버려졌소. 진창의 학소는 내가 잘 아오.'},
      {emote:'제갈량',text:'!'},
      {choice:'사마의',options:[
        {id:'jiang_wei',text:'강유를 받아들여 진창 공략에 앞세운다.',reply:'버려진 인재를 줍는 것도 군략이다.',answer:{speaker:'제갈량',line:'중달, 내 뒤를 이을 사람을 그대가 찾아 주었구려.'},note:'강유 영입(기병) · 처음 2턴 사기 상승',
          effects:[{kind:'recruit',name:'강유',unitClass:'cavalry'},{kind:'rally'},{kind:'flag',flag:'sn_jiangwei'}]},
        {id:'ziwu',text:'진창을 넘으면 위연의 자오곡 계책을 쓴다.',reply:'승상이 걸지 못한 판을, 이번에는 내가 걸어 보겠소.',answer:{speaker:'위연',line:'하하! 위에서 온 사람이 촉 사람보다 배짱이 크구려!'},note:'다음 전장이 「자오곡」으로 바뀐다 · 위연이 함께 싸운다',
          effects:[{kind:'path',tale:'IF3-sn-2x'},{kind:'recruit',name:'위연',unitClass:'infantry'},{kind:'flag',flag:'sn_ziwu'}]},
        {id:'siege',text:'운제와 충차를 사흘 안에 세운다.',reply:'학소는 스무 날을 버텼다. 그러면 스무 날 치 공성구를 사흘에 만들면 된다.',note:'책략 MP +15 · 첫 턴 방어 태세',effects:[{kind:'insight'},{kind:'guard'}]},
      ]},
    ]},
  ],
  after:[
    {place:'진창 · 무너진 성벽',art:8,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'강유',look:'cavalry'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'진창성이 사흘 만에 떨어졌다. 학소는 성루 위에서 칼을 내려놓았다.'},
      {enter:'강유',at:[60,62],from:'right',when:'sn_jiangwei'},
      {say:'강유',line:'학소가 말하더이다. 제갈량이었다면 스무 날은 버텼을 텐데, 사마의라서 사흘이었다고.',when:'sn_jiangwei'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'위의 장합이 가정으로 내려와 장안 길을 막았습니다!',unless:'sn_ziwu'},
      {say:'전령',line:'위연 장군이 자오곡 어귀에 섰습니다! 장안의 하후무는 아직 아무것도 모릅니다!',when:'sn_ziwu'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'IF3-sn-2',year:'228년 · 가정',title:'가정 너머',
  synopsis:'가정을 지나 장안으로. 위의 명장 장합이 마지막 길을 막는다. 마속이 산 위에 진을 쳐서 무너졌어야 할 그 고개에, 이번에는 위의 군략을 아는 자가 섰다.',
  scenes:[
    {place:'가정 · 고갯길',art:3,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'마속',look:'strategist',at:[56,60],face:'left'},
      {name:'왕평',look:'archer'},
      {name:'촉군 병사',look:'spear',at:[72,68],face:'left'}],
    steps:[
      {narrate:'가정. 길이 좁고 남쪽에 외딴 산이 하나 솟았다. 물은 산 아래 북쪽 샘에만 있다.'},
      {say:'마속',line:'군사, 저 산 위에 진을 치면 장합을 내려다볼 수 있습니다. 병법에 높은 곳에 서면 이긴다 했습니다.'},
      {enter:'왕평',at:[20,66],from:'left'},
      {emote:'왕평',text:'!'},
      {say:'왕평',line:'안 됩니다! 산 위에는 물이 없습니다. 장합이 샘을 끊으면 사흘 안에 우리 군은 목말라 무너집니다.'},
      {move:'촉군 병사',to:[80,66]},
      {say:'사마의',line:'내가 장합이었다면 바로 그렇게 했을 것이다. 유상(마속), 병법은 책에 있지 않고 물에 있다.'},
      {emote:'마속',text:'땀'},
      {choice:'사마의',options:[
        {id:'wang_ping',text:'왕평에게 북쪽 샘과 길목을 맡긴다.',reply:'글을 몰라도 땅을 아는 자가 오늘의 군사다.',answer:{speaker:'왕평',line:'목숨을 걸고 샘을 지키겠습니다!'},note:'왕평 영입(궁병) · 첫 턴 방어 태세',
          effects:[{kind:'recruit',name:'왕평',unitClass:'archer'},{kind:'guard'},{kind:'flag',flag:'sn_wangping'}]},
        {id:'hill',text:'마속의 말대로 산 위에 진을 친다.',reply:'…좋다. 다만 샘으로 가는 길은 내가 따로 지킨다. 높은 곳의 이득만 빌린다.',answer:{speaker:'마속',line:'감사합니다, 군사! 반드시 보여 드리겠습니다!'},note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배 · 마속의 고집이 남는다',
          effects:[{kind:'bold'},{kind:'flag',flag:'sn_hill'}]},
        {id:'scout',text:'장합의 별동대가 오는 산길을 먼저 막는다.',reply:'교변의 명장은 반드시 옆길을 쓴다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
      ]},
    ]},
  ],
  after:[
    {place:'가정 · 북쪽 샘',art:4,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'마속',look:'strategist',at:[60,60],face:'left'},
      {name:'장합',look:'cavalry'}],
    steps:[
      {narrate:'장합은 끝내 샘을 끊지 못했다. 가정이 촉의 손에 남았다.'},
      {enter:'장합',at:[86,58],from:'right'},
      {say:'장합',line:'사마중달! 그대가 위에 있었다면 이 고개는 내 것이었을 텐데. 하늘이 위를 버렸구려.'},
      {exit:'장합',to:'right'},
      {say:'마속',line:'산 위에서 내려다보니 알겠습니다. 샘을 지킨 이가 없었다면 저는 저 산에서 죽었을 겁니다.',when:'sn_hill'},
      {emote:'마속',text:'…'},
      {say:'사마의',line:'장안이 열렸다. 다음은 낙양이다.'},
    ]},
  ]},

{id:'IF3-sn-2x',year:'228년 · 자오곡 → 장안',title:'자오곡',
  synopsis:'위연의 계책대로 자오곡 칠백 리 험로를 열흘 만에 넘었다. 장안을 지키는 부마 하후무는 촉군이 산을 넘어올 줄 꿈에도 몰랐다. 하후무를 꺾으면 장안이 떨어진다.',
  scenes:[
    {place:'자오곡 · 북쪽 출구',art:4,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'위연',look:'infantry',at:[56,60],face:'left'},
      {name:'촉군 병사',look:'spear',at:[22,68]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'열흘 동안 잔도를 기고 벼랑을 탔다. 자오곡 북쪽 출구에서 장안의 성벽이 보였다.'},
      {emote:'촉군 병사',text:'땀'},
      {move:'촉군 병사',to:[28,66]},
      {say:'위연',line:'봤소, 군사! 열흘이오, 열흘! 승상이 이 길을 두려워한 걸 평생 비웃겠소!'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'장안의 하후무가 연회를 열고 있습니다! 성문 수비병이 반은 졸고 있습니다!'},
      {say:'사마의',line:'하후무는 하후돈의 아들이나 아비를 닮지 않았다. 연회가 끝나기 전에 끝낸다.'},
      {exit:'전령',to:'right'},
      {choice:'사마의',options:[
        {id:'feast',text:'연회가 한창일 때 성문을 친다.',reply:'술잔을 쥔 손은 칼을 늦게 쥔다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
        {id:'rest',text:'지친 병사들을 하룻밤 쉬게 하고 새벽에 친다.',reply:'열흘을 걸은 다리로는 성벽을 오르지 못한다.',note:'처음 2턴 사기 상승 · 첫 턴 방어 태세',effects:[{kind:'rally'},{kind:'guard'}]},
        {id:'wang_ping',text:'뒤따라온 왕평에게 퇴로를 막게 한다.',reply:'하후무는 싸우기보다 달아날 사람이다. 달아날 길을 먼저 막는다.',answer:{speaker:'위연',line:'왕평이 따라왔다고? 그 촌놈, 발은 빠르구려!'},note:'왕평 영입(궁병) · 척후로 적 한 부대가 나오지 않는다',
          effects:[{kind:'recruit',name:'왕평',unitClass:'archer'},{kind:'scout'},{kind:'flag',flag:'sn_wangping'}]},
      ]},
    ]},
  ],
  after:[
    {place:'장안 · 열린 성문',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'위연',look:'infantry',at:[58,62],face:'left'},
      {name:'제갈량',look:'strategist'}],
    steps:[
      {narrate:'장안이 하룻밤 만에 떨어졌다. 하후무는 서쪽으로 달아났다.'},
      {enter:'제갈량',at:[80,58],from:'right'},
      {say:'제갈량',line:'문장, 내가 틀렸소. 그리고 중달, 그대는 내가 걸지 못한 판을 걸었구려.'},
      {emote:'위연',text:'♪'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'승상께서 쌓은 군량이 없었다면 열흘을 버티지 못했을 겁니다. 이제 낙양입니다.'},
    ]},
  ]},

{id:'shu_north:boss',year:'229년 · 낙양',title:'낙양 입성',
  synopsis:'장안을 잃은 위의 젊은 황제 조예가 몸소 금군을 이끌고 낙양 앞에 섰다. 조조의 손자이자 조비의 아들, 사마의가 어린 시절을 기억하는 그 아이다. 낙양을 얻으면 한의 깃발이 다시 오른다.',
  scenes:[
    {place:'낙양 서쪽 · 촉군 군영',art:6,cast:[
      {name:'제갈량',look:'strategist',at:[62,54],face:'left'},
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마랑',look:'physician'}],
    steps:[
      {narrate:'229년, 촉군이 낙양 서쪽 들판에 닿았다. 한(漢)의 붉은 깃발이 위의 도성을 바라보았다.'},
      {enter:'사마랑',at:[22,64],from:'left'},
      {say:'사마랑',line:'중달, 조예가 몸소 나왔다 한다. 선왕께서 사냥터에서 어미 사슴을 쏘지 못한 그 아이를 귀히 여기셨지.'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'어미 잃은 새끼 사슴을 쏘지 못한 아이였지요. 이제 그 아이가 황제가 되어 나를 쏘려 합니다.'},
      {move:'제갈량',to:[54,56]},
      {say:'제갈량',line:'중달, 마음이 쓰이면 내가 앞에 서겠소.'},
    ]},
    {place:'낙양 · 성문 앞 들판',art:16,cast:[
      {name:'사마의',look:'strategist',at:[32,62]},
      {name:'조예',look:'strategist',at:[72,54],face:'left'},
      {name:'금군 병사',look:'heavy',at:[84,60],face:'left'},
      {name:'촉군 병사',look:'spear',at:[18,66]}],
    steps:[
      {move:'조예',to:[64,56]},
      {say:'조예',line:'사마의, 할아버님께서 그대를 경계하라 하셨소. 이리는 끝내 등을 돌린다고.'},
      {emote:'촉군 병사',text:'!'},
      {say:'사마의',line:'폐하, 신은 등을 돌린 것이 아니라 얼굴을 돌렸을 뿐입니다. 한(漢) 쪽으로.'},
      {choice:'사마의',options:[
        {id:'spare',text:'황제는 다치게 하지 말라 명한다.',reply:'사슴을 쏘지 못한 아이를, 나도 쏘지 않겠다.',note:'첫 턴 방어 태세 · 조예의 목숨이 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'sn_spare_rui'}]},
        {id:'kongming',text:'제갈량의 본대와 함께 친다.',reply:'와룡과 총이 함께 서는 날이다.',answer:{speaker:'제갈량',line:'좋소. 오늘은 내가 그대의 날개가 되겠소.'},note:'제갈량의 본대가 초록 깃발로 돕는다',effects:[{kind:'reinforce',name:'제갈량',unitClass:'strategist',side:'npc'}]},
        {id:'bold',text:'금군 한가운데를 뚫는다.',reply:'황제가 앞에 섰으니, 그 앞까지 간다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {exit:'금군 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'낙양 · 성문',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'조예',look:'strategist'},
      {name:'제갈량',look:'strategist',at:[24,62]}],
    steps:[
      {narrate:'금군이 무너지고 낙양의 성문이 열렸다.'},
      {enter:'조예',at:[66,58],from:'right',when:'sn_spare_rui'},
      {say:'조예',line:'…살려 주는가. 할아버님 말씀이 틀렸구려. 그대는 이리가 아니었소.',when:'sn_spare_rui'},
      {narrate:'조예는 낙양을 버리고 동쪽 업성으로 달아났다. 위는 하북으로 물러났다.',unless:'sn_spare_rui'},
      {emote:'제갈량',text:'♪'},
      {move:'제갈량',to:[30,62]},
      {say:'제갈량',line:'중달, 함께 들어갑시다. 선제께 아뢸 말이 생겼소.'},
    ]},
  ]},

{id:'ending:shu_north',year:'229년 · 낙양',title:'한실 부흥',
  synopsis:'와룡과 총이 함께 낙양에 들어섰다. 한(漢)의 깃발이 다시 도성 위에 올랐다.',
  scenes:[
    {place:'낙양 · 옛 한의 궁궐',art:5,cast:[
      {name:'제갈량',look:'strategist',at:[60,54],face:'left'},
      {name:'사마의',look:'strategist'},
      {name:'위연',look:'infantry'},
      {name:'강유',look:'cavalry'},
      {name:'사마랑',look:'physician',at:[18,66]}],
    steps:[
      {narrate:'와룡과 총이 함께 낙양에 들어섰다. 한(漢)의 깃발이 다시 도성 위에 올랐다.'},
      {enter:'사마의',at:[40,58],from:'left'},
      {say:'제갈량',line:'선제께서 이 궁을 보셨다면… 중달, 출사표의 끝을 그대가 썼소.'},
      {say:'사마의',line:'승상께서 쓰신 글에 신은 마침표 하나를 찍었을 뿐입니다.'},
      {enter:'강유',at:[76,62],from:'right',when:'sn_jiangwei'},
      {say:'강유',line:'천수에서 버려진 몸이 한의 도성에 섰습니다. 두 분 스승께 감사드립니다.',when:'sn_jiangwei'},
      {enter:'위연',at:[86,58],from:'right',when:'sn_ziwu'},
      {say:'위연',line:'자오곡 열흘! 이 이야기는 백 년은 술자리에서 떠들겠소!',when:'sn_ziwu'},
      {emote:'사마랑',text:'…'},
      {say:'사마랑',line:'중달, 하내가 멀지 않다. 언젠가 아버님 무덤에 이 소식을 전하자꾸나.'},
      {narrate:'위를 버린 사마의가 한실을 되살렸다 — 누구도 쓰지 못한 출사표의 끝이었다.'},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 하편 가상 · 촉의 승상 (shu_south) — 적: 올돌골·축융(또는 타사대왕)·맹획
// ════════════════════════════════════════════════════════════════
{id:'IF3-ss-1',year:'227년 · 남중 반사곡',title:'등갑병의 숲',
  synopsis:'제갈량에게 북쪽을 맡기고 사마의는 남중으로 내려왔다. 기름 먹인 등갑을 두른 올돌골의 군대가 숲을 메웠다. 칼도 화살도 듣지 않는다 — 불만이 답이다.',
  scenes:[
    {place:'남중 · 반사곡 어귀',art:11,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'마대',look:'cavalry'},
      {name:'사마랑',look:'physician',at:[22,66]},
      {name:'촉군 병사',look:'spear',at:[58,68],face:'left'}],
    steps:[
      {narrate:'227년 여름, 남중. 숲은 덥고 축축했으며, 그 숲 속에서 등갑병의 갑옷이 기름처럼 번들거렸다.'},
      {emote:'촉군 병사',text:'땀'},
      {move:'촉군 병사',to:[50,70]},
      {say:'사마랑',line:'등갑은 기름에 반년을 담갔다 말린 것이라 한다. 강물에도 가라앉지 않고 칼도 미끄러진다지.'},
      {enter:'마대',at:[70,60],from:'right'},
      {say:'마대',line:'군사, 서량의 마대요. 숲 바깥을 기병으로 돌면 등갑병의 뒤를 칠 수 있소.'},
      {say:'사마의',line:'기름에 담근 갑옷이라. 그렇다면 답은 정해졌다. 다만 불은 쓰는 자의 수명도 깎는다 했지.'},
      {emote:'사마랑',text:'…'},
      {choice:'사마의',options:[
        {id:'fire',text:'반사곡에 기름 수레와 지뢰를 묻는다.',reply:'저들이 기름을 입었으니, 나는 불을 준다. 이 죄는 내가 지겠다.',note:'기습 · 적 전원 체력 80%로 시작 · 반사곡의 불이 남는다',effects:[{kind:'ambush'},{kind:'flag',flag:'ss_fire'}]},
        {id:'ma_dai',text:'마대의 기병으로 숲 바깥을 돈다.',reply:'숲 속에서 싸우지 않는다. 숲 밖으로 끌어낸다.',answer:{speaker:'마대',line:'서량 기병의 발을 보여 드리지요!'},note:'마대 영입(기병) · 척후로 적 한 부대가 나오지 않는다',
          effects:[{kind:'recruit',name:'마대',unitClass:'cavalry'},{kind:'scout'},{kind:'flag',flag:'ss_madai'}]},
        {id:'hermit',text:'만안계곡의 은자를 먼저 찾아간다.',reply:'맹획의 형이 산속에 숨어 산다 들었다. 남중은 남중 사람에게 묻는다.',note:'다음 전장이 「독천의 타사대왕」으로 바뀐다 · 책략 MP +15',
          effects:[{kind:'path',tale:'IF3-ss-2x'},{kind:'insight'},{kind:'flag',flag:'ss_hermit'}]},
      ]},
      {exit:'촉군 병사',to:'left'},
    ]},
  ],
  after:[
    {place:'반사곡 · 연기 걷힌 골짜기',art:4,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마랑',look:'physician',at:[24,64]},
      {name:'남만 포로',look:'bandit'}],
    steps:[
      {narrate:'올돌골의 등갑군이 무너졌다. 오과국의 왕은 숲 너머로 달아났다.'},
      {emote:'사마의',text:'…',when:'ss_fire'},
      {say:'사마의',line:'사직에는 공이 있으나, 내 수명은 반드시 줄었을 것이다.',when:'ss_fire'},
      {enter:'남만 포로',at:[70,64],from:'right'},
      {say:'남만 포로',line:'대왕(맹획)의 부인 축융께서 독룡동에서 기다리십니다. 비도 다섯 자루가 그대를 노리오.'},
      {say:'사마랑',line:'풀어 보내라 하겠지, 중달? 남중은 마음을 쳐야 한다는 마속의 말을 나도 들었다.'},
      {exit:'남만 포로',to:'right'},
    ]},
  ]},

{id:'IF3-ss-2',year:'227년 · 독룡동',title:'독룡동',
  synopsis:'맹획의 아내 축융이 독룡동 앞에서 비도를 겨눈다. 남만의 여장수는 사내 장수들보다 날래고, 그 칼은 등 뒤에서 날아온다.',
  scenes:[
    {place:'독룡동 · 동굴 앞 숲',art:11,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'관색',look:'spear'},
      {name:'축융',look:'lady',at:[74,56],face:'left'},
      {name:'남만 병사',look:'bandit',at:[86,62],face:'left'}],
    steps:[
      {narrate:'독룡동 앞, 축융 부인이 붉은 깃발 아래 섰다. 등에는 비도 다섯 자루가 꽂혀 있었다.'},
      {say:'축융',line:'사내들이 줄줄이 지고 왔으니 이번에는 내가 나가야지. 위에서 온 책사, 내 칼은 그대 목을 기억하겠소.'},
      {move:'축융',to:[66,58]},
      {enter:'관색',at:[54,62],from:'left'},
      {say:'관색',line:'군사, 관운장의 셋째 관색이오. 저 여장수는 제가 사로잡겠습니다. 칼을 쓰는 사람끼리 겨루지요.'},
      {emote:'축융',text:'♪'},
      {choice:'사마의',options:[
        {id:'guan_suo',text:'관색에게 축융을 사로잡게 한다.',reply:'관씨 집안의 창은 여인이라 봐주지 않겠지. 다만 죽이지는 마라.',answer:{speaker:'관색',line:'명을 받듭니다!'},note:'관색 영입(창병) · 처음 2턴 사기 상승',
          effects:[{kind:'recruit',name:'관색',unitClass:'spearman'},{kind:'rally'},{kind:'flag',flag:'ss_guansuo'}]},
        {id:'shield',text:'방패를 겹쳐 비도를 막으며 천천히 다가간다.',reply:'비도는 다섯 자루뿐이다. 다섯 번만 막으면 된다.',note:'첫 턴 방어 태세',effects:[{kind:'guard'}]},
        {id:'scout',text:'동굴 뒤 샛길을 먼저 막는다.',reply:'여장수는 지면 달아나지 않고 뒤로 돌아온다. 그 길을 막는다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
      ]},
      {exit:'남만 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'독룡동 · 동굴 앞',art:4,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'축융',look:'lady',at:[64,58],face:'left'}],
    steps:[
      {narrate:'축융은 사로잡혔다가 다시 풀려났다. 그녀는 독룡동 깊은 곳을 가리켰다.'},
      {say:'축융',line:'관씨 아이의 창이 빠르더구려. 그대는 좋은 장수를 두었소.',when:'ss_guansuo'},
      {say:'축융',line:'살려 보내는 건 고맙지만, 남편은 고집이 세오. 은갱동에서 코끼리를 몰고 나올 것이오.'},
      {emote:'사마의',text:'…'},
      {move:'축융',to:[56,58]},
      {exit:'축융',to:'right'},
    ]},
  ]},

{id:'IF3-ss-2x',year:'227년 · 독천',title:'독천의 타사대왕',
  synopsis:'만안계곡의 은자 맹절은 동생 맹획의 길을 막으려면 독천을 넘어야 한다고 일렀다. 독룡동의 주인 타사대왕이 네 개의 독 샘 뒤에서 촉군을 기다린다.',
  scenes:[
    {place:'만안계곡 · 은자의 초막',art:12,cast:[
      {name:'사마의',look:'strategist',at:[38,62]},
      {name:'맹절',look:'sage',at:[62,58],face:'left'},
      {name:'사마랑',look:'physician'},
      {name:'촉군 병사',look:'spear',at:[22,68]}],
    steps:[
      {narrate:'은자는 맹획의 형 맹절이었다. 그는 동생과 달리 칼을 버리고 산속에 숨어 살았다.'},
      {say:'맹절',line:'아우의 길목에 타사대왕이 있소. 네 개의 샘이 모두 독이라, 마시면 말을 잃고 씻으면 살이 녹소.'},
      {emote:'촉군 병사',text:'땀'},
      {enter:'사마랑',at:[28,64],from:'left'},
      {say:'사마랑',line:'독이라면 내 일이다. 해독할 약초가 이 근처에 있겠지요?'},
      {say:'맹절',line:'초막 뒤 해엽운향(薤葉芸香)을 입에 물면 독기가 들지 않소. 그리고 만안계곡의 샘물은 맑소.'},
      {move:'사마의',to:[46,60]},
      {say:'사마의',line:'형이 아우를 막는 길을 알려 주는구려. 맹획을 살려서 데려오리다.'},
      {choice:'사마의',options:[
        {id:'herb',text:'사마랑에게 해엽운향을 온 군에 나누게 한다.',reply:'형님, 이번 싸움은 형님의 약이 이깁니다.',answer:{speaker:'사마랑',line:'풀 한 잎씩, 한 명도 빠뜨리지 않으마.'},note:'첫 턴 방어 태세 · 처음 2턴 사기 상승',effects:[{kind:'guard'},{kind:'rally'},{kind:'flag',flag:'ss_herb'}]},
        {id:'scout',text:'맑은 샘 쪽으로 돌아 타사대왕의 뒤로 간다.',reply:'독 샘을 건너지 않고, 맑은 샘을 따라간다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
        {id:'bold',text:'독 샘 한가운데를 곧장 건넌다.',reply:'약초를 물고 단숨에 건넌다. 머뭇거리면 독이 든다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
    ]},
  ],
  after:[
    {place:'독천 · 맑아진 샘',art:4,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'맹절',look:'sage',at:[62,58],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'타사대왕이 쓰러지고, 촉군은 한 사람도 독에 쓰러지지 않았다.'},
      {say:'맹절',line:'아우는 은갱동에 있소. 목록대왕의 맹수와 코끼리 떼를 데리고. 부디 살려 주시오.'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'맹획이 은갱동에서 코끼리를 몰고 나옵니다! 일곱 번째 싸움이라 외칩니다!'},
      {exit:'맹절',to:'left'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'shu_south:boss',year:'228년 · 은갱동',title:'일곱 번째 사로잡음',
  synopsis:'여섯 번 사로잡히고 여섯 번 풀려난 맹획이 은갱동에서 코끼리 떼를 몰고 나왔다. 일곱 번째 싸움이다. 이번에 남만의 마음을 얻지 못하면 남중은 영영 촉의 등 뒤에서 불탄다.',
  scenes:[
    {place:'은갱동 · 군막',art:14,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마랑',look:'physician',at:[24,64]},
      {name:'마대',look:'cavalry'}],
    steps:[
      {narrate:'은갱동 앞 들판에 코끼리 떼가 산처럼 섰다. 맹획은 여섯 번 사로잡혔고, 여섯 번 풀려났다.'},
      {enter:'마대',at:[64,60],from:'right'},
      {say:'마대',line:'군사, 여섯 번이나 놓아주었는데 또 덤빕니다. 이번에는 목을 베는 것이 어떻소.'},
      {emote:'사마랑',text:'?'},
      {say:'사마랑',line:'중달, 승상이었다면 일곱 번째도 놓아주었을 게다. 너는 어찌하겠느냐.'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'놓아주는 것은 쉽고, 마음을 얻는 것은 어렵습니다. 둘이 같을지는 싸워 보면 알겠지요.'},
    ]},
    {place:'은갱동 · 앞 들판',art:16,cast:[
      {name:'사마의',look:'strategist',at:[32,62]},
      {name:'맹획',look:'elephant',at:[74,54],face:'left'},
      {name:'남만 병사',look:'bandit',at:[86,62],face:'left'},
      {name:'촉군 병사',look:'spear',at:[18,66]}],
    steps:[
      {move:'맹획',to:[66,56]},
      {say:'맹획',line:'위에서 온 책사! 제갈량도 아니면서 나를 여섯 번 잡았다고 우쭐하지 마라! 일곱 번째는 내가 이긴다!'},
      {emote:'촉군 병사',text:'땀'},
      {move:'촉군 병사',to:[12,68]},
      {choice:'사마의',options:[
        {id:'seventh',text:'이기거든 일곱 번째로 놓아준다고 미리 외친다.',reply:'죽음을 두려워하지 않는 자에게는 삶을 준다.',note:'처음 2턴 사기 상승 · 칠종칠금이 남는다',effects:[{kind:'rally'},{kind:'flag',flag:'ss_seventh'}]},
        {id:'execute',text:'이번에는 반드시 목을 벤다고 군에 알린다.',reply:'여섯 번이면 족하다. 촉의 등 뒤는 오늘 끝낸다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배 · 맹획을 벤 일이 남는다',effects:[{kind:'bold'},{kind:'flag',flag:'ss_execute'}]},
        {id:'beasts',text:'불을 뿜는 나무 짐승 수레로 코끼리 떼를 맞선다.',reply:'짐승은 불을 두려워한다. 코끼리도 짐승이다.',note:'책략 MP +15 · 기습으로 적 전원 체력 80%로 시작',effects:[{kind:'insight'},{kind:'ambush'}]},
      ]},
      {exit:'남만 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'은갱동 · 군막 앞',art:6,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'맹획',look:'bandit'}],
    steps:[
      {narrate:'코끼리 떼가 흩어지고, 맹획은 일곱 번째로 사로잡혔다.'},
      {enter:'맹획',at:[66,60],from:'right',unless:'ss_execute'},
      {say:'맹획',line:'일곱 번 잡고 일곱 번 놓아주다니… 남인은 다시는 배반하지 않겠소. 하늘의 위엄이오.',when:'ss_seventh'},
      {say:'맹획',line:'나를 풀어 주는가? 다음엔… 아니, 다음은 없겠구려.',unless:'ss_seventh'},
      {narrate:'사마의는 맹획의 목을 베었다. 남중은 고요해졌으나, 숲 속의 눈들은 오래 촉군을 노려보았다.',when:'ss_execute'},
      {move:'사마의',to:[48,60]},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'ending:shu_south',year:'230년 · 성도',title:'촉의 승상',
  synopsis:'남중의 맹획이 일곱 번째로 머리를 숙였다. 사마의는 제갈량의 뒤를 이어 촉의 승상이 되었다.',
  scenes:[
    {place:'성도 · 승상부',art:12,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'제갈량',look:'strategist'},
      {name:'사마랑',look:'physician',at:[22,64]},
      {name:'맹획',look:'bandit'}],
    steps:[
      {narrate:'남중이 고요해진 해, 제갈량은 북쪽 싸움에서 지친 몸으로 성도에 돌아왔다.'},
      {enter:'제갈량',at:[64,56],from:'right'},
      {say:'제갈량',line:'중달, 내 부채를 받으시오. 이제 촉의 안살림은 그대가 맡으시오. 나는 조금 쉬어야겠소.'},
      {say:'사마의',line:'승상의 부채는 무겁습니다. 다만 쥐어 보겠습니다.'},
      {enter:'맹획',at:[80,62],from:'right',when:'ss_seventh'},
      {say:'맹획',line:'남중 사람들이 공물을 가져왔소. 승상이 바뀌어도 남인의 맹세는 바뀌지 않소!',when:'ss_seventh'},
      {say:'사마랑',line:'남중에서 아직도 밤마다 횃불이 오른다 한다. 벤 목 하나가 백 개의 원한을 남겼구나.',when:'ss_execute'},
      {emote:'사마랑',text:'…'},
      {say:'사마랑',line:'중달, 하내로는 돌아가지 않을 셈이냐.'},
      {say:'사마의',line:'고향은 마음에 두면 됩니다, 형님. 이제 이곳이 제 자리입니다.'},
      {narrate:'위에서 태어나 촉에서 늙은 책사 — 그는 끝내 고향 하내로 돌아가지 않았다.'},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 하편 가상 · 이른 정변 (coup) — 적: 환범·조희(또는 하안)·조상
// ════════════════════════════════════════════════════════════════
{id:'IF3-coup-1',year:'245년 · 낙양',title:'무기고 장악',
  synopsis:'기다림을 버리기로 한 밤. "지낭"이라 불린 환범이 조상에게 달려가기 전에 무기고를 쥐어야 한다. 사마사가 사병 삼천을 이끌고 어둠 속에 섰다.',
  scenes:[
    {place:'낙양 · 사마씨 저택 뜰',art:0,cast:[
      {name:'사마의',look:'strategist',at:[42,58]},
      {name:'장춘화',look:'lady',at:[58,56],face:'left'},
      {name:'사마사',look:'infantry'},
      {name:'사마소',look:'civil'}],
    steps:[
      {narrate:'245년 가을밤. 대장군 조상이 병권을 쥐고 노신들을 밀어낸 지 여러 해. 사마의는 더 기다리지 않기로 했다.'},
      {say:'장춘화',line:'늙은 몸으로 칼을 드시겠다니. 병을 칭하고 누워 계실 때가 더 편해 보이셨는데요.'},
      {say:'사마의',line:'누워 있는 동안 남은 날이 줄었소. 힘이 남았을 때 일어나야 아이들에게 짐을 덜 남기지.'},
      {enter:'사마사',at:[24,62],from:'left'},
      {say:'사마사',line:'사병 삼천, 모두 모였습니다. 아무도 소리 내지 않았습니다.'},
      {enter:'사마소',at:[12,66],from:'left'},
      {emote:'사마소',text:'땀'},
      {say:'사마소',line:'…저는 어젯밤 한숨도 못 잤습니다. 형님은 코를 골며 주무시더군요.'},
      {emote:'사마의',text:'…'},
    ]},
    {place:'낙양 · 무기고 앞',art:9,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'사마사',look:'infantry',at:[50,64],face:'left'},
      {name:'장제',look:'civil'},
      {name:'사병',look:'spear',at:[20,68]}],
    steps:[
      {move:'사병',to:[28,66]},
      {enter:'장제',at:[70,60],from:'right'},
      {say:'장제',line:'태위 장제요. 중달, 정말 일을 벌이는구려. 환범이 이미 낌새를 채고 무기고로 사람을 보냈소.'},
      {choice:'사마의',options:[
        {id:'jiang_ji',text:'장제와 함께 태후의 이름으로 명분을 세운다.',reply:'자통(장제), 그대가 서 주면 이 일은 정변이 아니라 바로잡음이 된다.',answer:{speaker:'장제',line:'…조상의 병권만 거둔다면, 나도 함께 서겠소.'},note:'장제 영입(책사) · 첫 턴 방어 태세',
          effects:[{kind:'recruit',name:'장제',unitClass:'strategist'},{kind:'guard'},{kind:'flag',flag:'coup_jiangji'}]},
        {id:'silent',text:'사마사의 사병만으로 소리 없이 친다.',reply:'일을 아는 사람이 적을수록 일은 빨리 끝난다.',answer:{speaker:'사마사',line:'저희 삼천이면 충분합니다.'},note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'},{kind:'flag',flag:'coup_silent'}]},
        {id:'empress',text:'무기고를 쥐거든 곧장 영녕궁의 곽태후부터 찾아뵌다.',reply:'다리보다 궁이 먼저다. 태후의 조서가 있으면 조상은 돌아올 곳이 없다.',note:'다음 전장이 「영녕궁의 문」으로 바뀐다 · 책략 MP +15',
          effects:[{kind:'path',tale:'IF3-coup-2x'},{kind:'insight'},{kind:'flag',flag:'coup_empress'}]},
      ]},
      {emote:'사마사',text:'!'},
    ]},
  ],
  after:[
    {place:'낙양 · 무기고 안',art:9,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마사',look:'infantry',at:[58,62],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'무기고가 사마씨의 손에 들어왔다. 환범은 사로잡혔다.'},
      {say:'사마사',line:'환범이 말하길, 조상은 사냥을 나가 고평릉에 있다 합니다. 황제를 모시고요.'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'조상의 아우 조희가 낙수 부교로 달려갑니다! 다리를 끊고 조상의 본대를 불러들이려 합니다!',unless:'coup_empress'},
      {say:'전령',line:'영녕궁 문을 하안이 막았습니다! 태후를 뵙지 못하게 하려는 겁니다!',when:'coup_empress'},
      {exit:'전령',to:'right'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'IF3-coup-2',year:'245년 · 낙수 부교',title:'낙수 부교',
  synopsis:'조상의 아우 조희가 낙수 부교를 끊으려 한다. 다리가 끊기면 황제를 모신 조상의 본대가 낙양으로 돌아오고, 정변은 역모가 된다.',
  scenes:[
    {place:'낙수 · 부교 북쪽',art:15,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'사마소',look:'civil',at:[22,66]},
      {name:'왕관',look:'infantry'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'새벽 안개가 낙수 위에 깔렸다. 부교 건너편에서 조희의 금군이 도끼를 들고 다가온다.'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'조희가 부교 남쪽 끝에 닿았습니다! 밧줄을 끊기 시작했습니다!'},
      {exit:'전령',to:'right'},
      {enter:'왕관',at:[60,60],from:'right'},
      {say:'왕관',line:'태복 왕관이오. 조희의 진영은 제가 잘 압니다. 저들은 다리를 끊는 데만 정신이 팔려 있소.'},
      {emote:'사마소',text:'!'},
      {say:'사마소',line:'아버님, 이 일이 끝나면 조상을 어찌하실 겁니까. 병사들이 묻습니다.'},
      {move:'사마의',to:[44,60]},
      {choice:'사마의',options:[
        {id:'wang_guan',text:'왕관에게 조희의 진영을 맡긴다.',reply:'적을 아는 자에게 적을 맡긴다.',answer:{speaker:'왕관',line:'다리 밧줄 하나 끊기 전에 끝내겠소.'},note:'왕관 영입(보병) · 척후로 적 한 부대가 나오지 않는다',
          effects:[{kind:'recruit',name:'왕관',unitClass:'infantry'},{kind:'scout'}]},
        {id:'oath',text:'낙수를 가리켜 병권만 거두겠다고 맹세한다.',reply:'조상의 목숨은 거두지 않는다. 낙수가 내 말을 들었다.',answer:{speaker:'사마소',line:'…아버님, 그 맹세 꼭 지키셔야 합니다.'},note:'처음 2턴 사기 상승 · 낙수의 맹세가 남는다',
          effects:[{kind:'rally'},{kind:'flag',flag:'coup_luo_oath'}]},
        {id:'bold',text:'부교 위로 곧장 돌격한다.',reply:'다리가 끊기기 전에, 다리 위에서 끝낸다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
    ]},
  ],
  after:[
    {place:'낙수 · 지켜낸 부교',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마소',look:'civil',at:[24,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'부교는 끊기지 않았다. 조희는 사로잡혀 낙양으로 끌려갔다.'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'조상이 황제를 모시고 고평릉에서 돌아옵니다! 금군을 모두 모아 사마문 앞에 진을 치려 합니다!'},
      {emote:'사마소',text:'땀'},
      {move:'사마의',to:[48,58]},
      {say:'사마의',line:'다리를 지켰으니 조상은 돌아올 수밖에 없다. 오라 하라. 낙양 성문 앞에서 끝낸다.'},
    ]},
  ]},

{id:'IF3-coup-2x',year:'245년 · 낙양 궁성',title:'영녕궁의 문',
  synopsis:'곽태후의 조서를 받으러 영녕궁으로 갔으나, 조상의 심복 하안이 궁문을 막았다. 조서가 없으면 정변은 역모로 기록된다.',
  scenes:[
    {place:'낙양 · 영녕궁 앞',art:13,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'사마사',look:'infantry',at:[22,66]},
      {name:'하안',look:'civil',at:[70,54],face:'left'},
      {name:'궁 호위병',look:'spear',at:[82,60],face:'left'}],
    steps:[
      {narrate:'영녕궁 회랑에 등불이 일렁였다. 문 앞에 분칠한 얼굴의 하안이 섰다.'},
      {say:'하안',line:'태부, 늙고 병드셨다더니 걸음이 빠르시구려. 태후께서는 주무시오. 돌아가시오.'},
      {move:'사마의',to:[46,60]},
      {say:'사마의',line:'평숙(하안), 그대는 노자를 풀이한 학자 아니오. 학자가 왜 창을 든 사람들 뒤에 서 있소.'},
      {emote:'하안',text:'분노'},
      {move:'궁 호위병',to:[74,58]},
      {emote:'사마사',text:'!'},
      {choice:'사마의',options:[
        {id:'gate',text:'궁 뒤편 쪽문으로 사마사를 보낸다.',reply:'하안은 앞문만 본다. 학자는 늘 정면만 본다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
        {id:'eunuch',text:'궁 안의 환관들을 먼저 달래 문을 열게 한다.',reply:'궁문은 밖에서 여는 것이 아니라 안에서 여는 것이다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
        {id:'guard',text:'궁 안에서 피를 보지 않도록 방패를 앞세운다.',reply:'태후 앞에서 칼을 휘두를 수는 없다.',note:'첫 턴 방어 태세 · 처음 2턴 사기 상승',effects:[{kind:'guard'},{kind:'rally'}]},
      ]},
    ]},
  ],
  after:[
    {place:'낙양 · 영녕궁 안뜰',art:5,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'곽태후',look:'lady',at:[64,54],face:'left'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'하안이 물러나고 궁문이 열렸다. 곽태후가 붓을 들었다.'},
      {say:'곽태후',line:'태부, 조상의 병권을 거두라는 조서요. 다만 황제의 숙부들이니 목숨만은 살펴 주시오.'},
      {emote:'사마의',text:'…'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'조상이 조서 소식을 듣고 황제를 모신 채 금군을 몰아 돌아옵니다!'},
      {exit:'전령',to:'right'},
    ]},
  ]},

{id:'coup:boss',year:'245년 · 낙양 성문 앞',title:'낙양의 주인',
  synopsis:'고평릉에서 돌아온 조상이 금군을 모아 낙양 성문 앞에 섰다. 환범의 꾀도, 아우들의 칼도 잃었다. 이 싸움에서 지는 쪽은 역적으로 기록된다.',
  scenes:[
    {place:'낙양 · 사마문 성루',art:8,cast:[
      {name:'사마의',look:'strategist',at:[40,58]},
      {name:'사마사',look:'infantry',at:[24,62]},
      {name:'사마소',look:'civil'},
      {name:'장제',look:'civil'}],
    steps:[
      {narrate:'해 질 무렵, 조상의 금군이 낙양 서쪽 들판을 메웠다. 황제의 수레는 그 한가운데 있었다.'},
      {enter:'사마소',at:[58,62],from:'right'},
      {say:'사마소',line:'조상의 금군이 이만입니다. 우리는 그 반도 되지 않습니다.'},
      {say:'사마사',line:'조상은 싸워 본 적 없는 대장군이다. 이만이 아니라 이만 마리 양이다.'},
      {enter:'장제',at:[72,58],from:'right',when:'coup_jiangji'},
      {say:'장제',line:'중달, 내가 조상에게 서신을 보내 두었소. 병권만 내놓으면 부귀는 지켜 준다고.',when:'coup_jiangji'},
      {emote:'사마의',text:'…'},
    ]},
    {place:'낙양 · 성문 앞 들판',art:16,cast:[
      {name:'사마의',look:'strategist',at:[32,62]},
      {name:'조상',look:'cavalry',at:[72,54],face:'left'},
      {name:'금군 병사',look:'spear',at:[84,60],face:'left'},
      {name:'사병',look:'spear',at:[18,66]}],
    steps:[
      {move:'조상',to:[64,56]},
      {say:'조상',line:'늙은 여우! 병들어 죽을 날만 기다린다더니 이 무슨 짓이냐! 황제께서 여기 계시다!'},
      {say:'사마의',line:'소백(조상), 그대가 황제를 모신 것이 아니라 황제를 끌고 다닌 것이오. 이제 내려놓으시오.'},
      {emote:'조상',text:'땀'},
      {move:'사병',to:[24,64]},
      {choice:'사마의',options:[
        {id:'mercy',text:'조상의 목숨만은 살린다고 금군에 외친다.',reply:'항복하면 산다. 그 한마디가 금군의 창을 내리게 한다.',note:'첫 턴 방어 태세 · 조상을 살린 일이 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'coup_mercy'}]},
        {id:'purge',text:'조상의 삼족을 멸한다고 선포한다.',reply:'뿌리를 남기면 다시 자란다. 오늘 모두 뽑는다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배 · 피의 숙청이 남는다',effects:[{kind:'bold'},{kind:'flag',flag:'coup_purge'}]},
        {id:'sons',text:'사마사와 사마소에게 양 날개를 맡긴다.',reply:'이 일의 끝은 너희가 짊어질 것이다. 지금부터 짊어져라.',answer:{speaker:'사병',line:'공자들을 따르라!'},note:'처음 2턴 사기 상승 · 책략 MP +15',effects:[{kind:'rally'},{kind:'insight'}]},
      ]},
      {exit:'금군 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'낙양 · 성문 앞',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'조상',look:'cavalry',at:[64,60],face:'left'},
      {name:'사마사',look:'infantry',at:[24,64]}],
    steps:[
      {narrate:'조상은 끝내 칼을 내던졌다. 황제의 수레가 낙양 성문을 지났다.'},
      {say:'조상',line:'…부잣집 늙은이로 살 수만 있다면 족하오.',when:'coup_mercy'},
      {say:'조상',line:'낙수에 맹세했다 들었소. 그 맹세를 믿겠소.',when:'coup_luo_oath'},
      {narrate:'그날 밤, 조상과 그 형제들의 목이 낙양 저잣거리에 걸렸다.',when:'coup_purge'},
      {emote:'사마사',text:'…'},
      {move:'사마의',to:[48,60]},
      {exit:'조상',to:'right'},
    ]},
  ]},

{id:'ending:coup',year:'245년 · 낙양',title:'낙양의 주인',
  synopsis:'사마의는 기다림을 버리고 칼을 뽑았다. 낙양은 하룻밤 사이 사마씨의 것이 되었다.',
  scenes:[
    {place:'낙양 · 태부부',art:12,cast:[
      {name:'사마의',look:'strategist',at:[42,58]},
      {name:'사마사',look:'infantry'},
      {name:'사마소',look:'civil'},
      {name:'장춘화',look:'lady',at:[62,56],face:'left'}],
    steps:[
      {narrate:'사마의는 기다림을 버리고 칼을 뽑았다. 낙양은 하룻밤 사이 사마씨의 것이 되었다.'},
      {enter:'사마사',at:[24,62],from:'left'},
      {enter:'사마소',at:[14,66],from:'left'},
      {say:'사마사',line:'아버님, 조정의 백관이 모두 태부부에 인사를 왔습니다. 이제 낙양의 주인은 아버님이십니다.'},
      {say:'장춘화',line:'낙수의 맹세를 지키셨군요. 조상이 살아 있으니 사람들이 덜 두려워합니다.',when:'coup_luo_oath'},
      {say:'사마소',line:'저잣거리의 피가 아직 마르지 않았습니다. 사람들은 아버님을 구원자라 부르면서도 눈을 피합니다.',when:'coup_purge'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'일찍 뽑은 칼은 일찍 녹이 슨다. 너희는 이 칼을 오래 닦아야 할 것이다.'},
      {narrate:'역사는 그를 찬탈자이자 구원자로 함께 기록했다.'},
    ]},
  ]},

// ════════════════════════════════════════════════════════════════
// 하편 가상 · 천하통일 (unify) — 적: 주연·제갈각·손권(또는 전종)·육손
// ════════════════════════════════════════════════════════════════
{id:'IF3-uni-1',year:'241년 · 합비',title:'합비 돌파',
  synopsis:'조정 다툼은 아들들에게 맡기고, 늙은 사마의는 남은 생을 강동에 걸었다. 합비를 넘어 장강으로. 주연이 지키는 강가 요새가 첫 관문이다.',
  scenes:[
    {place:'낙양 · 사마씨 저택 문',art:10,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'사마사',look:'infantry',at:[58,60],face:'left'},
      {name:'사마소',look:'civil'}],
    steps:[
      {narrate:'조상이 조정을 휘두르는 낙양을 뒤로하고, 늙은 태부는 남쪽으로 떠날 채비를 했다.'},
      {say:'사마사',line:'아버님, 조상은 저희가 지켜보겠습니다. 칼을 뽑지는 않겠습니다. 아버님께서 돌아오실 때까지.'},
      {enter:'사마소',at:[74,62],from:'right'},
      {say:'사마소',line:'강동은 물의 땅입니다. 아버님 연세에 배 위에서 겨울을 나시다니요.'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'제갈량은 오장원에서 죽었다. 나도 어디선가 죽을 것이다. 이왕이면 천하가 하나 된 강가였으면 한다.'},
      {exit:'사마소',to:'right'},
    ]},
    {place:'합비 신성 · 군막',art:14,cast:[
      {name:'사마의',look:'strategist',at:[38,60]},
      {name:'왕릉',look:'infantry',at:[60,58],face:'left'},
      {name:'곽회',look:'archer',at:[22,64]},
      {name:'등애',look:'spear'}],
    steps:[
      {say:'왕릉',line:'양주의 왕릉이오. 태부께서 몸소 오시다니. 주연이 강가 요새를 단단히 쌓았소.'},
      {enter:'등애',at:[76,62],from:'right'},
      {say:'등애',line:'애, 애… 등애가 아뢰옵니다. 회수 남북에 둔전을 열면 오만 군이 다섯 해를 먹을 수 있습니다.'},
      {emote:'곽회',text:'?'},
      {choice:'사마의',options:[
        {id:'deng_ai',text:'등애의 둔전책을 쓰고 그를 곁에 둔다.',reply:'군량이 있어야 기다릴 수 있다. 기다릴 수 있어야 이긴다.',answer:{speaker:'등애',line:'처, 천천히… 그러나 반드시 이기게 해 드리겠습니다.'},note:'등애 영입(창병) · 첫 턴 방어 태세',
          effects:[{kind:'recruit',name:'등애',unitClass:'spearman'},{kind:'guard'},{kind:'flag',flag:'uni_tuntian'}]},
        {id:'wang_ling',text:'왕릉의 양주군을 앞세운다.',reply:'양주를 아는 자가 양주의 강을 건넌다.',answer:{speaker:'왕릉',line:'태부의 명이라면 기꺼이.'},note:'왕릉의 양주군이 초록 깃발로 돕는다 · 왕릉에게 공이 쌓인다',
          effects:[{kind:'reinforce',name:'왕릉',unitClass:'infantry',side:'npc'},{kind:'flag',flag:'uni_wangling'}]},
        {id:'bold',text:'요새를 정면으로 들이친다.',reply:'늙은이에게는 시간이 없다. 첫 관문은 빨리 넘는다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {move:'등애',to:[68,62]},
    ]},
  ],
  after:[
    {place:'합비 남쪽 · 강가 요새',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'왕릉',look:'infantry'}],
    steps:[
      {narrate:'주연은 요새를 버리고 강 건너로 물러났다.'},
      {enter:'왕릉',at:[62,60],from:'right',when:'uni_wangling'},
      {say:'왕릉',line:'양주군이 첫 공을 세웠소. 태부, 이 공을 잊지 마시오.',when:'uni_wangling'},
      {emote:'곽회',text:'!'},
      {say:'곽회',line:'유수구에 오의 수군이 모인다 합니다. 제갈근의 아들 제갈각이 지휘한다고요.'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'재주가 넘치는 아이라 들었다. 넘치는 것은 쏟아지게 마련이지.'},
    ]},
  ]},

{id:'IF3-uni-2',year:'242년 · 유수구',title:'유수구 결전',
  synopsis:'재주가 넘치는 제갈각이 유수구에 수군을 모았다. 이 물길을 넘으면 건업이 보인다. 북군은 다시 물 위에서 싸워야 한다.',
  scenes:[
    {place:'유수구 · 북쪽 강둑',art:7,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'곽회',look:'archer',at:[20,66]},
      {name:'왕창',look:'infantry'},
      {name:'위군 병사',look:'spear',at:[58,70],face:'left'}],
    steps:[
      {narrate:'유수구의 물길 위로 오의 누선이 줄지어 섰다. 뱃머리에 젊은 제갈각이 부채를 들었다.'},
      {emote:'위군 병사',text:'땀'},
      {move:'위군 병사',to:[66,70]},
      {enter:'왕창',at:[76,60],from:'right'},
      {say:'왕창',line:'형주의 왕창이오. 강릉에서 배를 끌고 내려왔소. 상류의 물길은 제가 쥐고 있소.'},
      {say:'곽회',line:'건업으로 곧장 가면 손권이 버티고, 상류 무창을 치면 건업의 등이 빕니다.'},
      {emote:'사마의',text:'…'},
      {choice:'사마의',options:[
        {id:'wang_chang',text:'왕창의 형주 수군을 불러 함께 친다.',reply:'물 위의 싸움은 물을 아는 자의 몫이다.',answer:{speaker:'왕창',line:'형주 수군이 앞장서겠소!'},note:'왕창 영입(수군) · 처음 2턴 사기 상승',
          effects:[{kind:'recruit',name:'왕창',unitClass:'navy'},{kind:'rally'},{kind:'flag',flag:'uni_wangchang'}]},
        {id:'upstream',text:'유수구를 넘거든 건업 대신 상류 무창을 먼저 친다.',reply:'머리를 치기 전에 팔을 자른다.',note:'다음 전장이 「무창 상류」로 바뀐다 · 책략 MP +15',effects:[{kind:'path',tale:'IF3-uni-3x'},{kind:'insight'}]},
        {id:'fire',text:'바람을 기다려 불배를 띄운다.',reply:'재주 넘치는 아이는 불을 모른다. 불은 노인이 안다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
      ]},
    ]},
  ],
  after:[
    {place:'유수구 · 연기 낀 물길',art:7,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'제갈각',look:'strategist',at:[70,56],face:'left'},
      {name:'곽회',look:'archer',at:[24,64]}],
    steps:[
      {narrate:'제갈각의 수군이 흩어졌다. 제갈각은 뱃머리에서 사마의를 돌아보았다.'},
      {say:'제갈각',line:'늙은 이리! 숙부(제갈량)가 그대를 끝내 이기지 못한 까닭을 알겠소. 다음에는 내가 이기겠소!'},
      {exit:'제갈각',to:'right'},
      {emote:'곽회',text:'…'},
      {move:'사마의',to:[46,58]},
      {say:'사마의',line:'다음이 있으려면 살아 있어야지. 저 아이는 오래 살지 못할 얼굴이다.'},
    ]},
  ]},

{id:'IF3-uni-3',year:'243년 · 건업',title:'건업 포위',
  synopsis:'벽안자염의 손권이 건업 성벽 위에 섰다. 예순이 넘은 강동의 주인과 예순이 넘은 위의 노신이 마주한다. 한 사람의 이름 아래 천하를 모을 날이 가깝다.',
  scenes:[
    {place:'건업 · 성벽 아래',art:8,cast:[
      {name:'사마의',look:'strategist',at:[36,64]},
      {name:'곽회',look:'archer',at:[20,66]},
      {name:'손권',look:'strategist',at:[64,42],face:'left'},
      {name:'오군 병사',look:'spear',at:[78,46],face:'left'}],
    steps:[
      {narrate:'건업 성벽 위, 푸른 눈에 붉은 수염의 노인이 섰다. 강동을 쉰 해 다스린 손권이었다.'},
      {say:'손권',line:'사마중달! 조조도 조비도 이 강을 넘지 못했다. 늙은 그대가 넘겠다는 것이냐!'},
      {move:'사마의',to:[44,62]},
      {say:'사마의',line:'중모(손권), 조조와 조비는 서둘렀소. 나는 서두르지 않았을 뿐이오. 그래서 여기 있소.'},
      {emote:'손권',text:'분노'},
      {move:'오군 병사',to:[72,46]},
      {emote:'곽회',text:'!'},
      {choice:'사마의',options:[
        {id:'letter',text:'손권에게 항복하면 강동을 맡기겠다는 글을 보낸다.',reply:'강동의 주인을 죽이면 강동이 백 년 운다.',note:'첫 턴 방어 태세 · 손권에게 보낸 글이 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'uni_sunquan_letter'}]},
        {id:'siege',text:'성을 겹겹이 에워싸고 서두르지 않는다.',reply:'건업에는 곡식이 석 달 치뿐이다. 나는 석 달을 기다릴 줄 안다.',note:'책략 MP +15 · 척후로 적 한 부대가 나오지 않는다',effects:[{kind:'insight'},{kind:'scout'}]},
        {id:'bold',text:'성문을 정면으로 친다.',reply:'남은 날이 많지 않다. 오늘 연다.',note:'정면 승부 · 적 정예 1부대 추가, 경험치 1.5배',effects:[{kind:'bold'}]},
      ]},
      {exit:'손권',to:'right'},
    ]},
  ],
  after:[
    {place:'건업 · 열린 성문',art:2,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'손권',look:'strategist'},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'건업의 성문이 열렸다. 그러나 오의 마지막 군은 이미 서쪽으로 빠져나간 뒤였다.'},
      {enter:'손권',at:[64,60],from:'right',when:'uni_sunquan_letter'},
      {say:'손권',line:'그대의 글을 읽었소. 강동 백성을 살려 준다면… 이 늙은이는 무릎을 꿇겠소.',when:'uni_sunquan_letter'},
      {enter:'전령',at:[86,62],from:'right'},
      {say:'전령',line:'육손이 남은 오군을 모아 서릉 강가에 진을 쳤습니다! 마지막 싸움을 하겠다 합니다!'},
      {emote:'사마의',text:'…'},
    ]},
  ]},

{id:'IF3-uni-3x',year:'243년 · 무창',title:'무창 상류',
  synopsis:'건업 대신 상류 무창을 먼저 쳤다. 오의 대장 전종이 무창의 수군을 이끌고 강 위에서 막아선다. 무창을 잃으면 건업은 팔다리를 잃는다.',
  scenes:[
    {place:'무창 · 강 위',art:7,cast:[
      {name:'사마의',look:'strategist',at:[36,62]},
      {name:'곽회',look:'archer',at:[20,66]},
      {name:'전종',look:'infantry',at:[72,54],face:'left'},
      {name:'오군 병사',look:'spear',at:[84,60],face:'left'}],
    steps:[
      {narrate:'장강 상류, 무창. 오의 서쪽 도읍 앞에 전종의 수군이 버티고 섰다.'},
      {say:'전종',line:'건업을 두고 무창으로 오다니. 늙은이가 길을 잃었소?'},
      {move:'사마의',to:[44,60]},
      {say:'사마의',line:'길은 잃지 않았소, 자황(전종). 건업으로 가는 가장 먼 길이 가장 빠른 길일 뿐이오.'},
      {emote:'전종',text:'?'},
      {move:'오군 병사',to:[78,58]},
      {emote:'곽회',text:'!'},
      {choice:'사마의',options:[
        {id:'chain',text:'강 위에 쇠사슬을 걸어 오의 배를 묶는다.',reply:'적벽의 사슬은 불을 불렀다. 이 사슬은 도망길을 막는다.',note:'척후 · 적 한 부대가 나오지 않는다',effects:[{kind:'scout'}]},
        {id:'night',text:'밤에 강을 거슬러 무창 성 밑에 닿는다.',reply:'무창은 건업을 걱정하느라 제 발밑을 보지 않는다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
        {id:'jing_navy',text:'형주 수군을 불러 뒤에서 친다.',reply:'형주의 배는 상류에 있다. 물은 위에서 아래로 흐른다.',note:'형주 수군이 직접 지휘하는 아군으로 합류',effects:[{kind:'reinforce',name:'형주 수군',unitClass:'navy',side:'ally'}]},
      ]},
      {exit:'전종',to:'right'},
    ]},
  ],
  after:[
    {place:'무창 · 강가',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'전령',look:'infantry'}],
    steps:[
      {narrate:'무창이 떨어졌다. 상류를 잃은 건업은 사흘 만에 성문을 열었다.'},
      {enter:'전령',at:[84,62],from:'right'},
      {say:'전령',line:'손권이 건업을 버렸습니다! 육손이 남은 오군을 모아 서릉 강가에 마지막 진을 쳤습니다!'},
      {emote:'곽회',text:'!'},
      {exit:'전령',to:'right'},
      {say:'사마의',line:'이릉의 불을 놓은 그 사람이 마지막에 남았구나. 그럴 줄 알았다.'},
    ]},
  ]},

{id:'unify:boss',year:'244년 · 서릉 강가',title:'마지막 서생',
  synopsis:'강동의 마지막 군을 육손이 이끈다. 이릉에서 유비의 칠백 리 진채를 불태운 서생이다. 그를 꺾으면 백 년 만에 천하가 하나가 된다.',
  scenes:[
    {place:'서릉 · 위군 군영 아침',art:6,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'등애',look:'spear'}],
    steps:[
      {narrate:'244년 봄, 서릉. 장강이 좁아지는 곳에 육손의 마지막 진이 섰다.'},
      {enter:'등애',at:[64,62],from:'right',when:'uni_tuntian'},
      {say:'등애',line:'두, 둔전의 곡식이 넉넉합니다. 한 해를 더 기다려도 굶지 않습니다.',when:'uni_tuntian'},
      {say:'곽회',line:'육손은 이릉에서 일곱 달을 기다렸다가 하룻밤에 불을 놓았습니다. 기다림이라면 그도 압니다.'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'기다림을 아는 자끼리 만났구나. 그렇다면 먼저 움직이는 쪽이 진다.'},
      {move:'곽회',to:[30,62]},
    ]},
    {place:'서릉 · 강가 들판',art:16,cast:[
      {name:'사마의',look:'strategist',at:[32,62]},
      {name:'육손',look:'strategist',at:[72,54],face:'left'},
      {name:'오군 병사',look:'spear',at:[84,60],face:'left'},
      {name:'위군 병사',look:'spear',at:[18,66]}],
    steps:[
      {move:'육손',to:[64,56]},
      {say:'육손',line:'사마중달. 제갈량을 막고, 이제 나를 막으러 왔구려. 그대의 진채는 몇 리요?'},
      {say:'사마의',line:'한 리도 잇지 않았소, 백언. 이릉의 불은 남의 일로 배웠으니.'},
      {emote:'육손',text:'…'},
      {emote:'위군 병사',text:'!'},
      {choice:'사마의',options:[
        {id:'yiling',text:'진채를 띄엄띄엄 세우고 불길을 막을 도랑을 판다.',reply:'불은 이어진 것을 태운다. 잇지 않으면 탈 것이 없다.',note:'첫 턴 방어 태세 · 이릉의 교훈이 남는다',effects:[{kind:'guard'},{kind:'flag',flag:'uni_yiling'}]},
        {id:'respect',text:'육손에게 싸움 뒤 강동 백성을 지키겠다고 약조한다.',reply:'이 서생이 지키려는 것은 손씨가 아니라 강동이다.',answer:{speaker:'육손',line:'…그 약조, 싸움이 끝나도 지키시오.'},note:'처음 2턴 사기 상승 · 육손과의 약조가 남는다',effects:[{kind:'rally'},{kind:'flag',flag:'uni_luxun_respect'}]},
        {id:'ambush',text:'먼저 움직이는 척하고 강가 갈대밭에 복병을 둔다.',reply:'먼저 움직이는 쪽이 진다. 그러니 움직이는 척만 한다.',note:'기습 · 적 전원 체력 80%로 시작',effects:[{kind:'ambush'}]},
      ]},
      {exit:'오군 병사',to:'right'},
    ]},
  ],
  after:[
    {place:'서릉 · 강가',art:15,cast:[
      {name:'사마의',look:'strategist',at:[40,60]},
      {name:'육손',look:'strategist',at:[64,58],face:'left'}],
    steps:[
      {narrate:'육손의 마지막 진이 무너졌다. 서생은 칼 대신 부채를 내려놓았다.'},
      {say:'육손',line:'약조를 지키시오, 중달. 강동은 그대에게 지는 것이지 짓밟히는 것이 아니오.',when:'uni_luxun_respect'},
      {say:'육손',line:'불을 놓을 곳이 없었소. 그대는 내가 본 장수 가운데 가장 참을성이 많았소.',unless:'uni_luxun_respect'},
      {emote:'사마의',text:'…'},
      {move:'육손',to:[56,60]},
      {move:'사마의',to:[48,58]},
      {say:'사마의',line:'백언, 천하가 하나 되었소. 이제 그대도 나도 쉴 수 있겠구려.'},
    ]},
  ]},

{id:'ending:unify',year:'244년 · 건업',title:'천하통일',
  synopsis:'위의 노신은 남은 생을 강동에 걸었다. 건업이 무너진 날, 백 년 만에 천하가 한 사람의 이름 아래 모였다.',
  scenes:[
    {place:'건업 · 강가 성루',art:8,cast:[
      {name:'사마의',look:'strategist',at:[42,58]},
      {name:'곽회',look:'archer',at:[24,64]},
      {name:'사마사',look:'infantry'},
      {name:'손권',look:'strategist'}],
    steps:[
      {narrate:'위의 노신은 남은 생을 강동에 걸었다. 건업이 무너진 날, 백 년 만에 천하가 한 사람의 이름 아래 모였다.'},
      {enter:'사마사',at:[62,60],from:'right'},
      {say:'사마사',line:'아버님, 낙양에서 달려왔습니다. 조정의 백관이 아버님을 맞으러 강가까지 나왔습니다.'},
      {say:'사마사',line:'조상은 아버님의 승전보를 듣고 스스로 병권을 내놓았습니다. 칼을 뽑을 필요가 없었습니다.',unless:'uni_wangling'},
      {say:'사마사',line:'다만 양주의 왕릉이 공을 앞세워 목소리를 높입니다. 언젠가 수춘에서 일이 날지도 모릅니다.',when:'uni_wangling'},
      {enter:'손권',at:[80,58],from:'right',when:'uni_sunquan_letter'},
      {say:'손권',line:'강동 백성은 무사하오. 그대의 글 한 장이 칼 만 자루보다 무거웠소.',when:'uni_sunquan_letter'},
      {emote:'사마의',text:'…'},
      {say:'사마의',line:'제갈량을 막을 때는 기다리는 법을 배웠고, 손권을 이길 때는 끝내는 법을 배웠다. 늦게 배웠구나.'},
      {emote:'곽회',text:'!'},
      {narrate:'제갈량을 막아 낸 손으로 손권을 꺾은 사람 — 그가 사마의였다.'},
    ]},
  ]},
],
extraTales:[
  {id:'IF2-zhi-3x',route:'cao_zhi',replaces:'IF2-zhi-3',title:'장료의 북상',intro:'거짓 서신에 조휴는 엉뚱한 곳에 묶였다. 그러나 조비는 합비의 장료를 불러올렸다. 강동의 아이 울음을 그치게 하던 이름이 업성으로 내달린다.',target:{name:'장료',unitClass:'cavalry'}},
  {id:'IF2-shu-3x',route:'shu',replaces:'IF2-shu-3',title:'신성의 맹달',intro:'촉을 버리고 위로 간 맹달이 상용 신성에서 촉의 등을 노린다. 위에 있었다면 사마의가 여드레 만에 짓밟았을 성을, 이번에는 촉의 장수로 친다.',target:{name:'맹달',unitClass:'infantry'}},
  {id:'IF3-zu-2x',route:'zhi_unify',replaces:'IF3-zu-2',title:'동흥 설전',intro:'건업 앞바다 대신 동흥의 둑을 노렸다. 눈 내리는 제방 위에서 오의 노장 정봉이 갑옷을 벗은 단병을 이끌고 기다린다.',target:{name:'정봉',unitClass:'infantry'}},
  {id:'IF3-zt-2x',route:'zhi_throne',replaces:'IF3-zt-2',title:'옹주의 격문',intro:'조진은 옛 벗과의 정으로 금군을 움직이지 않았다. 대신 하후연의 아들 하후패가 옹주에서 격문을 돌리고 기병을 몰아 낙양으로 내려온다.',target:{name:'하후패',unitClass:'cavalry'}},
  {id:'IF3-sn-2x',route:'shu_north',replaces:'IF3-sn-2',title:'자오곡',intro:'위연의 계책대로 자오곡 험로를 열흘 만에 넘었다. 장안을 지키는 부마 하후무는 촉군이 산을 넘어올 줄 몰랐다.',target:{name:'하후무',unitClass:'cavalry'}},
  {id:'IF3-ss-2x',route:'shu_south',replaces:'IF3-ss-2',title:'독천의 타사대왕',intro:'만안계곡의 은자 맹절이 독천의 길을 일러 주었다. 독룡동의 주인 타사대왕이 네 개의 독 샘 뒤에서 기다린다.',target:{name:'타사대왕',unitClass:'shaman'}},
  {id:'IF3-coup-2x',route:'coup',replaces:'IF3-coup-2',title:'영녕궁의 문',intro:'곽태후의 조서를 받으러 영녕궁으로 갔으나, 조상의 심복 하안이 궁문을 막았다. 조서가 없으면 정변은 역모로 기록된다.',target:{name:'하안',unitClass:'strategist'}},
  {id:'IF3-uni-3x',route:'unify',replaces:'IF3-uni-3',title:'무창 상류',intro:'건업 대신 상류 무창을 먼저 친다. 오의 대장 전종이 무창의 수군을 이끌고 강 위에서 막아선다.',target:{name:'전종',unitClass:'navy'}},
],
endingNotes:[
  {flag:'zhi_burden',line:'업성에서 창을 쥐고 쓰러진 문사들의 비석은, 그 뒤로도 오래 업성 남문 밖에 서 있었다.'},
  {flag:'zhi_yangxiu',line:'계륵의 양수는 재상 곁에서 끝내 목을 지켰다. 입이 가벼운 재사를 쓸 줄 아는 사람이 있었던 것이다.'},
  {flag:'zhi_mandate',line:'허창에서 받은 천자의 조서는, 업성의 봉기를 역모가 아닌 대의로 남게 했다.'},
  {flag:'zhi_cang',line:'수염 노란 조창은 아우를 위해 칼을 들었고, 형제 다툼 속에서도 끝내 형제를 버리지 않았다.'},
  {flag:'zhi_night_raid',line:'어둠 속에서 허저의 진을 친 그 밤은, 업성 봉기의 첫 승리로 노래되었다.'},
  {flag:'zhi_false_letter',line:'조휴를 엉뚱한 곳으로 달리게 한 거짓 서신은, 종친들 사이에 사마의를 향한 의심을 오래 남겼다.'},
  {flag:'zhi_poet_front',line:'진 앞에 섰던 시인 왕은, 그 뒤로 병사의 숨을 노래한 시를 여러 편 남겼다.'},
  {flag:'zhi_spare_pi',line:'안향으로 간 조비는 아우와 시를 주고받으며 늙었다. 콩과 콩대는 끝내 서로를 태우지 않았다.'},
  {flag:'zu_manchong',line:'합비를 열 번 지킨 만총은, 열한 번째에 처음으로 강을 건넜다.'},
  {flag:'zu_dengai',line:'말을 더듬던 둔전관 등애는 강동의 물길을 그린 공으로 이름을 얻었다.'},
  {flag:'zu_fire',line:'장강을 사흘 동안 태운 불은, 강동 사람들에게 오래도록 원망으로 남았다.'},
  {flag:'zu_king_letter',line:'시인 왕의 친서는 강동의 선비들 사이에서 오래 베껴 읽혔다.'},
  {flag:'zu_yiling',line:'진채를 잇지 않은 재상 앞에서, 이릉의 불은 다시 타오르지 못했다.'},
  {flag:'zu_luxun_letter',line:'항복한 육손은 약조대로 강동을 다스리는 붓이 되었다.'},
  {flag:'zt_jiachong',line:'군량길을 끊은 가충은 새 왕조의 공신이 되었으나, 사람들은 그의 꾀를 두려워했다.'},
  {flag:'zt_zhen_friend',line:'금군을 움직이지 않은 조진의 침묵은, 옛 벗에게 보낸 마지막 우정이었다.'},
  {flag:'zt_zhen_spared',line:'두 번 지고 두 번 살아난 조진은, 끝내 새 왕조에 고개를 숙이지 않은 채 고향에서 늙었다.'},
  {flag:'zt_no_blood',line:'피 한 방울 없던 선양은, 훗날 사람들이 이 왕조를 찬탈이라 부르지 못하게 했다.'},
  {flag:'zt_sons',line:'궁정 회랑에서 양 날개를 맡았던 사마사와 사마소는, 그날의 무게를 평생 잊지 않았다.'},
  {flag:'shu_weiyan',line:'반골이라 불린 위연은 위에서 온 책사 아래서만은 한 번도 칼을 거꾸로 들지 않았다.'},
  {flag:'shu_guanyu',line:'관우는 사마의의 말을 따라 강릉에 봉화를 더 세웠고, 그 봉화가 형주를 지켰다.'},
  {flag:'shu_false_letter',line:'양양의 거짓 항복 서신은 법정의 의심을 끝내 다 풀지 못했다.'},
  {flag:'shu_guanping',line:'한수의 둑을 함께 터뜨린 관평은 사마의를 두 번째 스승으로 섬겼다.'},
  {flag:'shu_mercy',line:'번성에서 살려 준 칠군의 항졸 삼만은 형주의 둔전을 일구는 손이 되었다.'},
  {flag:'shu_masu',line:'물 없는 산을 피하라는 말을 들은 마속은, 가정의 비극을 끝내 겪지 않았다.'},
  {flag:'shu_beacon',line:'강릉의 봉화는 여몽의 흰 옷 배를 비췄고, 관우는 맥성으로 가지 않았다.'},
  {flag:'sn_jiangwei',line:'천수에서 버려졌던 강유는 와룡과 총, 두 스승의 군략을 함께 이었다.'},
  {flag:'sn_ziwu',line:'자오곡 열흘의 행군은 위연의 이름을 촉에서 가장 대담한 장수로 남겼다.'},
  {flag:'sn_wangping',line:'글을 몰랐던 왕평은 샘 하나를 지켜 장안 길을 열었다.'},
  {flag:'sn_hill',line:'산 위에 섰던 마속은 그날 샘을 지킨 이들 덕에 살았음을 평생 잊지 않았다.'},
  {flag:'sn_spare_rui',line:'사슴을 쏘지 못한 황제 조예는, 자신을 쏘지 않은 사마의를 원망하지 않았다.'},
  {flag:'ss_fire',line:'반사곡의 불은 사직에는 공이 되었으나, 사마의는 그 불이 제 수명을 깎았다고 말하곤 했다.'},
  {flag:'ss_madai',line:'서량의 마대는 남중의 숲을 기병으로 돈 첫 장수가 되었다.'},
  {flag:'ss_hermit',line:'만안계곡의 은자 맹절은 아우와 촉 사이의 다리가 되었다.'},
  {flag:'ss_guansuo',line:'축융을 사로잡은 관색은 남중에서 관씨의 이름을 이어 갔다.'},
  {flag:'ss_herb',line:'사마랑이 나눈 해엽운향 덕에 독천을 건넌 촉군은 한 사람도 말을 잃지 않았다.'},
  {flag:'ss_seventh',line:'일곱 번 잡혀 일곱 번 풀려난 맹획은, 남인은 다시 배반하지 않는다는 맹세를 지켰다.'},
  {flag:'ss_execute',line:'벤 맹획의 목 하나는 남중의 숲에 백 개의 원한을 남겼다.'},
  {flag:'coup_jiangji',line:'태위 장제는 정변에 명분을 세웠으나, 끝내 지키지 못한 약속이 있을까 늘 두려워했다.'},
  {flag:'coup_silent',line:'소리 없이 움직인 사병 삼천의 밤은, 사마사의 이름을 낙양에 처음 알렸다.'},
  {flag:'coup_empress',line:'곽태후의 조서는 이른 정변을 역모가 아닌 바로잡음으로 남게 했다.'},
  {flag:'coup_luo_oath',line:'낙수를 가리켜 한 맹세는 지켜졌고, 사람들은 사마의의 말을 다시 믿기 시작했다.'},
  {flag:'coup_mercy',line:'목숨을 건진 조상은 부잣집 늙은이로 살다 조용히 죽었다.'},
  {flag:'coup_purge',line:'낙양 저잣거리에 걸린 조씨 형제의 목은, 사마씨의 이름에 오래도록 피 냄새를 남겼다.'},
  {flag:'uni_tuntian',line:'등애의 둔전은 통일 뒤에도 회수 남북을 먹여 살렸다.'},
  {flag:'uni_wangling',line:'공을 앞세운 왕릉은 끝내 수춘에서 일을 일으켰고, 사마씨는 또 한 번 칼을 들어야 했다.'},
  {flag:'uni_wangchang',line:'형주 수군을 이끈 왕창은 통일된 천하의 첫 수군 도독이 되었다.'},
  {flag:'uni_sunquan_letter',line:'항복한 손권은 강동을 맡아 여생을 마쳤고, 강동 사람들은 그를 마지막 주인으로 기억했다.'},
  {flag:'uni_yiling',line:'진채를 잇지 않은 사마의 앞에서, 육손의 불은 끝내 타오르지 못했다.'},
  {flag:'uni_luxun_respect',line:'약조를 받은 육손은 통일된 천하에서 강동 백성을 지키는 관리로 늙었다.'},
],
};
export default pack;
