import {describe,it,expect,vi} from 'vitest';
import {newDuel,duelRound,type DuelAction} from '../src/duel.ts';
import {Session,chapters} from '../src/session.ts';
import {freshCampaign,award,equipSlot,equippedItems,deployment,readCampaign,writeCampaign} from '../src/progression.ts';
import {availableStrategies} from '../src/officers.ts';
import {estimatePhysical,decide} from '../../core/src/index.ts';
const duel=(stat=60)=>newDuel('duel',{id:'a',name:'아군',stat},{id:'b',name:'적군',stat:60});
describe('five round duels and debates',()=>{
 it('requires energy, rejects invalid moves, and ends exactly on the fifth choice',()=>{const d=duel();expect(duelRound(d,'special')).toBe(false);expect(d.round).toBe(0);for(const a of ['rally','special','guard','attack','attack'] as DuelAction[])expect(duelRound(d,a)).toBe(true);expect(d.round).toBe(5);expect(d.result).toBeDefined();expect(duelRound(d,'attack')).toBe(false);expect(d.history).toHaveLength(5);});
 it('scales damage with stats and reduces incoming damage through guard',()=>{const weak=duel(30),strong=duel(90),guard=duel(30);duelRound(weak,'attack');duelRound(strong,'attack');duelRound(guard,'guard');expect(strong.history[0]!.dealt).toBeGreaterThan(weak.history[0]!.dealt);expect(guard.history[0]!.taken).toBeLessThan(weak.history[0]!.taken);});
 it('replays and undoes mid-debate without losing choices',()=>{
   const s=new Session(7,'normal',215,'survival',4);let started=false;
   for(let i=0;i<300&&!started&&s.state.outcome==='ongoing';i++){
     const st=s.state,u=st.living(st.currentSide).find(u=>!u.hasActed);
     if(!u||!['player','ally'].includes(st.currentSide)){s.tick();continue;}
     const challenge=()=>{const enemy=st.living('enemy').find(e=>Math.abs(e.pos.x-u.pos.x)+Math.abs(e.pos.y-u.pos.y)<=3);if(enemy&&!u.hasActed&&u.id==='sima_yi')started=s.act({kind:'item',unit:u.id,item:'debate',target:enemy.id}).ok;};
     challenge();if(started)break;
     for(const cmd of decide(st,u)){if(cmd.kind==='move'&&cmd.to.x===u.pos.x&&cmd.to.y===u.pos.y)continue;s.act(cmd);challenge();if(started)break;}
     if(!started&&!u.hasActed)s.act({kind:'wait',unit:u.id});
   }
   expect(started).toBe(true);expect(s.act({kind:'endPhase'}).ok).toBe(false);expect(s.act({kind:'item',unit:'sima_yi',item:'duel-round:rally'}).ok).toBe(true);const loaded=Session.load(s.save());expect(loaded.activeDuel).toEqual(s.activeDuel);expect(loaded.undo()).toBe(true);expect(loaded.activeDuel?.round).toBe(0);
 });
 it.each(['duel','debate'] as const)('resolves %s into battle HP and one action',kind=>{const s=new Session(7,'normal',215,'survival',4),u=s.state.get('sima_yi'),enemy=s.state.living('enemy')[0]!;enemy.pos={x:u.pos.x+1,y:u.pos.y};expect(s.act({kind:'item',unit:u.id,item:kind,target:enemy.id}).ok).toBe(true);expect(s.activeDuel?.player.stat).toBe(kind==='debate'?u.stats.intellect:30+u.level);for(const action of ['rally','special','guard','attack','attack'])expect(s.act({kind:'item',unit:u.id,item:'duel-round:'+action}).ok).toBe(true);expect(s.activeDuel).toBeNull();expect(s.lastDuel?.round).toBe(5);expect(u.hasActed).toBe(true);expect(u.hp).toBeLessThan(u.stats.maxHp);expect(enemy.hp).toBeLessThan(enemy.stats.maxHp);});
});
describe('equipment, traits, spells and castle siege',()=>{
 it('preserves the paid escape beside the new Luoyang gate',()=>{const s=new Session(0,'normal',215,'survival',4),st=s.state;st.get('sima_yi').pos={x:6,y:10};st.get('sima_lang').pos={x:7,y:10};expect(s.act({kind:'wait',unit:'sima_yi'}).ok).toBe(true);if(st.activeDialogue==='bribe')expect(s.act({kind:'choose',nodeId:'bribe',optionId:'pay'}).ok).toBe(true);expect(st.activeDialogue).toBe('gate_payment');expect(s.act({kind:'choose',nodeId:'gate_payment',optionId:'pay_gate'}).ok).toBe(true);expect(st.outcome).toBe('victory');expect(s.funds).toBe(1000);});
 it('recovers MP on the next turn and increases Cao Zhen physical damage',()=>{const s=new Session(7,'normal',215,'survival',4),st=s.state,u=st.get('sima_yi'),cao=st.get('cao_zhen'),e=st.living('enemy')[0]!;u.mp=0;for(let i=0;i<4;i++)s.battle.endPhase();expect(u.mp).toBe(3);const enhanced=estimatePhysical(cao,e,st.map);cao.traits=cao.traits.filter(t=>t!=='caoVanguard');expect(enhanced).toBeGreaterThan(estimatePhysical(cao,e,st.map));});
 it('keeps three slots unique and persists them across reload',()=>{const c=freshCampaign();for(const stage of ['S1-01','S1-02'])award(c,stage,'normal',[],[1]);expect(equipSlot(c,'sima_yi','weapon','sevenstar')).toBe(true);expect(equipSlot(c,'sima_yi','armor','ironArmor')).toBe(true);expect(equipSlot(c,'sima_yi','accessory','taiping')).toBe(true);expect(equippedItems(c,'sima_yi')).toHaveLength(3);expect(equipSlot(c,'sima_yi','armor','sevenstar')).toBe(false);expect(equipSlot(c,'sima_lang','weapon','sevenstar')).toBe(true);expect(equippedItems(c,'sima_yi')).not.toContain('sevenstar');const memory=new Map<string,string>();vi.stubGlobal('localStorage',{setItem:(k:string,v:string)=>memory.set(k,v),getItem:(k:string)=>memory.get(k)??null});writeCampaign(c);expect(readCampaign().loadouts).toEqual(c.loadouts);vi.unstubAllGlobals();});
 it('applies all equipped stat bonuses and the general-specific trait',()=>{const c=freshCampaign();award(c,'S1-01','normal',[],[1]);award(c,'S1-02','normal',[],[1]);const base=new Session(0,'normal',215,'survival',4,deployment(c));equipSlot(c,'sima_yi','weapon','sevenstar');equipSlot(c,'sima_yi','armor','ironArmor');equipSlot(c,'sima_yi','accessory','taiping');const s=new Session(0,'normal',215,'survival',4,deployment(c)),a=s.state.get('sima_yi'),b=base.state.get('sima_yi');expect(a.stats.attack-b.stats.attack).toBe(4);expect(a.stats.defense-b.stats.defense).toBe(2);expect(a.stats.maxHp-b.stats.maxHp).toBe(12);expect(a.traits).toContain('simaPatience');expect(Session.load(s.save()).state.snapshot()).toEqual(s.state.snapshot());});
 it('unlocks the full spell list progressively',()=>{expect(availableStrategies(1)).toEqual(['fire']);expect(availableStrategies(5)).toEqual(['fire','windDragon','bind']);expect(availableStrategies(20)).toHaveLength(7);const d=deployment(freshCampaign());d.levels.sima_yi=10;expect(new Session(7,'normal',215,'survival',4,d).state.get('sima_yi').strategies).toEqual(availableStrategies(10));});
 it.each([0,1,2,6])('forces a controllable ram and HP structures in castle chapter %i',chapter=>{const s=new Session(chapter,'normal',215,'survival',4,deployment(freshCampaign()));expect(s.state.living('ally').some(u=>u.unitClass==='ram')).toBe(true);expect(s.state.living().some(u=>u.id.startsWith('gate_')&&u.hp>0)).toBe(true);expect(s.state.living().some(u=>u.id.startsWith('tower_')&&u.hp>0&&u.range[1]>1)).toBe(true);});
 it('gives rams a real attack bonus against structures, not ordinary soldiers',()=>{const s=new Session(1,'normal',215,'survival',4),u=s.state.get('siege_crew'),gate=s.state.get('gate_33_12');u.pos={x:32,y:12};const enhanced=estimatePhysical(u,gate,s.state.map);u.traits=[];expect(enhanced).toBeGreaterThan(estimatePhysical(u,gate,s.state.map)*2);});
});
