import {troopAdvice} from './troop-tactics.ts';
import {troopRoles} from './troops.ts';
import {expeditions,canExpedition,storyWins} from './expeditions.ts';
import type {Unit} from '../../core/src/index.ts';
import {treasures,treasurePowerText,treasureInfo,gearNames,equippedItems,deployment,type Campaign,type GearSlot} from './progression.ts';
import {officerFeatures,allStrategies,strategyHint,talentTree,martialPower} from './officers.ts';
import {classNames,unitName} from './battlefield.ts';
export function treasureIcon(id:string){const i=treasureInfo(id).icon,row=Math.floor(i/6),edges=[0,150,306,458,610,764,919,1072,1228,1387,1619],top=edges[row]!,height=edges[row+1]!-top;return `<i class="treasure-icon" style="background-size:600% ${1619/height*100}%;background-position:${i%6/5*100}% ${top/(1619-height)*100}%"></i>`;}
export function campMarkup(c:Campaign,units:Unit[],selected:string,filter:string,inspect:string,portrait:(u:Unit)=>string){
 const u=units.find(x=>x.id===selected)??units[0]!,feature=officerFeatures[u.id],owned=equippedItems(c,u.id),item=treasures.find(t=>t.id===inspect);
 return `<div class="camp-workbench"><section class="camp-roster"><div class="section-label">출진 부대 <span>${units.length}명 · 시나리오 편성</span></div><div class="officer-grid">${units.map(x=>`<button data-officer="${x.id}" class="officer-card ${x.id===u.id?'chosen':''}">${portrait(x)}<strong>${unitName(x)}</strong><small>Lv.${x.level} · ${classNames[x.unitClass]}</small><em>${x.unitClass==='ram'?'공성 필수':x.side==='player'?'본대 필수':'지원 부대'}</em></button>`).join('')}</div><p class="muted">장수를 선택해 능력·보물·고유특성을 정비하세요. 필수 장수와 공성대는 제외할 수 없습니다.</p></section>
 <section class="camp-detail"><div class="section-label">부대 정보 <span>${classNames[u.unitClass]}</span></div><div class="camp-hero">${portrait(u)}<div><h3>${unitName(u)}</h3><p>Lv.${u.level} · 무력 ${martialPower(u)}</p><p>HP ${u.hp} / MP ${u.mp}</p></div></div><div class="camp-stats">${[['공격',u.stats.attack],['방어',u.stats.defense],['지력',u.stats.intellect],['정신',u.stats.spirit],['민첩',u.stats.agility],['이동',u.stats.movement]].map(([k,v])=>`<span>${k}<b>${v}</b></span>`).join('')}</div><div class="troop-tactic-card"><b>병종 운용 · 사거리 ${u.range[0]}~${u.range[1]}</b><p>${troopAdvice[u.unitClass]}</p></div><h4>장수 고유특성 · 성장의 증표</h4>${feature?talentTree(u.id,u.level,deployment(c,true).growth!).map(t=>`<p class="feature-card ${t.ready?'':'locked'}"><b>${t.ready?'◆':'◇'} ${t.name}</b> · ${t.ready?'해금':'잠김'}<br>${t.description}<br><small>${t.requirement}</small></p>`).join(''):`<p class="feature-card">${troopRoles[u.unitClass]?.role??(u.unitClass==='ram'?'공성 충격 · 구조물 피해 3배':'병종 전문화 · 이동/사거리/지형 상성')}</p>`}<div class="gear-slots">${(Object.keys(gearNames) as GearSlot[]).map(slot=>{const id=owned.find(id=>treasureInfo(id).slot===slot);return `<div><small>${gearNames[slot]}</small>${id?treasureIcon(id):'<i class="empty-slot">＋</i>'}<span>${treasures.find(t=>t.id===id)?.name??'미장착'}</span>${id?`<button data-unequip="${slot}">해제</button>`:''}</div>`;}).join('')}</div>${u.strategies.length?`<h4>책략 습득</h4><div class="strategy-tree">${allStrategies.filter(s=>!troopRoles[u.unitClass]||troopRoles[u.unitClass]!.spells.includes(s.id)).map(s=>`<span title="${strategyHint(s.id)}" class="${u.strategies.includes(s.id)?'learned':'locked'}">Lv.${s.id==='mend'&&troopRoles[u.unitClass]?1:s.level} ${s.name} · ${s.mpCost} MP</span>`).join('')}</div>`:''}</section></div>
 <section class="treasury"><div class="section-label">보물 도감 <span>${c.treasures.length}/${treasures.length} 보유 · 부위별 1점</span></div><div class="treasury-filters">${[['all','전체'],...Object.entries(gearNames)].map(([id,name])=>`<button data-gear-filter="${id}" class="${filter===id?'active':''}">${name}</button>`).join('')}</div><div class="treasury-body"><div class="treasure-grid">${treasures.filter(t=>filter==='all'||treasureInfo(t.id).slot===filter).map(t=>{const m=treasureInfo(t.id),has=c.treasures.includes(t.id);return `<button data-treasure="${t.id}" class="treasure-tile grade-${m.grade} ${has?'':'unowned'} ${t.id===inspect?'chosen':''}" aria-label="${t.name} · ${m.rarity} · ${has?'보유':'미보유'}">${treasureIcon(t.id)}<strong>${t.name}</strong><small>${'★'.repeat(m.grade)} ${has?'':'· 잠김'}</small></button>`;}).join('')}</div><div class="treasure-description">${item?`${treasureIcon(item.id)}<h3>${item.name}</h3><p>${treasureInfo(item.id).rarity} · ${gearNames[treasureInfo(item.id).slot]}</p><p>${item.effect}</p><p class="treasure-unique"><b>고유 효과</b><br>${treasurePowerText(item.id)}</p><small>${item.description}</small><p>입수: ${item.quest?(expeditions.find(m=>m.id===item.quest)?.name??item.quest)+' · '+(canExpedition(c,item.quest)?'도전 가능':'본편 '+(expeditions.find(m=>m.id===item.quest)?.requires??0)+'승 필요 · 현재 '+storyWins(c)+'승'):item.stage+' 첫 승리'}</p><button id="equip-treasure" ${c.treasures.includes(item.id)&&u.side==='player'?'':'disabled'}>${unitName(u)}에게 장착</button>`:'보물을 선택하면 효과와 입수처가 표시됩니다.'}</div></div><small>같은 보물은 한 장수만 사용할 수 있습니다. 보물 인연 외전을 완료하면 잠긴 보물을 해금합니다.</small></section>`;
}
