import type {UnitClass} from '../../core/src/index.ts';

/** 칸 쓰임새: 시트마다 2·3열이 뜻하는 동작이 다르다. attack은 [준비, 내지름], walk는 [내딛음, 디딤] 칸 번호. */
export type PaintedFrames={attack:[number,number];walk:[number,number];cast:number;hit:number};
export const STRIDE:PaintedFrames={attack:[1,1],walk:[2,0],cast:1,hit:3};   // 2열 공격 · 3열 걷기(보병·등갑병·상병)
export const THRUST:PaintedFrames={attack:[1,2],walk:[2,0],cast:1,hit:3};   // 2열 준비 · 3열 내지름(걷기 겸용: 창병·기병)
export const SHOOT:PaintedFrames={attack:[1,2],walk:[0,0],cast:2,hit:3};    // 2열 겨눔 · 3열 쏨 · 걷기는 대기 칸(궁병·노병)
export const CASTER:PaintedFrames={attack:[1,2],walk:[0,0],cast:2,hit:3};   // 2열 책 들기 · 3열 부채 휘두름(책사·풍수사)
export const RUN:PaintedFrames={attack:[2,2],walk:[1,0],cast:2,hit:3};      // 2열 달림(걷기) · 3열 공격(자객·등갑병)
/** 차트 낱장 시트: 0 대기 · 1 준비(젖힘) · 2 공격(내디딤) · 3 피격. 걷기는 대기·준비를 번갈아. */
export const POSE:PaintedFrames={attack:[1,2],walk:[0,1],cast:1,hit:3};
export const CHARGE:PaintedFrames={attack:[1,2],walk:[1,0],cast:2,hit:3};   // 2열 질주(걷기·준비) · 3열 찌르기(기병)
/** Dedicated art includes all three evolutions; never recolor another troop into these classes. */
/** union: 칸 안의 떨어진 조각(투석기와 병사, 떠도는 부적)을 한 프레임으로 합쳐 자른다. 정리 도구로 짠 시트는 모두 켠다. */
export const paintedTroopSheets=[
  {id:'rattan-v3',url:'troops-rattan-v3.png',rows:3,frames:RUN,union:true},
  {id:'elephant-v1',url:'troops-elephant-v1.png',rows:3,frames:STRIDE},
  {id:'infantry-v2',url:'troops-infantry-v2.png',rows:3,frames:RUN,union:true},
  {id:'spearman-v2',url:'troops-spearman-v2.png',rows:3,frames:THRUST,union:true},
  {id:'archer-v1',url:'troops-archer-v1.png',rows:3,frames:SHOOT,union:true},
  {id:'cavalry-v2',url:'troops-cavalry-v2.png',rows:3,frames:CHARGE,union:true},
  {id:'assassin-v1',url:'troops-assassin-v1.png',rows:3,frames:RUN,union:true},
  {id:'slinger-v1',url:'troops-slinger-v1.png',rows:3,frames:SHOOT,union:true},
  {id:'shaman-v1',url:'troops-shaman-v1.png',rows:3,frames:CASTER,union:true},
  {id:'maiden-v1',url:'troops-maiden-v1.png',rows:3,frames:CASTER,union:true},
  {id:'heavycav-v1',url:'troops-heavycav-v1.png',rows:3,frames:CHARGE,union:true},
  {id:'xiliang-v1',url:'troops-xiliang-v1.png',rows:3,frames:CHARGE,union:true},
  {id:'crossbow-v1',url:'troops-crossbow-v1.png',rows:3,frames:SHOOT,union:true},
  {id:'strategist-v1',url:'troops-strategist-v1.png',rows:3,frames:CASTER,union:true},
  {id:'fengshui-v1',url:'troops-fengshui-v1.png',rows:3,frames:CASTER,union:true},
  {id:'horsearcher-v1',url:'troops-horsearcher-v1.png',rows:3,frames:CHARGE,union:true},
  {id:'taoist-v1',url:'troops-taoist-v1.png',rows:3,frames:CASTER,union:true},
  {id:'ram-v1',url:'troops-ram-v1.png',rows:3,frames:CHARGE,union:true},
  {id:'engineer-v1',url:'troops-engineer-v1.png',rows:3,frames:SHOOT,union:true},
  {id:'navy-v1',url:'troops-navy-v1.png',rows:3,frames:SHOOT,union:true},
  // 병종 차트에서 잘라 낸 낱장을 기울여 만든 4동작 시트(대기·준비·공격·피격)
  {id:'chart-sword',url:'troops-chart-sword.png',rows:5,frames:POSE,union:true},
  {id:'chart-lord',url:'troops-chart-lord.png',rows:4,frames:POSE,union:true},
  {id:'chart-commander',url:'troops-chart-commander.png',rows:4,frames:POSE,union:true},
  {id:'chart-dancer',url:'troops-chart-dancer.png',rows:4,frames:POSE,union:true},
  {id:'chart-mountaincav',url:'troops-chart-mountaincav.png',rows:4,frames:POSE,union:true},
  {id:'chart-valiantcav',url:'troops-chart-valiantcav.png',rows:4,frames:POSE,union:true},
  {id:'chart-chariot',url:'troops-chart-chariot.png',rows:4,frames:POSE,union:true},
  {id:'chart-siegetower',url:'troops-chart-siegetower.png',rows:4,frames:POSE,union:true},
  {id:'chart-prince',url:'troops-chart-prince.png',rows:4,frames:POSE,union:true},
  {id:'chart-supply',url:'troops-chart-supply.png',rows:4,frames:POSE,union:true},
  {id:'chart-nanman',url:'troops-chart-nanman.png',rows:3,frames:POSE,union:true},
  {id:'chart-gaema',url:'troops-chart-gaema.png',rows:3,frames:POSE,union:true},
  {id:'chart-halberdcav',url:'troops-chart-halberdcav.png',rows:2,frames:POSE,union:true},
  {id:'chart-wheelsage',url:'troops-chart-wheelsage.png',rows:2,frames:POSE,union:true},
  {id:'chart-yellow',url:'troops-chart-yellow.png',rows:4,frames:POSE,union:true},
  {id:'chart-north',url:'troops-chart-north.png',rows:2,frames:POSE,union:true},
  {id:'chart-special',url:'troops-chart-special.png',rows:4,frames:POSE,union:true},
  {id:'chart-fourth',url:'troops-chart-fourth.png',rows:9,frames:POSE,union:true},
  {id:'chart-monk',url:'troops-chart-monk.png',rows:3,frames:POSE,union:true},
  {id:'chart-bandit',url:'troops-chart-bandit.png',rows:3,frames:POSE,union:true},
  {id:'chart-catapult',url:'troops-chart-catapult.png',rows:3,frames:POSE,union:true},
] as const;
export const paintedFrames=(sheet:string):PaintedFrames=>paintedTroopSheets.find(s=>s.id===sheet)?.frames??STRIDE;
export const paintedTroopArt:Partial<Record<UnitClass,{sheet:string;row:number;rows:number}>>={
  rattan:{sheet:'rattan-v3',row:0,rows:3},
  rattanElite:{sheet:'rattan-v3',row:1,rows:3},
  wuguoRattan:{sheet:'rattan-v3',row:2,rows:3},
  elephant:{sheet:'elephant-v1',row:0,rows:3},
  warElephant:{sheet:'elephant-v1',row:1,rows:3},
  elephantKing:{sheet:'elephant-v1',row:2,rows:3},
  infantry:{sheet:'infantry-v2',row:0,rows:3},
  shieldGuard:{sheet:'infantry-v2',row:1,rows:3},
  royalGuard:{sheet:'infantry-v2',row:2,rows:3},
  spearman:{sheet:'spearman-v2',row:0,rows:3},
  pikeman:{sheet:'spearman-v2',row:1,rows:3},
  halberdier:{sheet:'spearman-v2',row:2,rows:3},
  archer:{sheet:'archer-v1',row:0,rows:3},
  longbow:{sheet:'archer-v1',row:1,rows:3},
  sharpshooter:{sheet:'archer-v1',row:2,rows:3},
  cavalry:{sheet:'cavalry-v2',row:0,rows:3},
  lancer:{sheet:'cavalry-v2',row:1,rows:3},
  tigerRider:{sheet:'cavalry-v2',row:2,rows:3},
  assassin:{sheet:'assassin-v1',row:0,rows:3},
  phantom:{sheet:'assassin-v1',row:1,rows:3},
  wraith:{sheet:'assassin-v1',row:2,rows:3},
  slinger:{sheet:'slinger-v1',row:0,rows:3},
  hurler:{sheet:'slinger-v1',row:1,rows:3},
  boulderCorps:{sheet:'slinger-v1',row:2,rows:3},
  shaman:{sheet:'shaman-v1',row:0,rows:3},
  warlock:{sheet:'shaman-v1',row:1,rows:3},
  demonKing:{sheet:'shaman-v1',row:2,rows:3},
  maiden:{sheet:'maiden-v1',row:0,rows:3},
  priestess:{sheet:'maiden-v1',row:1,rows:3},
  celestial:{sheet:'maiden-v1',row:2,rows:3},
  heavyCav:{sheet:'heavycav-v1',row:0,rows:3},
  ironCav:{sheet:'heavycav-v1',row:1,rows:3},
  ironPagoda:{sheet:'heavycav-v1',row:2,rows:3},
  xiliang:{sheet:'xiliang-v1',row:0,rows:3},
  feixiong:{sheet:'xiliang-v1',row:1,rows:3},
  liangzhouIron:{sheet:'xiliang-v1',row:2,rows:3},
  crossbow:{sheet:'crossbow-v1',row:0,rows:3},
  repeater:{sheet:'crossbow-v1',row:1,rows:3},
  greatBow:{sheet:'crossbow-v1',row:2,rows:3},
  strategist:{sheet:'strategist-v1',row:0,rows:3},
  tactician:{sheet:'strategist-v1',row:1,rows:3},
  mastermind:{sheet:'strategist-v1',row:2,rows:3},
  fengshui:{sheet:'fengshui-v1',row:0,rows:3},
  sage:{sheet:'fengshui-v1',row:1,rows:3},
  immortal:{sheet:'fengshui-v1',row:2,rows:3},
  horseArcher:{sheet:'horsearcher-v1',row:0,rows:3},
  nomad:{sheet:'horsearcher-v1',row:1,rows:3},
  whiteHorse:{sheet:'horsearcher-v1',row:2,rows:3},
  taoist:{sheet:'taoist-v1',row:0,rows:3},
  stormSage:{sheet:'taoist-v1',row:1,rows:3},
  thunderGod:{sheet:'taoist-v1',row:2,rows:3},
  ram:{sheet:'ram-v1',row:0,rows:3},
  ironRam:{sheet:'ram-v1',row:1,rows:3},
  cloudRam:{sheet:'ram-v1',row:2,rows:3},
  engineer:{sheet:'engineer-v1',row:0,rows:3},
  sapper:{sheet:'engineer-v1',row:1,rows:3},
  masterBuilder:{sheet:'engineer-v1',row:2,rows:3},
  swordsman:{sheet:'chart-sword',row:0,rows:5},
  knightErrant:{sheet:'chart-sword',row:1,rows:5},
  swordArtist:{sheet:'chart-sword',row:2,rows:5},
  swordMaster:{sheet:'chart-sword',row:3,rows:5},
  swordSaint:{sheet:'chart-sword',row:4,rows:5},
  lord:{sheet:'chart-lord',row:0,rows:4},
  hegemon:{sheet:'chart-lord',row:1,rows:4},
  sovereign:{sheet:'chart-lord',row:2,rows:4},
  sonOfHeaven:{sheet:'chart-lord',row:3,rows:4},
  commander:{sheet:'chart-commander',row:0,rows:4},
  grandCommander:{sheet:'chart-commander',row:1,rows:4},
  marshal:{sheet:'chart-commander',row:2,rows:4},
  heavenCommander:{sheet:'chart-commander',row:3,rows:4},
  dancer:{sheet:'chart-dancer',row:0,rows:4},
  songstress:{sheet:'chart-dancer',row:1,rows:4},
  beauty:{sheet:'chart-dancer',row:2,rows:4},
  heavenDancer:{sheet:'chart-dancer',row:3,rows:4},
  mountainCav:{sheet:'chart-mountaincav',row:0,rows:4},
  scoutCav:{sheet:'chart-mountaincav',row:1,rows:4},
  raidCav:{sheet:'chart-mountaincav',row:2,rows:4},
  pegasusCav:{sheet:'chart-mountaincav',row:3,rows:4},
  valiantCav:{sheet:'chart-valiantcav',row:0,rows:4},
  dragonCav:{sheet:'chart-valiantcav',row:1,rows:4},
  stormCav:{sheet:'chart-valiantcav',row:2,rows:4},
  heavenCav:{sheet:'chart-valiantcav',row:3,rows:4},
  lightChariot:{sheet:'chart-chariot',row:0,rows:4},
  assaultChariot:{sheet:'chart-chariot',row:1,rows:4},
  heavyChariot:{sheet:'chart-chariot',row:2,rows:4},
  divineChariot:{sheet:'chart-chariot',row:3,rows:4},
  siegeTower:{sheet:'chart-siegetower',row:0,rows:4},
  jinglan:{sheet:'chart-siegetower',row:1,rows:4},
  heavyJinglan:{sheet:'chart-siegetower',row:2,rows:4},
  divineJinglan:{sheet:'chart-siegetower',row:3,rows:4},
  crownPrince:{sheet:'chart-prince',row:0,rows:4},
  royalPrince:{sheet:'chart-prince',row:1,rows:4},
  emperor:{sheet:'chart-prince',row:2,rows:4},
  heavenEmperor:{sheet:'chart-prince',row:3,rows:4},
  transport:{sheet:'chart-supply',row:0,rows:4},
  baggageTrain:{sheet:'chart-supply',row:1,rows:4},
  woodenOx:{sheet:'chart-supply',row:2,rows:4},
  divineOx:{sheet:'chart-supply',row:3,rows:4},
  nanmanRider:{sheet:'chart-nanman',row:0,rows:3},
  nanmanBeast:{sheet:'chart-nanman',row:1,rows:3},
  nanmanFoot:{sheet:'chart-nanman',row:2,rows:3},
  gaemaWarrior:{sheet:'chart-gaema',row:0,rows:3},
  gaemaCaptain:{sheet:'chart-gaema',row:1,rows:3},
  whiteTigerCav:{sheet:'chart-gaema',row:2,rows:3},
  halberdCav:{sheet:'chart-halberdcav',row:0,rows:2},
  heavyHalberdCav:{sheet:'chart-halberdcav',row:1,rows:2},
  wheelSage:{sheet:'chart-wheelsage',row:0,rows:2},
  fanSage:{sheet:'chart-wheelsage',row:1,rows:2},
  yellowTurban:{sheet:'chart-yellow',row:0,rows:4},
  ytArcher:{sheet:'chart-yellow',row:1,rows:4},
  ytSpear:{sheet:'chart-yellow',row:2,rows:4},
  ytBrawler:{sheet:'chart-yellow',row:3,rows:4},
  northFoot:{sheet:'chart-north',row:0,rows:2},
  northRider:{sheet:'chart-north',row:1,rows:2},
  palanquin:{sheet:'chart-special',row:0,rows:4},
  baguaChariot:{sheet:'chart-special',row:1,rows:4},
  flyingBlade:{sheet:'chart-special',row:2,rows:4},
  bashuRepeater:{sheet:'chart-special',row:3,rows:4},
  ironInfantry:{sheet:'chart-fourth',row:0,rows:9},
  divineSpear:{sheet:'chart-fourth',row:1,rows:9},
  divineStrategist:{sheet:'chart-fourth',row:2,rows:9},
  heavenTaoist:{sheet:'chart-fourth',row:3,rows:9},
  fistSaint:{sheet:'chart-fourth',row:4,rows:9},
  chieftain:{sheet:'chart-fourth',row:5,rows:9},
  admiral:{sheet:'chart-fourth',row:6,rows:9},
  wujiHeavyCav:{sheet:'chart-fourth',row:7,rows:9},
  dragonRam:{sheet:'chart-fourth',row:8,rows:9},
  monk:{sheet:'chart-monk',row:0,rows:3},
  warriorMonk:{sheet:'chart-monk',row:1,rows:3},
  arhat:{sheet:'chart-monk',row:2,rows:3},
  bandit:{sheet:'chart-bandit',row:0,rows:3},
  outlaw:{sheet:'chart-bandit',row:1,rows:3},
  greenwoodKing:{sheet:'chart-bandit',row:2,rows:3},
  catapult:{sheet:'chart-catapult',row:0,rows:3},
  thunderCart:{sheet:'chart-catapult',row:1,rows:3},
  greatTrebuchet:{sheet:'chart-catapult',row:2,rows:3},
  navy:{sheet:'navy-v1',row:0,rows:3},
  mengchong:{sheet:'navy-v1',row:1,rows:3},
  louchuan:{sheet:'navy-v1',row:2,rows:3},
};
/** 진화표의 겉모습 설명: 전용 그림은 단계 장비가 그림에 이미 그려져 있어 갑옷 덧그리기 규칙 대신 이 글을 쓴다. */
export const paintedLook:Partial<Record<UnitClass,string>>={
  elephant:'가죽·밧줄 하네스 · 얇은 안장 덮개 · 단독 기수',
  warElephant:'보강 가죽 하네스 · 누빔 방호포 · 머리 철갑 · 난간 좌석',
  elephantKing:'다중 체결 하네스 · 측면 비늘갑 · 상아 보호구 · 2인승 전투 누각',
  rattan:'등나무 갑옷 · 등투구 · 큰 둥근 등패 · 환도',
  rattanElite:'붉은 술 투구 · 비늘 등갑 · 긴 직사각 등패 · 대도',
  wuguoRattan:'사자 문양 흑갑 · 못 박은 대형 등패 · 톱날 대도',
  assassin:'검은 두건 · 짙은 회색 무복 · 쌍단검',
  phantom:'복면 · 가죽 찰갑 · 검은 띠 · 쌍곡도',
  wraith:'뿔 투구 · 검은 판갑 · 긴 망토 · 어둠이 서린 쌍검',
  slinger:'두건 · 갈색 천 옷 · 손 투석구 · 작은 투석기',
  hurler:'철 투구 · 비늘 철갑 · 불덩이 투석기',
  boulderCorps:'깃 투구 · 금장 판갑 · 톱니 추 달린 대형 투석기',
  shaman:'갈색 무복 · 뼈 장식 · 깃털 달린 부적 지팡이',
  warlock:'금관 · 자줏빛 도포 · 떠도는 부적 · 삼지창 지팡이',
  demonKing:'뿔 투구 · 검은 갑주 · 마기 구슬 · 붉은 요검',
  maiden:'흰 저고리 · 붉은 치마 · 방울 · 부채',
  priestess:'금 비녀 · 청록 비단옷 · 나뭇가지 · 거울',
  celestial:'하늘거리는 비단 띠 · 연꽃 · 꽃잎 바람 · 맨발',
  infantry:'푸른 두건 · 가죽 조끼 · 둥근 나무 방패 · 환도',
  shieldGuard:'철 투구 · 비늘 철갑 · 긴 사각 방패 · 환도',
  royalGuard:'검은 깃 투구 · 금장 비늘갑 · 금테 방패 · 불꽃 서린 환도',
  spearman:'푸른 두건 · 가죽 조끼 · 장창',
  pikeman:'철 투구 · 비늘 찰갑 · 붉은 술 장창',
  halberdier:'검은 깃 투구 · 금테 흑갑 · 월아 대부',
  archer:'푸른 두건 · 가죽 조끼 · 짧은 활 · 화살통',
  longbow:'철 투구 · 비늘 철갑 · 큰 활',
  sharpshooter:'붉은 술 금투구 · 금갑 · 용머리 장궁 · 망토',
  cavalry:'푸른 무복 · 갈색 말 · 창',
  lancer:'철 투구 · 찰갑 · 마갑 두른 말 · 붉은 술 기창',
  tigerRider:'녹색 망토 · 호피 마의 · 검은 말 · 월아극',
  heavyCav:'철 투구 · 찰갑 · 앞가슴 마갑 두른 갈색 말 · 장창',
  ironCav:'깃 투구 · 비늘 철갑 · 온몸 비늘 마갑 · 깃발 장창',
  ironPagoda:'뿔 장식 흑금 판갑 · 금장 판 마갑 · 군기 · 기창',
  xiliang:'철 투구 · 가죽 찰갑 · 반 마갑 · 장창',
  feixiong:'깃 투구 · 비늘 철갑 · 비늘 마갑 · 철퇴창',
  liangzhouIron:'가시 달린 흑금 갑주 · 판 마갑 · 언월도',
  crossbow:'두건 · 가죽 갑옷 · 쇠뇌',
  repeater:'철 투구 · 비늘 찰갑 · 연노',
  greatBow:'금장 투구 · 붉은 금갑 · 대형 쇠뇌',
  strategist:'두건 · 청록 도포 · 죽간',
  tactician:'관 · 흰 도포 · 깃털 부채',
  mastermind:'금관 · 자줏빛 도포 · 떠도는 부적 · 불꽃 책략',
  fengshui:'상투 · 녹황 도포 · 나침반 거울 · 지팡이',
  sage:'높은 관 · 녹색 비단 도포 · 호리병 · 불진',
  immortal:'금테 흰 선의 · 연꽃 지팡이 · 빛 구슬',
  horseArcher:'두건 · 가죽 옷 · 갈색 말 · 단궁',
  nomad:'털 모자 · 찰갑 · 갈색 말 · 각궁',
  whiteHorse:'은 투구 · 은갑 · 백마 · 장궁',
  taoist:'상투 · 남백 도포 · 목검 · 부적',
  stormSage:'금테 남색 도포 · 뇌신 망치 · 번개 구름',
  thunderGod:'금관 · 남색 법복 · 떠도는 뇌고 · 번개 지팡이',
  ram:'초가 지붕 수레 · 통나무 충목 · 미는 병사',
  ironRam:'철판 지붕 · 가시 · 용머리 충목',
  cloudRam:'거북 등 철갑 수레 · 용머리 충각 · 연기',
  engineer:'두건 · 작업복 · 망치·삽',
  sapper:'철 투구 · 가죽 찰갑 · 큰 망치 · 목책',
  masterBuilder:'깃 투구 · 금테 갑옷 · 도끼 · 방패',
  navy:'쪽배 · 갈고리창 · 둥근 방패',
  mengchong:'지붕 덮은 몽충선 · 뱃전 궁수',
  louchuan:'깃발 꽂은 다층 누선 · 투석대',
};
/** 전장 자세 번호 → 시트 칸. 0 대기 · 1 공격 준비 · 2 공격 · 3 책략 · 4~7 걷기(짝수 내딛음) · 8~11 반응. */
export function paintedTroopFrame(pose:number,f:PaintedFrames=STRIDE){
  if(pose>=8)return pose===9||pose===11?0:f.hit;
  if(pose>=4)return pose%2===0?f.walk[0]:f.walk[1];
  if(pose===3)return f.cast;
  return pose===1?f.attack[0]:pose===2?f.attack[1]:0;
}
