/** Recorded CC0 samples in public/sfx (see docs/tech/sound-credits.md). Generated from the
 * selection script; each group lists its takes. Zheng takes carry their measured MIDI pitch. */
export const SAMPLE_GROUPS:Record<string,{files:string[];midi?:number[]}>={
  'swing':{files:["swing-0.wav", "swing-1.wav", "swing-2.wav", "swing-3.wav", "swing-4.wav", "swing-5.wav"]},
  'slash':{files:["slash-0.wav", "slash-1.wav", "slash-2.wav", "slash-3.wav", "slash-4.wav", "slash-5.wav"]},
  'blade':{files:["blade-0.wav", "blade-1.wav", "blade-2.wav", "blade-3.wav", "blade-4.wav", "blade-5.wav"]},
  'anvil':{files:["anvil-0.wav", "anvil-1.wav", "anvil-2.wav"]},
  'metal-hit':{files:["metal-hit-0.wav", "metal-hit-1.wav", "metal-hit-2.wav", "metal-hit-3.wav", "metal-hit-4.wav"]},
  'plate-hit':{files:["plate-hit-0.wav", "plate-hit-1.wav", "plate-hit-2.wav", "plate-hit-3.wav", "plate-hit-4.wav"]},
  'punch':{files:["punch-0.wav", "punch-1.wav", "punch-2.wav", "punch-3.wav"]},
  'flesh':{files:["flesh-0.wav", "flesh-1.wav", "flesh-2.wav"]},
  'evade':{files:["evade-0.wav", "evade-1.wav", "evade-2.wav", "evade-3.wav"]},
  'shield':{files:["shield-0.wav", "shield-1.wav", "shield-2.wav", "shield-3.wav", "shield-4.wav"]},
  'draw':{files:["draw-0.wav", "draw-1.wav", "draw-2.wav", "draw-3.wav", "draw-4.wav"]},
  'arrow-fly':{files:["arrow-fly-0.wav", "arrow-fly-1.wav", "arrow-fly-2.wav", "arrow-fly-3.wav"]},
  'arrow-thunk':{files:["arrow-thunk-0.wav", "arrow-thunk-1.wav", "arrow-thunk-2.wav", "arrow-thunk-3.wav"]},
  'latch':{files:["latch-0.wav", "latch-1.wav", "latch-2.wav"]},
  'wood-crack':{files:["wood-crack-0.wav", "wood-crack-1.wav", "wood-crack-2.wav", "wood-crack-3.wav"]},
  'creak':{files:["creak-0.wav", "creak-1.wav", "creak-2.wav"]},
  'rock-break':{files:["rock-break-0.wav", "rock-break-1.wav", "rock-break-2.wav", "rock-break-3.wav", "rock-break-4.wav"]},
  'stones':{files:["stones-0.wav", "stones-1.wav", "stones-2.wav", "stones-3.wav"]},
  'wood-break':{files:["wood-break-0.wav", "wood-break-1.wav", "wood-break-2.wav", "wood-break-3.wav", "wood-break-4.wav"]},
  'ratchet':{files:["ratchet-0.wav", "ratchet-1.wav"]},
  'footstep':{files:["footstep-0.wav", "footstep-1.wav", "footstep-2.wav", "footstep-3.wav", "footstep-4.wav", "footstep-5.wav"]},
  'chain':{files:["chain-0.wav", "chain-1.wav", "chain-2.wav"]},
  'cloth':{files:["cloth-0.wav", "cloth-1.wav", "cloth-2.wav", "cloth-3.wav"]},
  'splash':{files:["splash-0.wav", "splash-1.wav", "splash-2.wav", "splash-3.wav", "splash-4.wav", "splash-5.wav"]},
  'water-loop':{files:["water-loop-0.wav", "water-loop-1.wav"]},
  'ocean':{files:["ocean-0.wav"]},
  'fire':{files:["fire-0.wav", "fire-1.wav", "fire-2.wav", "fire-3.wav", "fire-4.wav"]},
  'spell':{files:["spell-0.wav", "spell-1.wav"]},
  'boom':{files:["boom-0.wav", "boom-1.wav", "boom-2.wav", "boom-3.wav"]},
  'zap':{files:["zap-0.wav"]},
  'hammer':{files:["hammer-0.wav", "hammer-1.wav", "hammer-2.wav", "hammer-3.wav", "hammer-4.wav"]},
  'pain':{files:["pain-0.wav", "pain-1.wav", "pain-2.wav", "pain-3.wav"]},
  'death':{files:["death-0.wav", "death-1.wav", "death-2.wav", "death-3.wav"]},
  'grunt':{files:["grunt-0.wav", "grunt-1.wav", "grunt-2.wav", "grunt-3.wav", "grunt-4.wav"]},
  'book':{files:["book-0.wav", "book-1.wav", "book-2.wav"]},
  'click':{files:["click-0.wav", "click-1.wav", "click-2.wav"]},
  'open':{files:["open-0.wav", "open-1.wav"]},
  'gong':{files:["gong-0.wav", "gong-1.wav", "gong-2.wav"]},
  'gong-light':{files:["gong-light-0.wav", "gong-light-1.wav"]},
  'bass-drum':{files:["bass-drum-0.wav", "bass-drum-1.wav", "bass-drum-2.wav"]},
  'frame-drum':{files:["frame-drum-0.wav", "frame-drum-1.wav", "frame-drum-2.wav"]},
  'woodblock':{files:["woodblock-0.wav", "woodblock-1.wav", "woodblock-2.wav"]},
  'cymbal':{files:["cymbal-0.wav", "cymbal-1.wav"]},
  'chime':{files:["chime-0.wav", "chime-1.wav", "chime-2.wav", "chime-3.wav", "chime-4.wav"]},
  'bell-tree':{files:["bell-tree-0.wav", "bell-tree-1.wav"]},
  'handbell':{files:["handbell-0.wav", "handbell-1.wav", "handbell-2.wav"]},
  'horn':{files:["horn-0.wav", "horn-1.wav"]},
  'zheng':{files:["zheng-0.wav", "zheng-1.wav", "zheng-2.wav", "zheng-3.wav", "zheng-4.wav", "zheng-5.wav", "zheng-6.wav", "zheng-7.wav", "zheng-8.wav", "zheng-9.wav", "zheng-10.wav", "zheng-11.wav", "zheng-12.wav", "zheng-13.wav", "zheng-14.wav", "zheng-15.wav"], midi:[47, 71.2, 70.9, 49.2, 61.4, 72.9, 51.2, 63.1, 75.1, 54.1, 65.9, 78.1, 56.1, 68, 80.2, 59.1]},
};
export const SAMPLE_ORIGINS:Record<string,string[]>={
  'swing':["cc0sounds/Micro Pack - Organic Wooshes/Classic Swish 1.wav", "cc0sounds/Micro Pack - Organic Wooshes/Classic Swish 2.wav", "cc0sounds/Micro Pack - Organic Wooshes/Swish 1.wav", "cc0sounds/Micro Pack - Organic Wooshes/Swish 2.wav", "cc0sounds/Micro Pack - Organic Wooshes/Swish 3.wav", "cc0sounds/Micro Pack - Organic Wooshes/Swish 5.wav"],
  'slash':["cc0sounds/Micro Pack - Organic Wooshes/Slash.wav", "cc0sounds/kenney_rpgaudio/Audio/knifeSlice.ogg", "cc0sounds/kenney_rpgaudio/Audio/knifeSlice2.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_strike1.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_strike2.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_strike3.ogg"],
  'blade':["cc0sounds/80-CC0-RPG-SFX/blade_01.ogg", "cc0sounds/80-CC0-RPG-SFX/blade_02.ogg", "cc0sounds/80-CC0-RPG-SFX/blade_03.ogg", "cc0sounds/80-CC0-RPG-SFX/metal_01.ogg", "cc0sounds/80-CC0-RPG-SFX/metal_02.ogg", "cc0sounds/80-CC0-RPG-SFX/metal_03.ogg"],
  'anvil':["VCSL/Idiophones/Struck Idiophones/Anvil/Anvil_Hit1_v2_rr1_Mid.wav", "VCSL/Idiophones/Struck Idiophones/Anvil/Anvil_Hit2_v2_rr1_Mid.wav", "VCSL/Idiophones/Struck Idiophones/Anvil/Anvil_Hit3_v2_rr1_Mid.wav"],
  'metal-hit':["cc0sounds/kenney_impactsounds/Audio/impactMetal_heavy_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_heavy_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_medium_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_medium_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_medium_002.ogg"],
  'plate-hit':["cc0sounds/kenney_impactsounds/Audio/impactPlate_heavy_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_heavy_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_medium_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_medium_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlate_medium_002.ogg"],
  'punch':["cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_002.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPunch_heavy_003.ogg"],
  'flesh':["cc0sounds/warfork-cc0/sounds/weapons/blade_hitflsh1.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_hitflsh2.ogg", "cc0sounds/warfork-cc0/sounds/weapons/blade_hitflsh3.ogg"],
  'evade':["cc0sounds/Micro Pack - Organic Wooshes/Gentle Swish.wav", "cc0sounds/Micro Pack - Organic Wooshes/Twirl Smol 1.wav", "cc0sounds/Micro Pack - Organic Wooshes/Twirl Smol 2.wav", "cc0sounds/Micro Pack - Organic Wooshes/Twirl Smol 3.wav"],
  'shield':["cc0sounds/kenney_impactsounds/Audio/impactMetal_light_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactMetal_light_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_000.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_001.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_002.ogg"],
  'draw':["cc0sounds/Micro Pack - Kitchen Knives/Big Knife - Unsheath 1.wav", "cc0sounds/Micro Pack - Kitchen Knives/Big Knife - Unsheath 2.wav", "cc0sounds/kenney_rpgaudio/Audio/drawKnife1.ogg", "cc0sounds/kenney_rpgaudio/Audio/drawKnife2.ogg", "cc0sounds/kenney_rpgaudio/Audio/drawKnife3.ogg"],
  'arrow-fly':["cc0sounds/Micro Pack - Organic Wooshes/Whistle 1.wav", "cc0sounds/Micro Pack - Organic Wooshes/Whistle 2.wav", "cc0sounds/Micro Pack - Organic Wooshes/Whistle 3.wav", "cc0sounds/Micro Pack - Organic Wooshes/Whistle 4.wav"],
  'arrow-thunk':["cc0sounds/Micro Pack - Organic Wooshes/Thunk 1.wav", "cc0sounds/Micro Pack - Organic Wooshes/Thunk 2.wav", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_003.ogg", "cc0sounds/kenney_impactsounds/Audio/impactPlank_medium_004.ogg"],
  'latch':["cc0sounds/kenney_rpgaudio/Audio/beltHandle1.ogg", "cc0sounds/kenney_rpgaudio/Audio/metalClick.ogg", "cc0sounds/kenney_rpgaudio/Audio/metalLatch.ogg"],
  'wood-crack':["cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_02.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_03.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_cracking_04.ogg"],
  'creak':["cc0sounds/kenney_rpgaudio/Audio/creak1.ogg", "cc0sounds/kenney_rpgaudio/Audio/creak2.ogg", "cc0sounds/kenney_rpgaudio/Audio/creak3.ogg"],
  'rock-break':["cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_breaking_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_breaking_02.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_breaking_03.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_falling_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_rock_falling_02.ogg"],
  'stones':["cc0sounds/80-CC0-RPG-SFX/stones_01.ogg", "cc0sounds/80-CC0-RPG-SFX/stones_02.ogg", "cc0sounds/80-CC0-RPG-SFX/stones_03.ogg", "cc0sounds/80-CC0-RPG-SFX/stones_04.ogg"],
  'wood-break':["cc0sounds/100-CC0-wood-metal-SFX/wood_breaking_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_breaking_02.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_slam_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_wood_breaking_01.ogg", "cc0sounds/75-cc0-breaking-falling-hit-sfx/bfh1_wood_breaking_02.ogg"],
  'ratchet':["VCSL/Idiophones/Struck Idiophones/Ratchet/Ratchet1_Slow_rr1_Mid.wav", "VCSL/Idiophones/Struck Idiophones/Ratchet/Ratchet2_Slow_rr1_Mid.wav"],
  'footstep':["cc0sounds/kenney_impactsounds/Audio/footstep_concrete_000.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_concrete_001.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_000.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_001.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_002.ogg", "cc0sounds/kenney_impactsounds/Audio/footstep_grass_003.ogg"],
  'chain':["cc0sounds/80-CC0-RPG-SFX/chain_01.ogg", "cc0sounds/80-CC0-RPG-SFX/chain_02.ogg", "cc0sounds/80-CC0-RPG-SFX/chain_03.ogg"],
  'cloth':["cc0sounds/kenney_rpgaudio/Audio/cloth1.ogg", "cc0sounds/kenney_rpgaudio/Audio/cloth2.ogg", "cc0sounds/kenney_rpgaudio/Audio/cloth3.ogg", "cc0sounds/kenney_rpgaudio/Audio/cloth4.ogg"],
  'splash':["cc0sounds/40-cc0-water-splash-slime-sfx/splash_01.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_02.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_03.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_04.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_05.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/splash_06.ogg"],
  'water-loop':["cc0sounds/40-cc0-water-splash-slime-sfx/loop_water_01.ogg", "cc0sounds/40-cc0-water-splash-slime-sfx/loop_water_02.ogg"],
  'ocean':["VCSL/Membranophones/Other Membranophones/Ocean Drum/OceanDrum_Sus_1_Mid.wav"],
  'fire':["cc0sounds/80-CC0-RPG-SFX/spell_fire_01.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_02.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_03.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_04.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_fire_05.ogg"],
  'spell':["cc0sounds/80-CC0-RPG-SFX/spell_01.ogg", "cc0sounds/80-CC0-RPG-SFX/spell_02.ogg"],
  'boom':["cc0sounds/25-CC0-bang-sfx/cannon_01.ogg", "cc0sounds/25-CC0-bang-sfx/cannon_02.ogg", "cc0sounds/25-CC0-bang-sfx/cannon_03.ogg", "cc0sounds/warfork-cc0/sounds/weapons/gren_strong_explosion1.ogg"],
  'zap':["cc0sounds/warfork-cc0/sounds/weapons/electrobolt_hit.ogg"],
  'hammer':["cc0sounds/100-CC0-wood-metal-SFX/hammer_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/hammer_02.ogg", "cc0sounds/100-CC0-wood-metal-SFX/hammer_03.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_hammer_01.ogg", "cc0sounds/100-CC0-wood-metal-SFX/wood_hammer_02.ogg"],
  'pain':["cc0sounds/warfork-cc0/sounds/players/male/pain100.ogg", "cc0sounds/warfork-cc0/sounds/players/male/pain25.ogg", "cc0sounds/warfork-cc0/sounds/players/male/pain50.ogg", "cc0sounds/warfork-cc0/sounds/players/male/pain75.ogg"],
  'death':["cc0sounds/80-CC0-creature-SFX/scream_01.ogg", "cc0sounds/80-CC0-creature-SFX/scream_02.ogg", "cc0sounds/warfork-cc0/sounds/players/male/death.ogg", "cc0sounds/warfork-cc0/sounds/players/male/falldeath.ogg"],
  'grunt':["cc0sounds/80-CC0-creature-SFX/grunt_01.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_02.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_03.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_04.ogg", "cc0sounds/80-CC0-creature-SFX/grunt_05.ogg"],
  'book':["cc0sounds/kenney_rpgaudio/Audio/bookFlip1.ogg", "cc0sounds/kenney_rpgaudio/Audio/bookFlip2.ogg", "cc0sounds/kenney_rpgaudio/Audio/bookFlip3.ogg"],
  'click':["cc0sounds/kenney_interfacesounds/Audio/click_001.ogg", "cc0sounds/kenney_interfacesounds/Audio/click_002.ogg", "cc0sounds/kenney_interfacesounds/Audio/click_003.ogg"],
  'open':["cc0sounds/kenney_interfacesounds/Audio/open_001.ogg", "cc0sounds/kenney_interfacesounds/Audio/open_002.ogg"],
  'gong':["VCSL/Idiophones/Struck Idiophones/Gong 1/gong_f.wav", "VCSL/Idiophones/Struck Idiophones/Gong 1/gong_mf.wav", "VCSL/Idiophones/Struck Idiophones/Gong 2/hit_full1.mp3"],
  'gong-light':["VCSL/Idiophones/Struck Idiophones/Gong 2/hit_light1.mp3", "VCSL/Idiophones/Struck Idiophones/Gong 2/hit_light2.mp3"],
  'bass-drum':["VCSL/Membranophones/Struck Membranophones/Bass Drum 1/BDrumNew_hit_v5_rr1_Sum.wav", "VCSL/Membranophones/Struck Membranophones/Bass Drum 1/BDrumNew_hit_v7_rr1_Sum.wav", "VCSL/Membranophones/Struck Membranophones/Bass Drum 1/BDrumNew_hit_v7_rr2_Sum.wav"],
  'frame-drum':["VCSL/Membranophones/Struck Membranophones/Frame Drum/HDrumL_Hit_v3_rr1_Sum.wav", "VCSL/Membranophones/Struck Membranophones/Frame Drum/HDrumL_Hit_v3_rr2_Sum.wav", "VCSL/Membranophones/Struck Membranophones/Frame Drum/HDrumS_Hit_v3_rr1_Sum.wav"],
  'woodblock':["VCSL/Idiophones/Struck Idiophones/Woodblock/wood_click_f_rr1.wav", "VCSL/Idiophones/Struck Idiophones/Woodblock/wood_click_f_rr2.wav", "VCSL/Idiophones/Struck Idiophones/Woodblock/wood_click_mp.wav"],
  'cymbal':["VCSL/Idiophones/Struck Idiophones/Clash Cymbals 1/cymbal_crash1_mf1.wav", "VCSL/Idiophones/Struck Idiophones/Clash Cymbals 1/cymbal_crash1_short1.wav"],
  'chime':["VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_A4_r01_main.wav", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_C5_r01_main.wav", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_C6_r01_main.wav", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_D5_r01_main.wav", "VCSL/Idiophones/Struck Idiophones/Hand Chimes/sus_E5_r01_main.wav"],
  'bell-tree':["VCSL/Idiophones/Struck Idiophones/Bell Tree/Stroke/BellTree_Stroke_1_Mid.wav", "VCSL/Idiophones/Struck Idiophones/Bell Tree/Stroke/BellTree_Stroke_3_Mid.wav"],
  'handbell':["VCSL/Idiophones/Struck Idiophones/Hand Bells, Nepalese/HB_1.wav", "VCSL/Idiophones/Struck Idiophones/Hand Bells, Nepalese/HB_2.wav", "VCSL/Idiophones/Struck Idiophones/Hand Bells, Nepalese/HB_3.wav"],
  'horn':["VCSL/Aerophones/Lip Aerophones/Didgeridoo/Didgeridoo1_Sus2_Main.wav", "VCSL/Aerophones/Lip Aerophones/Didgeridoo/Didgeridoo1_Sus3_Main.wav"],
  'zheng':["VCSL/Chordophones/Zithers/Dan Tranh/Normal/B1_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/B3_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/B4_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/C#2_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/C#3_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/C#4_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/D#2_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/D#3_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/D#4_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/F#2_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/F#3_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/F#4_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/G#2_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/G#3_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/G#4_mf_1.wav", "VCSL/Chordophones/Zithers/Dan Tranh/Normal/b2_mf_1.wav"],
};

/** One layer of a sound: a recorded group, or `synth` to keep the synthesized recipe. */
export interface SampleLayer {group?:string;synth?:boolean;gain?:number;delay?:number;rate?:number}
const L=(group:string,gain=1,delay=0,rate=1):SampleLayer=>({group,gain,delay,rate});
const SYNTH=(gain=1,delay=0):SampleLayer=>({synth:true,gain,delay});
/**
 * How each sound name is built from recordings. Names not listed (gallop, neigh, cheer…)
 * stay fully synthesized because no CC0 recording close enough was available.
 */
export const SAMPLE_LAYERS:Record<string,SampleLayer[]>={
  swing:[L('swing')],
  clash:[L('blade'),L('anvil',.35,.005)],
  stab:[L('slash',.8),L('flesh',.9,.04)],
  'armor-hit':[L('plate-hit'),L('punch',.6)],
  'heavy-hit':[L('punch'),L('plate-hit',.8,.01),L('metal-hit',.45,.02)],
  evade:[L('evade')],
  guard:[L('shield')],
  'bow-release':[SYNTH(.45),L('arrow-fly',.9,.03)],
  'crossbow-release':[L('latch',.8),L('arrow-fly',.8,.06)],
  'arrow-hit':[L('arrow-thunk')],
  'arrow-volley':[L('arrow-fly',.7),L('arrow-fly',.6,.06,1.08),L('arrow-fly',.6,.12,.93),L('arrow-thunk',.8,.45),L('arrow-thunk',.7,.52)],
  'catapult-launch':[L('wood-crack'),L('creak',.6),L('swing',.7,.15,.65)],
  'boulder-hit':[L('rock-break'),L('boom',.5,0,1.3),L('stones',.6,.1)],
  'ram-hit':[L('wood-break'),L('bass-drum',.9),L('metal-hit',.4,.01)],
  wheels:[L('ratchet',.7),L('creak',.5,.1)],
  march:[L('footstep',.8),L('footstep',.7,.17),L('footstep',.75,.34),L('chain',.25,.05)],
  robe:[L('cloth')],
  oars:[L('splash',.6),L('creak',.4,.1),L('splash',.45,.5,1.1)],
  shout:[L('grunt')],
  pain:[L('pain')],
  death:[L('death')],
  'battle-cry':[SYNTH(.5),L('grunt',.6,0,.85),L('grunt',.55,.08,1.1),L('pain',.5,.15,.9),L('grunt',.5,.22,.95),L('pain',.45,.3,1.15),L('grunt',.45,.38,.8)],
  fire:[L('fire')],
  wind:[SYNTH(),L('swing',.5,.2,.6)],
  water:[L('splash'),L('water-loop',.7,.1),L('ocean',.5,.2)],
  thunder:[L('zap',.5),L('boom',1,.05,.8),SYNTH(.5,.1)],
  earth:[L('stones'),L('rock-break',.6,.05),L('chain',.6,.2)],
  confuse:[L('spell'),SYNTH(.45)],
  heal:[L('bell-tree',.8),L('chime',.6,.1),L('chime',.5,.25)],
  buff:[L('gong-light',.8),L('frame-drum',.7),L('chime',.4,.2)],
  repair:[L('hammer'),L('hammer',.9,.28),L('hammer',.85,.56)],
  crumble:[L('rock-break'),L('wood-break',.7,.1),L('stones',.6,.3)],
  gong:[L('gong')],
  'war-drum':[L('bass-drum'),L('bass-drum',.8,.32),L('bass-drum',1,.62)],
  'enemy-drum':[L('bass-drum',1,0,.8),L('bass-drum',.9,.5,.8)],
  horn:[SYNTH(.6),L('horn',.8)],
  fanfare:[SYNTH(),L('cymbal',.6,.75),L('gong',.6,.75)],
  lament:[SYNTH(),L('gong-light',.5,1.4,.85)],
  'ui-click':[L('click',.8)],
  'ui-open':[L('open',.7)],
  page:[L('book',.8)],
  taiko:[L('bass-drum')],
  'taiko-small':[L('frame-drum')],
  woodblock:[L('woodblock')],
  'temple-bell':[L('handbell')],
};
